### ISSUE TITLE
[Bug] Potential bug with 3rd-party controller

### ISSUE THREAD

**Issue by ricardo404** [redphx/better-xcloud#1]
Hi, until yesterday, when I got version 1.2.1, I was able to press the home button on my controller without it activating the Xcloud menu during the game. With 1.3.1, this came back… Can it be removed again? Since I don’t use an official joystick, my home button is also the button that turns off the controller…
I don’t know if that was a coincidence. Thanks for the script.

![Screenshot_34](https://github.com/redphx/better-xcloud/assets/35298519/2b9f73d6-e5ca-4d75-ab3f-62da638a5e64)

**Comment by redphx** [comment]
I don't remember changing anything that could cause this. You could verify by downgrading the script to 1.2.1.

**Comment by ricardo404** [comment]
Hi redphx. Sorry for not returning, I ended up getting distracted this Sunday. Well, even doing a downgrade or a clean installation of version 1.2.1, it still enters the Xcloud menu when pressing home. Sorry, did you add this feature that inhibits the Xcloud menu during the game? It may have been some momentary coincidence that I associated with your script, or your script somehow temporarily inhibited it.

**Comment by redphx** [comment]
I still don't think it's because of Better xCloud. Or you could disable the script entirely and check again.  
Maybe it was a bug on xCloud's side and they fixed it.

**Comment by ricardo404** [comment]
From the way you wrote, I was scared. What happened is that before your script, when pressing the home button on the controller, it entered the Xcloud menu, this is normal. When I installed your script for the first time, it somehow inhibited this Xcloud menu, that is, when pressing the home button, it no longer entered the menu. This was beneficial for me.

**Comment by ricardo404** [comment]
> I still don't think it's because of Better xCloud. Or you could disable the script entirely and check again. Maybe it was a bug on xCloud's side and they fixed it.

It may have been that. I confess it was very good. I think we can now close this topic, since it did not come from your script, this menu inhibitor.
