### ISSUE TITLE
[Bug] "We are sorry" error message

### ISSUE THREAD

**Issue by tirbofish** [redphx/better-xcloud#102]
**Platform**
 - Device: Phone, Laptop, Desktop, TV...
 - OS: iOS...
 - Browser: Safari
 - Browser Version: idk
 - Better xCloud Version: 1.11

**Describe the bug**
Every time I try to play on xcloud with Userscripts on, it redirects me to an error page. 

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.
![IMG_0390](https://github.com/redphx/better-xcloud/assets/99516780/d20ae32e-fc6c-4daa-880f-9098ec29f677)

**Comment by redphx** [comment]
Duplicate #78  
This is a known problem, please check that issue.
