### ISSUE TITLE
[Bug] Disconnecting when better-xcloud is turned on

### ISSUE THREAD

**Issue by transbebek** [redphx/better-xcloud#107]
**Platform**
 - Device: MacBook Air (M2)
 - OS: Mac OS Ventura 13.0
 - Browser: Google Chrome
 - Browser Version: 115.0.5790.170 (Official Build) (arm64)
 - Better xCloud Version: 1.13

**Describe the bug**
The game session immediately kicks me out after the rocket animation. This only happens with the script running as I didn't have this issue once I turned it off on Tampermonkey.

**Screenshots/Videos**
Game launched: Atomic Heart
The error code reads EhiloTkGcVixZpmzMVkgNK.53
I received a different error code/message launching a different game, with the script turned on.

<img width="1710" alt="image" src="https://github.com/redphx/better-xcloud/assets/138798452/7f128787-304a-4a73-a6a0-7222c7d70719">

**Comment by redphx** [comment]
- Have you tried installing the previous version?  
- Did you have the "force high-quality codec" setting on?

**Comment by DVergil** [comment]
Mine was doing this when I used the Tizen user agent in this last update

**Comment by DVergil** [comment]
When I put it in Edge Windows it came back normally

**Comment by transbebek** [comment]
> * Have you tried installing the previous version?
> * Did you have the "force high-quality codec" setting on?

I had the high quality codec setting turned on. This didn’t occur in previous versions. I’ve tried different user agents but the outcome persists. I’ll try it again during the day and report back.

**Comment by ElVinz03** [comment]
Friend I had the same problem in the last 2 days,as soon as you can find a solution let me know,so I can solve it too ;)

**Comment by redphx** [comment]
@transbebek @ElVinz03 please take a screenshot of your Better xCloud's settings

**Comment by ElVinz03** [comment]
![Screenshot_20230817-150110_Reddit.jpg](https://github.com/redphx/better-xcloud/assets/128047880/bbc30041-76e2-42e7-9725-0ec662bb9fa0)

This with user agent profile Set to default

**Comment by transbebek** [comment]
> 

![image](https://github.com/redphx/better-xcloud/assets/138798452/ab853212-e490-4ab4-9c44-124ddbe0889d)

**Comment by ElVinz03** [comment]
Setting prefer IPv6 server solves the problem?

**Comment by transbebek** [comment]
> Setting prefer IPv6 server solves the problem?

Nope, I'm having the problem with or without it on. After the Xbox splash logo plays, I get a momentary black screen and then the "Disconnected from cloud gaming session" screen appears.

**Comment by ElVinz03** [comment]
@redphx Were you able to find a solution to this problem? I can no longer play anything because of this bug, all this since we updated to 1.13 :(

**Comment by ElVinz03** [comment]
@transbebek Try to uninstall and reinstall everything from scratch, I did so.

**Comment by ElVinz03** [comment]
@transbebek Try to uninstall and reinstall everything from scratch, I did so.

**Comment by transbebek** [comment]
> @transbebek Try to uninstall and reinstall everything from scratch, I did so.

Didn't work.

**Comment by redphx** [comment]
@transbebek @ElVinz03: please try this version https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by transbebek** [comment]
> @transbebek @ElVinz03: please try this version https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

That did just work! Goes in game after the Xbox splash screen like intended.

**Comment by ElVinz03** [comment]
> @transbebek @ElVinz03: please try this version https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

In the end I reinstalled everything from scratch but if problems occur again I will install the version above, thanks for the support ;)

**Comment by ElVinz03** [comment]
> @transbebek @ElVinz03: please try this version https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

In the end I reinstalled everything from scratch but if problems occur again I will install the version above, thanks for the support ;)

**Comment by redphx** [comment]
Fixed in 1.13.1.  
Thanks everyone for reporting.
