### ISSUE TITLE
[Bug] Stream doesn't start when the "Show game art" setting is off

### ISSUE THREAD

**Issue by DocS788** [redphx/better-xcloud#109]
**Platform**
 - Device: pc version
 - OS: Windows 10
 - Browser: canary edge
 - Browser Version: last
 - Better xCloud Version: last

**Describe the bug** (2)
-  the plugin does not appear in the first load of the page, i must refresh it to make it show
-  if i unpick the " show game art " in the loading screen option, the game does not start

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Please take a screenshot of your Better xCloud's settings

**Comment by DocS788** [comment]
![bxc_error](https://github.com/redphx/better-xcloud/assets/82037823/950fb073-feab-4838-b4e6-3b83c4785d7a)

**Comment by redphx** [comment]
@DocS788 does this still happen?

**Comment by DocS788** [comment]
> @DocS788 does this still happen?

hei :) Sorry for a late reply; so the game now starts also with" game art "check disabled, so good !

The other thing: not always the plugin is loaded at the browser start, but with a refresh it pops up, not a really hard issue :)
