### ISSUE TITLE
[Bug] ... Does not show up while the command is already running 

### ISSUE THREAD

**Issue by Chuoi97** [redphx/better-xcloud#111]
**Platform**
 - Device: Phone,
 - OS: Android,
 - Browser:  Kiwi...
 - Browser Version:116.0.5845.72
 - Better xCloud Version:1.13.1

**Describe the bug**
...Added but didn't run 
![Screenshot_2023-08-22-12-30-23-979_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/115388369/03e696fc-99f7-4e67-9b67-a8e23c230a33)

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.
![Screenshot_2023-08-22-12-32-18-395_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/115388369/e2ab2f14-0d06-43db-95e7-d336bbdab6ca)

**Comment by redphx** [comment]
It should work after refreshing several times

**Comment by Chuoi97** [comment]
> Nó sẽ hoạt động sau khi làm mới nhiều lần

When I fake vpn, it shows up.. I don't understand
