### ISSUE TITLE
[Feature] Customizable shortcuts

### ISSUE THREAD

**Issue by Haisom** [redphx/better-xcloud#117]
**I'm using:**  
- Device: Desktop
- OS: Windows 11
- Browser: Edge
  
**I want to suggest this feature:**  

Would it be possible to map keyboard/controller shortcuts to "Turn mic on/off" and "Show/hide touch controllers"? I'm aware it's not possible for fullscreen, as mentioned in #71. Is it possible to these other two though? Thank you!

**Comment by redphx** [comment]
I'm not sure if it's even possible. I can't interact directly with xCloud features once they are initialized.

**Comment by redphx** [comment]
Move to #378
