### ISSUE TITLE
[Bug] ios safari fullscreen

### ISSUE THREAD

**Issue by mkkurt** [redphx/better-xcloud#120]
**Platform**
 - Device: Phone
 - OS: iOS
 - Browser: Safari
 - Better xCloud Version: 1.14.1

**Describe the bug**

Userscripts seems not working on ios safari PWA, it does work on normal safari app but doesn't open fullscreen so unplayable. Do I missing something or is it a bug?

**Comment by redphx** [comment]
- Userscript only works in browser mode, not PWA.  
- Safari doesn't allow fullscreen unless it's PWA. You can only hide the address bar.

These are Safari's limitations. There's no way around it.
