### ISSUE TITLE
[Feature] Indication of Playtime Limit Reached

### ISSUE THREAD

**Issue by transbebek** [redphx/better-xcloud#124]
**I'm using:**  
- Device: MacBook Air (M2)
- OS: macOS Ventura 13.5.1
- Browser: Google Chrome
  
**I want to suggest this feature:**  
You know with Starfield being out, there will be more people playing for longer hours and no one wants to lose their saved progress, despite the autosave feature found in many games. I've experienced Xcloud closing in on itself close to the 4 and a half hour mark, playing Persona 5 before and today with Starfield. **I know we can already display playtime via the script, however, it would be an amazing feature if we can also know when it's time to restart the session without having to manually check the playtime.** This playtime limit is also found on Geforce Now, in which the limit is at 6 hours. As for the 4-ish hour limit of Xcloud, my measurement may be inaccurate and there is probably someone out there that knows it better.

**Comment by redphx** [comment]
I didn't know there is a time limit in xCloud. Have you tried asking Xbox Support or /r/xcloud about this? If anything xCloud should be the one who alert you about this.  

In the meantime you could setup an alarm on your phone.

**Comment by transbebek** [comment]
I’ll investigate and come back with a definitive answer. It isn’t a coincidence that the gaming session closes itself close to the four and a half hours. If you’ve used geforce now before, you’ll also see a countdown from 6 hours. When the timer gets closer to the end, geforce now lets you know.

**Comment by redphx** [comment]
I think this is more likely a bug.  
Or maybe your account is being limited by your parents. But in that case it should show an alert when the time is up.

**Comment by redphx** [comment]
@transbebek any updates?
