### ISSUE TITLE
[Bug] Audio problems 

### ISSUE THREAD

**Issue by DVergil** [redphx/better-xcloud#127]
**Platform**
 - Device: TV
 - OS: Android
 - Browser: Kiwi Browser
 - Browser Version: 116.0.5485.72
 - Better xCloud Version: 1.16

**Describe the bug**
... My game audio is completely broken in this latest version of better xcloud. After returning to 15.1 it is working normally 

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
How broken? Is it muted or something else? Do you have any other scripts/extensions outside of Tampermonkey installed?

**Comment by DVergil** [comment]
I used an extension to open in fullscreen mode, but I deleted it after better xcloud was able to do this and still leave the stream in 1080P

**Comment by DVergil** [comment]
Currently, I only have tampermonkey with the better xcloud script installed.

**Comment by DVergil** [comment]
I noticed this bug but I thought it was my browser or xcloud itself

**Comment by DVergil** [comment]
but after deciding to downgrade to the previous version, it is normal.

**Comment by DVergil** [comment]
The audio is very broken and sometimes it opens completely silent

**Comment by DVergil** [comment]
I assume it's the volume booster, but I didn't change anything. I just updated the extension

**Comment by redphx** [comment]
Yes the volume booster feature caused this problem, but I'm still trying to find out why.

**Comment by marlonvictor3161** [comment]
I have the same bug, I can't hear anything in games 😭

**Comment by DVergil** [comment]
On SAFARI my audio never work hahaha

**Comment by redphx** [comment]
@marlonvictor3161 @DVergil are you using "Samsung TV" User-Agent? Please share a screenshot of your Better xCloud's settings

**Comment by DVergil** [comment]
No, i’m using default android

**Comment by DVergil** [comment]
![Uploading Chrome.png…]()

**Comment by DVergil** [comment]
![image](https://github.com/redphx/better-xcloud/assets/89746439/558b742e-0a59-4191-a6f2-30b5bd00321b)

**Comment by DVergil** [comment]
The android user agent is only open fullscreen mode.

**Comment by redphx** [comment]
@DVergil @marlonvictor3161 please test this version: https://github.com/redphx/better-xcloud/raw/feature/volume_booster_fix/better-xcloud.user.js

**Comment by marlonvictor3161** [comment]
> @DVergil @marlonvictor3161 please test this version: https://github.com/redphx/better-xcloud/raw/feature/volume_booster_fix/better-xcloud.user.js

Only 1.15.1 is working correctly except 17 and 16 the audios in the Kiwi browser don't work

**Comment by redphx** [comment]
Your device, OS, browser?

**Comment by marlonvictor3161** [comment]
> Your device, OS, browser?

Yes, I use it in Kiwi browser

**Comment by DVergil** [comment]
I use kiwi on amazon fire stick

**Comment by DVergil** [comment]
On Google Tv ou Android TV, audio just never work fine.

It looks exactly the same way that the extension after the last version is causing

**Comment by DVergil** [comment]
Curious that the fire stick is the only one in which I test xcloud and it works well in audio and performance

**Comment by marlonvictor3161** [comment]
> Eu uso kiwi no Amazon Fire Stick

I play on my phone in the Kiwi browser after this update 1.16 everything got worse 😭

**Comment by DVergil** [comment]
The audio is still "failing" in this update.

I've already tried two different amazon and the problem still continues

**Comment by DVergil** [comment]
I'll try to delete the script and install only this version again

**Comment by marlonvictor3161** [comment]
> Vou tentar deletar o script e instalar apenas esta versão novamente

I'm going to update to the old version 1.15.1, the only one where the audio works correctly 😭

**Comment by marlonvictor3161** [comment]
![Screenshot_20230922-164638](https://github.com/redphx/better-xcloud/assets/145698764/ceff84b3-eac3-4d1e-8f27-fdcaf6561f0e)
This is the only one that is working

**Comment by DVergil** [comment]
I suspect that the volume booster has broken something.

**Comment by DVergil** [comment]
However, this bug is occurring which systems?

**Comment by marlonvictor3161** [comment]
> Porém, esse bug está ocorrendo em quais sistemas?

In all Fortnite games and other games

**Comment by DVergil** [comment]
I thought it was my stick, but only after version 1.16 and kind of weird

**Comment by marlonvictor3161** [comment]
> Suspeito que o amplificador de volume quebrou alguma coisa.

Yes, he was the one who caused this bug in the amplifier

**Comment by marlonvictor3161** [comment]
> Achei que era meu stick, mas só depois da versão 1.16 e meio estranho

A lot of people must have this bug ☹️

**Comment by DVergil** [comment]
I recommend removing the volume booster script only, so we can see how it would turn out @redphx

**Comment by redphx** [comment]
@DVergil @marlonvictor3161 please don't treat this as a chatroom. Don't send one message per comment, it's too difficult to read.

**Comment by redphx** [comment]
Try this version: https://github.com/redphx/better-xcloud/raw/feature/volume_booster_fix/better-xcloud.user.js  

You'll have an option to disable volume control feature in the main Settings.

**Comment by marlonvictor3161** [comment]
> @DVergil @marlonvictor3161por favor, não trate isso como uma sala de bate-papo. Não envie uma mensagem por comentário, é muito difícil de ler.

Sorry ☹️😭

**Comment by DVergil** [comment]
@redphx I disabled the function and it still remains buggy

**Comment by DVergil** [comment]
I think I'd better keep using version 1.5.1 for a while.

**Comment by marlonvictor3161** [comment]
> Acho melhor continuar usando a versão 1.5.1 por um tempo.

I'm going to do this too ☹️

**Comment by DVergil** [comment]
It's not so annoying.

I think it has improved a little
