### ISSUE TITLE
[Feature] Fps Counter 

### ISSUE THREAD

**Issue by DVergil** [redphx/better-xcloud#128]
**I'm using:**  
- Device: TV
- OS: Android
- Browser: Kiwi Browser
  
**I want to suggest this feature:**  
... It would be interesting to have an fps or latency counter in the corner of the screen always

**Comment by redphx** [comment]
![image](https://github.com/redphx/better-xcloud/assets/96280/27ff1b4f-bf49-4d54-b841-72e9376c61f4)

Double click on the stats bar and enable "Show stats when starting the game"

**Comment by DVergil** [comment]
Thanks
