### ISSUE TITLE
[Feature] DNS 1.1.1.1 

### ISSUE THREAD

**Issue by DVergil** [redphx/better-xcloud#129]
**I'm using:**  
- Device: TV
- OS: Android
- Browser: Kiwi Browser
  
**I want to suggest this feature:**  
![IMG_1228](https://github.com/redphx/better-xcloud/assets/89746439/7c252079-3a4f-47bd-932d-3bee304afaa8)

 the implementation of dns cloudfare would be interesting.
 This DNS or others can help a lot with response time in some cases.

**Comment by redphx** [comment]
Not possible with Javscript
