### ISSUE TITLE
Translate to more languages

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#130]
Help translating Better xCloud to more languages: https://crowdin.com/project/better-xcloud  
Discussion: https://github.com/redphx/better-xcloud/discussions/categories/translation  

Thanks.

**Comment by redphx** [comment]
@Haisom @ricardo404 could you help me translate it to Portuguese? Thanks.

**Comment by ricardo404** [comment]
> @Haisom @ricardo404 could you help me translate it to Portuguese? Thanks.

![image](https://github.com/redphx/better-xcloud/assets/35298519/a877cc9d-eaf0-43d4-bf4b-b4c03945fa4c)

Brazilian Portuguese is ready. Any other Brazilian can review the text to improve further.

**Comment by redphx** [comment]
@ricardo404 thanks a lot

**Comment by redphx** [comment]
@ricardo404 I added a new string for `Muted colors`. Also if the translated text is the same as original, please don't leave it empty, just put the same value (Ping, fps...). Thanks.

**Comment by redphx** [comment]
You can start testing the translation with this version: https://github.com/redphx/better-xcloud/raw/feature/translation/better-xcloud.user.js  
Some of the texts are a bit too long (the Setting's reload button, or `Stream settings` text), so please try to shorten it.

**Comment by ricardo404** [comment]
> You can start testing the translation with this version: https://github.com/redphx/better-xcloud/raw/feature/translation/better-xcloud.user.js Some of the texts are a bit too long (the Setting's reload button, or `Stream settings` text), so please try to shorten it.

Hey Red, I made some changes and adapted it to what you told me about PING, FPS, among others. Red, it is quite complicated, unlike English, to simplify some sentences, since Portuguese is more complex than English.

On my screen it was adequate, but I don't know how it is on mobile devices. If it gets big, could you add a function to reduce the size of the text according to the device's screen size? If you don't already have it.

**Comment by ricardo404** [comment]
> You can start testing the translation with this version: https://github.com/redphx/better-xcloud/raw/feature/translation/better-xcloud.user.js Some of the texts are a bit too long (the Setting's reload button, or `Stream settings` text), so please try to shorten it.

Could you re-release this link with my latest correction so I can see how it turned out?

**Comment by redphx** [comment]
@ricardo404 It's not easy to resize the text automatically to fit the layout so I'll avoid doing it.  

I updated the translation. Please try again.

**Comment by redphx** [comment]
Moved to discussion: https://github.com/redphx/better-xcloud/discussions/categories/translations
