### ISSUE TITLE
[Feature] Low resolutions for low pcs

### ISSUE THREAD

**Issue by leydsonandrey** [redphx/better-xcloud#135]
**I'm using:**  
- Device: Desktop
- OS: Windows 10 Pro
- Browser: Microsoft Edge
  
**I want to suggest this feature:** 

My pc has an extremely bad cpu that has difficulty processing streaming at "high" resolutions. I would like them to add resolutions such as: 480p, 360p, 240p and 144p.

**Comment by redphx** [comment]
Duplicate #123  
xCloud only supports 720p and 1080p.  

The upcoming version will allow you to lower the video's quality a little bit. You can try it here: https://github.com/redphx/better-xcloud/raw/feature/translation/better-xcloud.user.js  
It could help in your case.  
Set "Visual quality" to "Low", only available in Chrome/Edge...

**Comment by redphx** [comment]
@andrey-tar-xz please report back your result  

Not related, but you can check this page for the details of your GPU: `chrome://gpu/`  

<img width="402" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/e5e70b6a-f0e4-4339-b57f-4cc833d0708d">

**Comment by leydsonandrey** [comment]
> @andrey-tar-xz please report back your result  
> 
> Not related, but you can check this page for the details of your GPU: `chrome://gpu/`  
> 
> <img width="402" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/e5e70b6a-f0e4-4339-b57f-4cc833d0708d">
> 
> 

Apologies for the delay. Activating this option made streaming much better, but when the sharpness option is set to 1 or more, frames are lost. (Translated from Portuguese to English)

**Comment by andrey-tar-xz** [comment]
> @andrey-tar-xz please report back your result  
> 
> Not related, but you can check this page for the details of your GPU: `chrome://gpu/`  
> 
> <img width="402" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/e5e70b6a-f0e4-4339-b57f-4cc833d0708d">
> 
> 

Apologies for the delay. Activating this option made streaming much better, but when the sharpness option is set to 1 or more, frames are lost. (Translated from Portuguese to English)

**Comment by redphx** [comment]
yea, don't use the Clarity feature if your device is slow.
