### ISSUE TITLE
[Feature] Add Turkish language support

### ISSUE THREAD

**Issue by transbebek** [redphx/better-xcloud#136]
**I want to suggest this feature:**  
Hey! Xbox Cloud Streaming is currently not locally supported in Turkey; however, thanks to a VPN extension and your tampermonkey script, Xcloud has been actually usable. I've suggested this script to a few people to get them to use Xcloud and they're very thankful. I'd like to localize the script to Turkish to make its reach wider, since the number of Game Pass subscribers in the country is quite high, because of the pricing on games. Subscription is more viable but people don't know about Xcloud, since it is terrible without this script. As a translator specializing in software and video game localization, I'd like to contribute to this project as much as I can. Please let me know when you open a Turkish section on the Crowdin page. Thank you for all the hard work you've been putting into this small but quite useful project!

**Comment by redphx** [comment]
Hi, I've added the Turkish language. You can start translating using this link: https://crowdin.com/translate/better-xcloud/14/en-tr  

Thanks.

**Comment by redphx** [comment]
@transbebek You can start testing the translation with this version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js  

Please check and make sure the text doesn't break the UI.  

Thanks.

**Comment by transbebek** [comment]
@redphx I updated two strings, and with that, it's all done!

**Comment by redphx** [comment]
I updated the translation. Thanks.

**Comment by redphx** [comment]
@transbebek there is one new string. Please help me translating it. I'll add Turkish in the next release.

**Comment by transbebek** [comment]
@redphx Done!

**Comment by redphx** [comment]
Added in version 1.17.1. Thanks for the help.  
For future discussions, please use this post: https://github.com/redphx/better-xcloud/discussions/131
