### ISSUE TITLE
[Feature] Need help writing a more detailed guide on how to install on iOS

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#137]
My iPad is still running iOS 14 so I couldn't install the Userscripts extension in Safari (it requires iOS/iPadOS 15 or later).  
Some users are having trouble installing/activating Better xCloud in the Userscripts extension.  

If someone could write a more detailed installation guide with step-by-step screenshots would be great. And please make sure the languages of both System and Better xCloud are in English.  

Please post everything here in this issue and I'll create a wiki page.  
Thanks.

**Comment by GopherTheCoder** [comment]
Hi, I just installed the script on iPadOS 16,and I took some screenshots along the way.

First, install Userscript from App Store.

Once installed, go to Settings>Safari, choose "Extensions".
![IMG_0188.PNG](https://github.com/redphx/better-xcloud/assets/22365782/f4113163-70b1-47ea-bd25-bd53877649e4)

In "Extensions", turn on Userscripts.
![IMG_0189.PNG](https://github.com/redphx/better-xcloud/assets/22365782/24883f6f-ae4d-454a-ac5a-ffdac2beb1cc)

Then, open the newly installed Userscripts app found in home screen. Click "Set Userscripts Directory"
![IMG_0190.PNG](https://github.com/redphx/better-xcloud/assets/22365782/acb2fc5f-4a12-412f-aa11-d7216071730e)

Choose the directory where you put thr script.
![IMG_0191.PNG](https://github.com/redphx/better-xcloud/assets/22365782/25fa59cb-bc53-4bcc-978c-684188b63efa)

It should look like this once set.
![IMG_0192.PNG](https://github.com/redphx/better-xcloud/assets/22365782/8c76c0ed-1bec-4178-af81-4ea3686cb0bd)

In Safari, go to xbox.com/play.
Things may look like this before enabling the script.
Click extension button in address bar.
![IMG_0193.PNG](https://github.com/redphx/better-xcloud/assets/22365782/83084dc2-e00a-41b9-a41c-2ab4f1704da1)

Then click Userscripts.
![IMG_0194.PNG](https://github.com/redphx/better-xcloud/assets/22365782/13527a23-1958-45c6-9a8b-e5161045cbc9)

In dialog, choose "Always Allow".
![IMG_0195.PNG](https://github.com/redphx/better-xcloud/assets/22365782/92ebfcf6-1da4-4bac-b4a3-89781fa9b6ec)

Then
![IMG_0196.PNG](https://github.com/redphx/better-xcloud/assets/22365782/307a30fa-a1bc-4517-87b5-afafbcdfb6ba)

After enabling and refreshing the page, you can notice the "Get ready to play" button has changed to "Sign in", this indicate the script is already working.
![IMG_0197.PNG](https://github.com/redphx/better-xcloud/assets/22365782/91babd6c-4312-49d8-8df9-83b105cda59e)

Click the button on top-right, next to your profile avatar. (Don't know why it's ??? on my side)
![IMG_0198.PNG](https://github.com/redphx/better-xcloud/assets/22365782/4465d1d9-d5a4-4169-9461-6c9804b665be)

You can the Better xCloud settings panel.
![IMG_0199.PNG](https://github.com/redphx/better-xcloud/assets/22365782/264e28aa-0a69-4451-a88c-89ac9a3f4a7f)


I post all this from my phone, so I didn't do any image editing. Feel free to edit them, add arrows or something. You can also use other words to describe the steps. Anyway, the main purpose was just to provide all the screenshots.
Hope this help!

**Comment by redphx** [comment]
Thanks for the screenshots! I'll write the guide when I have time.

**Comment by redphx** [comment]
I'm writing the guide based on your screenshots, thanks again.  

I'd recommend creating a separate folder for the userscripts instead of choosing the Downloads folder, as it may load unexpected scripts from that folder.  

The reason you saw `???` instead of server name because the script wasn't loaded successfully. Just reload the page a few times and it will work.

**Comment by redphx** [comment]
Added: https://better-xcloud.github.io/safari/  

Thanks again.
