### ISSUE TITLE
Limit FPS

### ISSUE THREAD

**Issue by NikunjGupta01** [redphx/better-xcloud#138]
**I'm using:**  
- Device:pc
- OS:linux
- Browser:chorme or edge
  
I want an option to limit fps .As games that run at limit 30 fps look,run and feel very good and it is less intensive since browser in linux don't support hardware decding and in newer version sof browser it is very hard or impossible to enable it .I have test it with  playing forza on quality and performance mod.

**Comment by redphx** [comment]
Duplicate #44  
Not possible because the server decides the number of FPS.
