### ISSUE TITLE
Audio problems are completely muted, My cell phone is at 100% volume and no audio comes out from games on xcloud 😭 [Bug] ...

### ISSUE THREAD

**Issue by marlonvictor3161** [redphx/better-xcloud#139]
**Platform**
 - Device: Phone, Laptop, Desktop, TV...
 - OS: Windows, Android, iOS...
 - Browser: Chrome, Safari, Kiwi...
 - Browser Version:
 - Better xCloud Version:

**Describe the bug**
Bug in the audio there is no sound in the games is there a problem with this update 17 and 16 there is no sound in the games

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by DVergil** [comment]
Try on another browser

**Comment by marlonvictor3161** [comment]
> Experimente em outro navegador

Do you recommend another browser because I can only play on my cell phone?

**Comment by redphx** [comment]
Duplicate #127
