### ISSUE TITLE
[Bug] All black with version 1.4.2

### ISSUE THREAD

**Issue by ricardo404** [redphx/better-xcloud#14]
After updating to version 1.4.2, everything turned black, although you can hear the game sound in the background. When turning off the script it returns to normal. I will test 1.4.1.

![image](https://github.com/redphx/better-xcloud/assets/35298519/2bf116ac-a01a-4ae1-8ac0-e0e19081d4a0)

**Comment by ricardo404** [comment]
With 1.4.2 turned off

![image](https://github.com/redphx/better-xcloud/assets/35298519/f7cc3bb6-85eb-429b-9f69-fc7c2de89723)

**Comment by ricardo404** [comment]
Returns to normal using 1.4.1.

![image](https://github.com/redphx/better-xcloud/assets/35298519/f1404a2c-039a-4ae9-aa90-d2f31af57476)

**Comment by redphx** [comment]
Could you please try again with this fix: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by ricardo404** [comment]
> Could you please try again with this fix: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

Apparently it worked here. I updated the page and it didn’t go dark or try to form an image.

**Comment by redphx** [comment]
Thanks for reporting. It was bugged because I set the wrong codec.

**Comment by ricardo404** [comment]
I thank you for the Script. Redphx, I would like to ask you a question but I think it would be more appropriate via email, because the subject I want to ask you is sensitive… Do you have one? Thank you.

**Comment by redphx** [comment]
You could find me on reddit with the same username

**Comment by ricardo404** [comment]
Thank you, I think I found you, I will send a message soon, thank you.
