### ISSUE TITLE
[Feature] Remove "give feedback"

### ISSUE THREAD

**Issue by PotatoPTT** [redphx/better-xcloud#142]
**I'm using:**  
- Device: PC
- OS: Windows 11
- Browser: Edge
  
**I want to suggest this feature:**  
An option to remove the screen asking for feedback after you stop playing.

[Example](https://imgur.com/JnrZA93)

**Comment by KingNothing81** [comment]
I'm using "Better xCloud" on Android TV and quit games by just going "back" in the web browser. First press will exit full screen mode and second will bring me back to the xCloud website. This way I'm not asked to give "user feedback". 

So using the "back" button of your web browser to exit games, you should be able to bypass the "user feedback" prompt. And as the games are running in the cloud, it's not like force closing an app or pulling the plug. So I don't think it will have any negative effect.

**Comment by redphx** [comment]
Added this feature in 1.18
You can find the setting in `Stream/Disable post-stream feedback dialog`  

Thanks for the suggestion
