### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Nachhito** [redphx/better-xcloud#143]
**Platform**
 - Device: Phone, Laptop, Desktop, TV... windows 10 edge browser
 - OS: Windows, Android, iOS...
 - Browser: Chrome, Safari, Kiwi...
 - Browser Version:
 - Better xCloud Version:

**Describe the bug**
...doesnt work on gta oline, it says the session has expired

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Report it to xCloud
