### ISSUE TITLE
[Bug] Disabling social features doesn’t hide “find friends” box

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#147]
**Platform**
 - Device: Shield TV
 - OS: Android TV
 - Browser: Kiwi
 - Better xCloud Version: 1.17.2

**Describe the bug**
I don’t know if this can be considered a bug, but although I’ve checked “disable social features” in the settings, I can still see that big “find friends” box.

![IMG_0218](https://github.com/redphx/better-xcloud/assets/146887651/06ef0354-ef89-4f59-ad76-471112d7953e)

As I just want to play single player games and don’t have any “friends” on Xbox Live, I would really like to get rid of it. So maybe that’s something that could be fixed or added to the “disable social features” option.

Thanks.

**Comment by redphx** [comment]
Fixed in 1.18  
Thanks for reporting
