### ISSUE TITLE
[Feature] Include option to change trigger button for controller shortcuts

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#158]
**I'm using:**  
- Device: Nvidia Shield TV
- OS: Android TV
- Browser: Kiwi Browser
  
**I want to suggest this feature:**  

I think the controller shortcut feature added with the last update is a great addition. But currently you can only use it if your controller has a button that will bring up the Xbox Sidebar and identifies as "B16" on the gamepad testing site:

https://hardwaretester.com/gamepad

Unfortunately I don't have a button acting like this on my setup: Using a Shield controller with Kiwi browser on Android TV. And I think many other Android (TV) users will have a similiar problem: That the middle button on their controller, that might open the Xbox Sidebar when using it on a PC, will just act like a Android Home button when connected to an Android device. So pressing it will just exit the current app to the Android Home screen. 

To bypass this limitation I modified the script so the controller shortcuts can now be triggered with the START button. This way the shortcuts should work with all controllers on all platforms.

**And for future updates I think it would be a useful enhancement to add an option to "Better xCloud" that lets users change the shortcut's trigger button to START in the settings.** So all users will be able to use the feature. And for now and if @redphx doesn't mind, I can share my modified script with other users that are also affected by this limitation.

**Comment by redphx** [comment]
I chose the Home button because in some games holding the Start/Select button trigger an action.  
I plan to make the shortcut feature more customizable, but it takes more time so I wanna work on something else first.  

In the mean time, feel free to edit & share the modified version.

**Comment by KingNothing81** [comment]
> I chose the Home button because in some games holding the Start/Select button trigger an action. I plan to make the shortcut feature more customizable, but it takes more time so I wanna work on something else first.
> 
> In the mean time, feel free to edit & share the modified version.

Yes, I really understand prefering the HOME button as trigger. Especially for the screenshot feature, as the START button will usually pause games. And you don't want to take a screenshot of the pause menu. ;) But it's still possible to do even with the START button, if you press START once to pause the game. Then press and hold START a second time to continue the game and then press RB (while still holding START) to take the screenshot. So it's a little bit more complicated, but nothing a gamer can't handle. ;) And I think it's still better than not be able to use the shortcut feature at all.

And my suggestion would be to make this just optional. To continue to use the B16 button as default. But to add a checkbox "Use START button as trigger" for people like me that use a controller that lack that B16 button. In my opinion this would be good solution to make the feature useable for all of us. 

But yes, in the meantime, I can help myself. As long as it doesn't get more complex than replacing "HOME" with "START" in some lines of code. Because I have to admit that I don't have any real coding skills. ;)

**Comment by KingNothing81** [comment]
<s>So here is my modified script of the current version (2.0.2) that changes the trigger button for the shortcuts to START, just in case someone wants to have it:

https://drive.google.com/file/d/1twEGKVtS0hBkZtWUsFJ5V83y7tjX2aoO/view?usp=sharing</s>

So with the modified version it's now ...

START + LB = Take Screenshot
START + SELECT = Toggle Stats Bar

**Edit:** As my modified script had zero downloads, I won't continue to update this post. But if somebody reads this and wants to have it, you can leave me a message and I will upload and share the most current version with you.

**Comment by KingNothing81** [comment]
Just when I got myself a new controller, so I would be able to use the shortcuts without modifying the script, the feature was suspended to not conflict with MKB support. :(

But although I’m not affected by this anymore, I still think it would be helpful to make the shortcut feature more flexible in this regard when you bring it back. But for now I think it’s ok to close this issue.

**Comment by redphx** [comment]
The shortcut feature will be redesigned in the future

**Comment by KingNothing81** [comment]
> The shortcut feature will be redesigned in the future

Will the new shortcut feature make use of the same API needed for MKB support? 
Or will it also work on Android (TV)?

**Comment by redphx** [comment]
Yes, this feature will also work on Android TV
