### ISSUE TITLE
[Feature] SHOW CPU, GPU AND RAM USAGE DURING TRANSMISSION

### ISSUE THREAD

**Issue by DVergil** [redphx/better-xcloud#161]
**I'm using:**  
- Device: Amazon Fire Stick
- OS: Android TV
- Browser: Kiwi Browser
  
**I want to suggest this feature:**  

Sometimes I'm curious to know how much of my processor is being used during transmission to know reasons such as crashes or delay

**Comment by redphx** [comment]
Browser doesn't have API for these features

**Comment by Jotajota12** [comment]
Hello redphx...I play Fortnite on my cell phone, using xbox cloud...which
is the best browser? The default browser (kiwi) or edge+Microsoft??

Em qui., 23 de nov. de 2023 23:19, redphx ***@***.***>
escreveu:
