### ISSUE TITLE
[Bug] I can't turn on a certain option 

### ISSUE THREAD

**Issue by miauman** [redphx/better-xcloud#165]
**Platform**
 - Device: Phone
 - OS: Android
 - Browser: Kiwi
 - Better xCloud Version: 1.20

**Describe the bug**
I can't turn on the option to change the "Hz" and the control shortcut option. Every time I restart the tab it goes back to default 

**Screenshots/Videos**

https://github.com/redphx/better-xcloud/assets/65979810/d411d6c7-9f8c-4248-932c-a4057fbd4fc9

Lets I managed to solve it, on the site it said that it was in version 1.20 but the extension was in 1.18

**Comment by redphx** [comment]
Does it work with other settings?  
How do you install the extension?

**Comment by DVergil** [comment]
It's working normally here

**Comment by miauman** [comment]
> Does it work with other settings? How do you install the extension?

I've got it figured out. I didn't know I had to reinstall the "Better xCloud" extension, there on the xcloud website it appeared that it was on version 1.20 but in the extensions tab it was still on 1.18. Thank you for your attention
