### ISSUE TITLE
[Bug] v2.0 default polling rate of 50ms does *NOT* match the official polling rate

### ISSUE THREAD

**Issue by Diego-Perez-Botero** [redphx/better-xcloud#167]
By default, xbox.com/play is polling gamepad input every 4 milliseconds. As of v2.0 of better-xcloud, the default is being changed by the browser extension to be 50 milliseconds. This results in a noticeable increase in input latency that better-xcloud users will probably attribute to the service when it's actually being introduced by the browser extension. In general, default settings for the extension should be *DO NOTHING* (e.g., if xbox.com/play changes the official polling rate to 6 milliseconds or whatever else in the future, the extension should not have to be updated to reflect that).

**Comment by redphx** [comment]
Thanks for pointing that out!  

I was under the impression that this function defines the polling rate:  

```js
t.startGamepadPolling = () => {
    w || (w = setInterval(T, 50))
};
```

I tried to change the number from `50` to `200` and xCloud didn't recognize some of my button inputs.  
I couldn't find anywhere else that could be the 4ms polling rate as you stated. I'll try again. Thanks.


I made it so if the user selects the 50ms option, Better xCloud won't change the default value.

**Comment by Diego-Perez-Botero** [comment]
If you add a print to setTimeout, you'll find that the untouched code calls it with "4" as the second parameter. SetInterval isn't what's used for the actual polling.

SetTimeout (called N times) is more consistent than SetInterval.

**Comment by redphx** [comment]
I found it. Thank you for correcting me!  

I'll remove this feature in the next version.

**Comment by Diego-Perez-Botero** [comment]
Thank you for being open to feedback 🫶

**Comment by redphx** [comment]
Removed in 2.0.1  
Thanks for being such a cool dude 😁
