### ISSUE TITLE
[Bug] Cannot use Cloud search box with better xcloud installed

### ISSUE THREAD

**Issue by modemman11** [redphx/better-xcloud#168]
**Platform**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Edge
 - Browser Version: 119.0.2151.72
 - Better xCloud Version: 2.0

Attempting to use xcloud's built in search box attempts to launch remote play whenever I type any letter on my keyboard.

https://www.youtube.com/watch?v=TWDVarY7sCY

**Comment by redphx** [comment]
This bug is weird. Happened to me too.

**Comment by redphx** [comment]
Fixed in 2.0.1
