### ISSUE TITLE
[Feature] Controller Buttons Mapping 

### ISSUE THREAD

**Issue by Mobin735** [redphx/better-xcloud#169]
**I'm using:**  
- Device: Iqoo 
- OS: Android
- Browser: Kiwi
  
**I want to suggest this feature:**  
It should be great that I can change the mapping of the controller buttons because, in some games, it's hard to play with default mapping. You have to press RS for running, and at the same time, you have to move the R stick for looking, so it's kind of difficult.

**Comment by redphx** [comment]
Testing in #617

**Comment by redphx** [comment]
Added in 6.1.0
