### ISSUE TITLE
[Bug] Remote Play - Multiple Consoles (connects to wrong one)

### ISSUE THREAD

**Issue by blitz2kx** [redphx/better-xcloud#170]
**Platform**
 - Device: PC
 - OS: Windows 11
 - Browser: Chrome & Edge
 - Browser Version: Latest public
 - Better xCloud Version: Latest (2.01)

*
When clicking Remote Play and presented for my choice of consoles, the stream activates for the **opposite** console selected.

I have a SERIES-S and SERIES-X in my home. When I click to connect to the X, it attempts to connect to the S, and vise versa.

**Comment by redphx** [comment]
Thanks for reporting. I think I found the problem.  

Please test this:
1. Edit Better xCloud in Tampermonkey extension.
2. On line 2082, edit :
```js
REMOTE_PLAY_CONFIG = {
    serverId: con.serverId,
};

$connectButton.addEventListener('click', e => {
    ...
```
to
```js
$connectButton.addEventListener('click', e => {
    REMOTE_PLAY_CONFIG = {
      serverId: con.serverId,
    };
    ...
```

**Comment by blitz2kx** [comment]
Wow thanks for the fast response! I just did the code edit and it worked like a charm!! Connected to the correct console now, thank you.

**Comment by redphx** [comment]
Thanks for testing. I'll implement the fix in the next version.
