### ISSUE TITLE
[Bug] Remote play doesn't work

### ISSUE THREAD

**Issue by Trashinated1** [redphx/better-xcloud#171]
- Device: Desktop
 - OS: Windows 10
 - Browser: Chrome/Edge
 - Browser Version: 119
 - Better xCloud Version: 2.0.1
 - 
When trying to remote play on my Series S with remote play turned off, it immediately cuts to "We'll be right back".

![image](https://github.com/redphx/better-xcloud/assets/104871230/f288fb16-4c2c-48ee-81b4-c04ba3906133)

**Comment by Trashinated1** [comment]
Does remote play only work for users with Game Pass Ultimate?

**Comment by redphx** [comment]
What do you mean when saying "remote play turned off"?  
Are you subscribing to Game Pass, or you're using free tier to play Fortnite?  
I haven't tested this case.

**Comment by evanpaul14** [comment]
I get the same screen and I'm not currently subscribed to Game Pass Ultimate.

**Comment by redphx** [comment]
Let me check

**Comment by redphx** [comment]
@Trashinated1 @evanpaul14 please test this version: https://github.com/redphx/better-xcloud/raw/feature/remote_play_f2p_fix/better-xcloud.user.js

**Comment by Trashinated1** [comment]
> What do you mean when saying "remote play turned off"?  
> 
> Are you subscribing to Game Pass, or you're using free tier to play Fortnite?  
> 
> I haven't tested this case.

I meant turned on, I am using the free tier.

**Comment by Trashinated1** [comment]
> @Trashinated1 @evanpaul14 please test this version: https://github.com/redphx/better-xcloud/raw/feature/remote_play_f2p_fix/better-xcloud.user.js

Doesn’t work on iOS, haven’t tested on windows

**Comment by redphx** [comment]
I'll try again this weekend

**Comment by Trashinated1** [comment]
> I'll try again this weekend

Try replacing Starfield with Fortnite.

**Comment by evanpaul14** [comment]
I can confirm it doesn't work on Chrome on MacOS either.

**Comment by evanpaul14** [comment]
> @Trashinated1 @evanpaul14 please test this version: https://github.com/redphx/better-xcloud/raw/feature/remote_play_f2p_fix/better-xcloud.user.js

[https://github.com/evanpaul14/better-xcloud-fix/blob/main/Better%20xCloud.user.js](https://github.com/evanpaul14/better-xcloud-fix/blob/main/Better%20xCloud.user.js)

I was able to fix it by replacing line 2087 with this:
`const url = window.location.href.substring(0, 31) + '/launch/fortnite/BT5P2X999VH2#remote-play';`

**Comment by redphx** [comment]
> https://github.com/evanpaul14/better-xcloud-fix/blob/main/Better%20xCloud.user.js
> 
> I was able to fix it by replacing line 2087 with this: `const url = window.location.href.substring(0, 31) + '/launch/fortnite/BT5P2X999VH2#remote-play';`

Thanks. Let me implement it.

**Comment by somy05** [comment]
I’m still having this issue on 2.0.1

**Comment by redphx** [comment]
@Trashinated1 @evanpaul14 @superfastsi fixed in 2.0.2  
Thanks for reporting and testing.
