### ISSUE TITLE
[Feature] ...need fullscreen automatically on PC

### ISSUE THREAD

**Issue by egotriceps** [redphx/better-xcloud#172]
**I'm using:**  
- Device:PC
- OS:Win 10
- Browser:Edge
  
**I want to suggest this feature:**  
...It would be great if there's a function that fullscreen automatically.
  Do not need to press F11 to fullsrceen everytime launch the game.
  Thanks for such good game experience

**Comment by KingNothing81** [comment]
Using xCloud on Android TV, I think it would be nice if the browser would already switch to fullscreen mode when loading the xCloud website. ;)

https://github.com/redphx/better-xcloud/discussions/145

**Comment by redphx** [comment]
Duplicate #71
