### ISSUE TITLE
[Feature] Make using "Better xCloud" on Android TV more comfortable

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#174]
**I'm using:**  
- Device: Shield TV
- OS: Android TV
- Browser: Kiwi Browser
  
**I want to suggest this feature:**  

As an Android TV user I would be very happy about some future additions / modifications that make using "Better xCloud" on Android TV more comfortable. Because currently you need some sort of mouse support (physical mouse or an app) for many interactions. 

So making things more operable with the gamepad and/or the Android TV remote would feel like a great improvement for me.

**Comment by redphx** [comment]
Do the buttons on the remote have keycodes? You can test it here: https://keyjs.dev/

**Comment by KingNothing81** [comment]
> Do the buttons on the remote have keycodes? You can test it here: https://keyjs.dev/

Yes. I can also use Button Mapper to look them up. 

But there is also a list of Android keycodes here:
https://elementalx.org/button-mapper/android-key-codes/

I use this list to look up keycodes to assign additional functions to my remote buttons.

But actually ... some things already work with the remote. For example I can already use it in Kiwi browser to navigate to the server name and press OK to open the xCloud Settings. It's also possible to move from top to bottom and check/uncheck boxes. But the problem is that you can't see in which line you are. So you have to press OK to see which box gets (un-)ticked. So adding some kind of visual indicator here would already help a lot. But unfortunately it's not possible to open drop-down lists this way.

What also already works with the remote (or the controller) is moving from one item to another in the "three dot" menu. But at the moment there is no way to open it without touch / mouse support. That's why having a controller shortcut to open the menu would also be helpful.

I hope I could give you some useful information.

**Comment by KingNothing81** [comment]
> Do the buttons on the remote have keycodes? You can test it here: https://keyjs.dev/

I’ve visited this site now with Kiwi. And the keycodes shown there are different from the Android keycodes.

But yes … the D-Pad buttons (up/down/left/right) and media buttons (play/pause/fast forward/rewind) on my remote are registered on that site and show a keycode.

**Comment by redphx** [comment]
Please list all the possible keycodes

**Comment by KingNothing81** [comment]
On the D-Pad it reports:

Up: ArrowUp / ArrowUp / 38 / 38
Down: ArrowDown / ArrowDown / 49 / 49
Left: ArrowLeft / ArrowLeft / 37 / 37
Right: ArrowRight / ArrowRight / 39 / 39
Ok: Enter / - / 13 / 13

On the media buttons:

Play: MediaPlay / - / 179 / 179
Pause: MediaPause / MediaPause / 179 / 179
Play/Pause: MediaPlayPause / MediaPlayPause / 179 / 179
Fast Forward: MediaFastForward / MediaFastForward / 228 / 228
Rewind: MediaRewind / MediaRewind / 227 / 227

The order is always …
e.key / e.code / e.which / e.keyCode

For the OK and Play button, the e.code field stayed empty. And on my IR remote there is dedicated button for Play and Pause. But in my remote app there is a combined Play/Pause button. But all of them show the same 179 keycode value.

But that are just the keycodes I can provide with my setup. Some Smart TVs running Android TV might have additional media buttons. Some Android TV boxes totally lack media buttons on their remotes. 

But I think long pressing the directional D-pad buttons could be used to trigger some actions / shortcuts. And this should work on every device.

**Comment by KingNothing81** [comment]
I noticed that using the D-Pad of my controller, it will show the same codes on that site than when using the D-Pad on my remote. So I don't know if this is heading towards conflicts with the gamepad if we try using the remote's D-Pad for shortcuts.

And I know it's probably impossible to make all things work with the controller and/or the remote. Because of limitations with Kiwi browser. Because it's a mobile app not intended to be used on Android TV.

Personally my top wish would be to have a controller (or remote) shortcut to show/hide the "three dot menu". Because as mentioned already here ...

https://github.com/redphx/better-xcloud/issues/159

... when the menu is open, you can already use the controller (or the remote) to navigate and select items. So you can already use it to toggle the stream stats, enter/exit fullscreen mode, un(mute) the microphone or exit a game. Only using the exit button to refresh the stream won't work, Because you can't use the controller (or remote) to select "OK" or "Cancel" in the on screen dialog to confirm the stream refresh. So I still have to enable my mouse app to get past that. But maybe you would be able find a solution for that.

But even when not, the "three dot menu" is still very useful. So in my opinion having easy access to the menu would already improve the usage on Android TV a lot.

**Comment by KingNothing81** [comment]
@redphx: Of course you are the boss and set your own priorities, but I hope you will also find some time again to work on bringing back the controller shortcuts. As I really miss being able to toggle the screen stats with my controller. 

And maybe interesting for other Android TV users, this is what I did to make using "Better xCloud" on Android TV more comfortable:

- I've created a shortcut for my home screen that will directly open "xbox.com/play" in Kiwi Browser. This is also useful as sideloaded apps like Kiwi Browser won't show up on the Android TV launcher by default.

https://github.com/redphx/better-xcloud/discussions/234

- I've found and installed a "fullscreen" chrome extension that also works with Kiwi on Android. This will add a "Fullscreen" entry to Kiwi's app menu, so you can toggle fullscreen mode from there. If your remote has a dedicated menu button, you can open Kiwi's app menu with it and then use your remote's d-pad to select it.

https://chromewebstore.google.com/detail/fullscreen/lbpgkagpackldbkfookmmdpfaolnoged

- Or if your remote doesn't have a menu button, you can do it like me and install the "Button Mapper" app and trigger the "menu" action by long pressing one of your controller buttons. Personally I use long press "Start" to open Kiwi's app menu.

https://play.google.com/store/apps/details?id=flar2.homebutton

So maybe other Android TV users will find this useful.

**Comment by KingNothing81** [comment]
Reading my previous posts, it seems that all my suggested improvements from here have been implemented now. Especially the return of the controller shortcuts will make using "Better xCloud" on Android TV much more comfortable.

So a big thank you and I will close this now.
