### ISSUE TITLE
[Bug] Remote play not working

### ISSUE THREAD

**Issue by RoligKanin** [redphx/better-xcloud#176]
**Platform**
 - Device: Desktop
 - OS: Windows 11
 - Browser: Edge 
 - Browser Version: 119.0.2151.93
 - Better xCloud Version: 2.0.2 (had same issue with 2.0.1)

When I try to remoteplay i get the rocketship, it flies off and i get the error under.
Remote play works just fine with the official app (connecting to a Series S).

Tried both connecting via the same network and from 5g.

Without having any inside knowledge of how any of this works,  it seemed like the other bug reported for 2.0.1 that was fixed for some people :)

And I just wanna say great work. Tried this out just recently and the cloud-gaming part is just amazing.
...

**Screenshots/Videos**
![image](https://github.com/redphx/better-xcloud/assets/152406481/5085df99-8cbf-4a1c-9e4f-3064c7a18ab3)

**Comment by redphx** [comment]
I also have this problem in Firefox but not Chrome on MacOS.  
I'll check it this weekend.

**Comment by RoligKanin** [comment]
Tried running it in Chrome (Version 119.0.6045.200 (Official Build) (64-bit)).

Rocketship flies off, XBOX-splash and then the error.

**Comment by redphx** [comment]
Do you have the "Prefer IPv6 server" setting enabled? If you do please disable it and try again.

**Comment by RoligKanin** [comment]
Get the same error both with "Perfer iPv6 server" enabled and disabled. Also tried both resolution options.

**Comment by Trashinated1** [comment]
Go to network settings on your Xbox and check your NAT type.

**Comment by evanpaul14** [comment]
> Go to network settings on your Xbox and check your NAT type.

I second this. I had the same problem where only the official app would work when I had a strict NAT.

**Comment by RoligKanin** [comment]
Dont have time to test too much at the moment, but I checked and the NAT tyoe is OPEN.

**Comment by redphx** [comment]
Try to forward port 9002 too

**Comment by RoligKanin** [comment]
Already fowarded port 9002 to get XBplay to work. Another odd thing is, GPU ran out yesterday and I didn`t renew because I really dont have much time to play in the next weeks. When I tried to remoteplay again with Better Xcloud I was put in a 180 minute long queue, to remoteplay. As if I`m trying to start a cloudsession with Fortnite without GPU....

But, if I`m the only one experiencing this issue you can close the bug-report. The cloud-gaming part works like a charm, and that`s the most important thing for me :)

**Comment by redphx** [comment]
@RoligKanin the bug with Fornite was fixed in the latest version

**Comment by RoligKanin** [comment]
I have 2.0.3 installed and i get:
![image](https://github.com/redphx/better-xcloud/assets/152406481/5447de3f-f503-4a13-b421-70974acfed7d)

![image](https://github.com/redphx/better-xcloud/assets/152406481/004d5db4-caf2-429b-a957-dce69ab464db)

**Comment by redphx** [comment]
Then try this one: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by RoligKanin** [comment]
Tried the link and still stuck in a 245 min queue.

![image](https://github.com/redphx/better-xcloud/assets/152406481/32480558-720f-49cb-a402-e53acc23debc)

**Comment by redphx** [comment]
> Tried the link and still stuck in a 245 min queue.

It shouldn't be like that. People in this issue #171 confirmed it was fixed.

**Comment by RoligKanin** [comment]
Maybe it`s just something goofing it up on my end. I`m no tech wizard, so not unlikely :D

Unless anyone else is having the issue i suggest you close this thread :)

**Comment by IslamWahid** [comment]
I'm also having a problem, I'm getting the rocket screen, xbox logo and then black screen util goes back to the xbox/play page. I have the 9002 port forwarded and I can start remote play sessions from iPhone xbox app and from https://github.com/unknownskl/greenlight 

OS: Mac OS Sonoma 14.2
Browser: chromium based (arc browser)

**Comment by BS-JI** [comment]
Same here. I can see the Rocket and Xbox logo then the screen goes black. 
It took around 30s to back to the main page with an error message.
Interrest thing is when I tried to connect with other app like XBPLAY for XBOX official app after this happen, 
the other app also shows black screen with sound.
In this case the only solution was reboot the console.

OS - Android
Browser - Kiwi browser, Firefox, Yandex browser
NAT is open, 9002 port is forwarded also.

**Comment by redphx** [comment]
@RoligKanin @IslamWahid @Trashinated1 @BS-JI @evanpaul14 

Please test this version: https://github.com/redphx/better-xcloud/raw/feature/fix_remote_play/better-xcloud.user.js

It works for me after port-forwarding port 9002

**Comment by redphx** [comment]
Fixed in 2.1.2

**Comment by IslamWahid** [comment]
it works with 2.1.2 confirmed! thanks @redphx

**Comment by BS-JI** [comment]
Working w/ 2.1.2 confirmed! Thanks @redphx

edited: 
When I tried second time, I found an issue when close connection
1. updated w/ 2.1.2 → connected and everything looks okay → close connection w/ **better xcloud menu (red button)**
2. re-connect → **black screen w/ error**
3. reboot the console with the official app
4. better xcloud 1080p connection → connected → close connection w/ **Xbox home menu** 
6. reconnect w/ 1080p / 720p → connected

Anyway, thank you for the update.

**Comment by redphx** [comment]
@BS-JI this happens from time to time with the official app too, so there is nothing I can do unless Xbox fixes the bug themself.
