### ISSUE TITLE
[Feature] fps change

### ISSUE THREAD

**Issue by J0S387** [redphx/better-xcloud#178]
Ola, seria possivel cria uma função para fixar o fps?, por exemplo o  Valheim inicia sempre a 30 fps, mais se fechar e abrir algumas vezes ele abre a 60 fps, isso pode ta relacionado a internet. Mais teria como fixar a 60 fps?

**Comment by DVergil** [comment]
Infelizmente isso é decidido pelo servidor.
A única solução que eu recomendo e atualizar a pagina do xcloud ou abrir o botão xbox.

**Comment by J0S387** [comment]
resposta rapida kkk, atualizar a pagina não muda o fps pra min so fuciona se eu literalmente fechar o jogo, Obrigado.

**Comment by DVergil** [comment]
Bom, cmg 90% das vezes isso funciona 
Mas em alguns jogos como Jedi Fallen Order isso somente se corrige caso eu feche a sessão e abra uma nova.

**Comment by J0S387** [comment]
😆😆
