### ISSUE TITLE
[Feature] Custom layout touch controller for remote play

### ISSUE THREAD

**Issue by Tak-attack** [redphx/better-xcloud#179]
**I'm using:**  
- Device:Black Shark 4
- OS:Android 12
- Browser:Kiwi
  
The remote play feature works well in my environment.
I find it convenient to play 360 games from my mobile device.

I have one request, can you support the ability to use your own custom layout touch controller for remote play like the cloud gaming version of the game?

If a game is removed from the Xbox Game Pass lineup, custom controls for that game are usually not available, so it would be useful to be able to use them.
If this is technically possible, please consider it.

**Comment by redphx** [comment]
There are several reasons why it can't be done:  
- Once the game is removed from xCloud, its touch layout will also be removed. So there is no way to bring it back.
- The script won't be able to know which game you're playing.
- There are different layouts depend on the current context of the game, so it's not possible to handle this.

**Comment by redphx** [comment]
@Tak-attack Update: there is a chance that this is possible, but I'll look at it later when I have time

**Comment by redphx** [comment]
@Tak-attack also you should try this version: https://github.com/redphx/better-xcloud/issues/98#issuecomment-1866075541  
It contains some fixes for the touch controller not showing when using Remote Play (you don't have to activate the M&KB feature).

**Comment by Tak-attack** [comment]
I tried a test version from Android.
If the game is supported, it will be displayed on a dedicated virtual pad for remote play.
Games with special features (menu screen switching, direct touch & drag, gyro) like Minecraft Dungeons and Grounded worked just like Xbox Cloud Gaming. seeing these features working on the Xbox console and TV is odd🤣.
![IMG_2478](https://github.com/redphx/better-xcloud/assets/149154024/9347264d-5b3c-4d8a-b7d7-7da9f935c7b6)

https://github.com/redphx/better-xcloud/assets/149154024/f4083278-36e9-4c6a-a377-a77bc1fb47e9


https://github.com/redphx/better-xcloud/assets/149154024/cb77d8cc-1a42-4ff9-b197-36b8369fe99f

**Comment by redphx** [comment]
That's amazing. I didn't expect for it to work right now :D Thanks for the info.

**Comment by Tak-attack** [comment]
I closed it first, but it seems that these features are still working correctly in version 3.0.Thank you for your support.
