### ISSUE TITLE
[Feature] Put the Stream status bar in transparent

### ISSUE THREAD

**Issue by ricardo404** [redphx/better-xcloud#18]
Redphx, it would be interesting, to finalize this feature, that the bar became transparent and the information such as “FPS”, “RTT”…, in a color, like red or another color that would be interesting. I think it would make the feature excellent.

**Comment by ricardo404** [comment]
Option also to center, or place on the left or right side of the screen. Thank you.

**Comment by redphx** [comment]
Would be great if you provide a mockup. Thanks.

**Comment by ricardo404** [comment]
![Central](https://github.com/redphx/better-xcloud/assets/35298519/2dad5425-bfef-4e52-9687-0b3ff5bbaf28)

![Left](https://github.com/redphx/better-xcloud/assets/35298519/5ff1307d-f788-4a14-b733-9758f6a05937)

I think the options would be like this, Red. With the option to remove the black background, to make it transparent, leaving only the streaming data.

With options to choose, whether you want it on the left, center, and right, at the top of the screen. Something similar to the option to take a screenshot.

**Comment by ricardo404** [comment]
The font size of the words that you initially made is ideal and can remain.

**Comment by redphx** [comment]
I got the idea. Let me see.

**Comment by redphx** [comment]
You can start testing this feature with this version: https://github.com/redphx/better-xcloud/raw/feature/update-steam-stats/better-xcloud.user.js  

Show the stats, then double-click on it to show the Settings dialog.  

<img width="382" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/d598f30b-ab54-4439-8f5c-3e2fac4975b9">

**Comment by ricardo404** [comment]
![image](https://github.com/redphx/better-xcloud/assets/35298519/437e0992-9801-40c2-8bed-0c24280a0964)

Wow, it was excellent. You are incredible @redphx.

**Comment by ricardo404** [comment]
Red, could you put an "always on" option for this function in that Extension's tweak menu on the main page? How useful this information is, and believe me, I don't get paranoid. I think this information is important and I always like to see it. Thanks.

(I ended up discovering a lot of things with this feature, among others, who is to blame for the crashes throughout the game. I'm glad it's not my network. Lol.)

**Comment by redphx** [comment]
@ricardo404 reinstall the dev version and check the settings dialog again

**Comment by ricardo404** [comment]
> @ricardo404 reinstall the dev version and check the settings dialog again

![image](https://github.com/redphx/better-xcloud/assets/35298519/98f65384-5e25-4eac-95f8-329a538a30ac)

Hi Red. Feature tested and working properly and can be released to everyone. Thanks for this important feature and thanks for adding my request to your script.

**Comment by redphx** [comment]
I still have a few more features to add

**Comment by ricardo404** [comment]
Hey @redphx , can you give me a spoiler of what's coming?

**Comment by redphx** [comment]
Just check the [Commit logs](https://github.com/redphx/better-xcloud/commits/feature/update-steam-stats) from time to time

**Comment by redphx** [comment]
<img width="678" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/0a4af438-c01b-466c-a7a4-990656c52d1b">  
  
Added:  
- Text size  
- Decode time (DT) stat  
- Conditional formatting for RTT & DT (white = great, green = good, yellow = ok, red = bad)

**Comment by ricardo404** [comment]
> <img alt="image" width="678" src="https://user-images.githubusercontent.com/96280/256248053-0a4af438-c01b-466c-a7a4-990656c52d1b.png">
> Added:
> 
> * Text size
> * Decode time (DT) stat
> * Conditional formatting for RTT & DT (white = great, green = good, yellow = ok, red = bad)

Red, could you explain more in detail this ‘Decoded Time’, I didn’t understand what it monitors!

**Comment by redphx** [comment]
It's the average time it took to decode 1 frame in the last second. What is your value?

**Comment by ricardo404** [comment]
> It's the average time it took to decode 1 frame in the last second. What is your value?

It is between 1.27 and 1.44. But if I start moving the window, opening other things in the tab, or doing anything other than in-game, it starts going up to 5ms or more. If you go back to the game and don't change anything, it goes back to the values I quoted initially.

**Comment by redphx** [comment]
That's a really good value I think. Thanks for the answer.
