### ISSUE TITLE
[Bug] Remote play showing black screen when not connected to local network

### ISSUE THREAD

**Issue by evanpaul14** [redphx/better-xcloud#180]
**Platform**
 - Device: iPhone XS Max
 - OS: iOS 17
 - Browser:  Safari
 - Browser Version: 17
 - Better xCloud Version: 2.0.3

**Describe the bug**

When I’m on a cellular connection after the rocket loading screen ends it just shows a black screen.

I don’t know if this is a bug or if it’s even possible.
I think [this thread](https://github.com/unknownskl/greenlight/issues/593) might be relevant.

**Comment by redphx** [comment]
What is your NAT status? My NAT is `Moderate` and I have the same issue when trying to connect from outside.

**Comment by evanpaul14** [comment]
My NAT is open

**Comment by redphx** [comment]
Try to port forward port 9002

**Comment by Trashinated1** [comment]
It depends on your network. Go to your router settings (Mine's AT&T) and enable DMZplus mode like I did here.
![Annotation 2023-12-03 104305](https://github.com/redphx/better-xcloud/assets/104871230/2028dcf5-e902-4142-a984-7ef3066b478d)

**Comment by redphx** [comment]
@evanpaul14 how did you fix it?

**Comment by evanpaul14** [comment]
I didn’t. The official app also stopped working outside  my local network so I’m assuming it’s an issue with my setup.
