### ISSUE TITLE
[Bug] Large amount of dropped frames

### ISSUE THREAD

**Issue by ghost** [redphx/better-xcloud#182]
**Platform**
 - Device: TV
 - OS: Android 11
 - Browser: Kiwi
 - Browser Version: 120.0.6099.26
 - Better xCloud Version: 2.0.3

**Describe the bug**
With the Tampermonkey script enabled I am noticing a large amount of frame drops. Viewing the stream stats shows around 30% of frames are dropped. Bitrate, ping, packets are well within usual range that I see when using the script on my laptop.

I have lowered the resolution to 720p and quality to low in Better xCloud settings, tried various different combinations of user agent and settings etc too. Also reinstalled browser, tampermonkey and the script. Issue still persists.

Please note that when Better xCloud is disabled I am able to play with no issues whatsoever, other than the low video resolution on the stock Game Pass site.

**Comment by KingNothing81** [comment]
When using "Better xCloud", do you have "Clarity" enabled in the video settings? If that's the case, have you tried disabling it (set Clarity to 0) to see if it makes a difference?

**Comment by ghost** [comment]
> When using "Better xCloud", do you have "Clarity" enabled in the video settings? If that's the case, have you tried disabling it (set Clarity to 0) to see if it makes a difference?

Clarity is set to 0. Out of interest, what does the Clarity setting actually enable on the stream?

I have managed to mitigate the performance issue slightly by using ADB to uninstall a load of bloatware apps and services. Its a pretty mid TCL TV anyway so isnt the fastest. I may roll back to an Android 9 firmware as I recently flashed 11. It's not too big a deal at this point as its my bedroom TV but I find it hard to stop trying to resolve "issues" 😂

**Comment by KingNothing81** [comment]
> Clarity is set to 0. Out of interest, what does the Clarity setting actually enable on the stream?

It's simliar to "Clarity Boost" that's only available on Edge Browser on Windows. Foremost it adds sharpness to the image, making it more "clear". But as it's a video filter applied on local hardware, it affects performance and can make weak devices struggle. So using xCloud on a TV, I would always prefer adjusting the picture settings of my TV to further improve image quality.

**Comment by ghost** [comment]
> > Clarity is set to 0. Out of interest, what does the Clarity setting actually enable on the stream?
> 
> It's simliar to "Clarity Boost" that's only available on Edge Browser on Windows. Foremost it adds sharpness to the image, making it more "clear". But as it's a video filter applied on local hardware, it affects performance and can make weak devices struggle. So using xCloud on a TV, I would always prefer adjusting the picture settings of my TV to further improve image quality.

Yeah I've been playing about with my TV today and think I've managed to work out how to get the best possible visual quality while minimising latency and frame drops. 

Downgrading Kiwi to a random 116.x.x.x build from the newest 120.x.x.x build helped massively but interestingly swapping  gamepad from a DS4 to a Stadia controller (both connecting to TV with bluetooth) has had the most noticeable impact on Decode Time and Frame Loss. Spent half an hour or so looking into it and apparently Android 11 (Phone builds and TV) has always had issues communicating with DS4s properly.

**Comment by redphx** [comment]
This is most likely your TV isn't powerful enough.
