### ISSUE TITLE
[Bug] Input delay

### ISSUE THREAD

**Issue by ghost** [redphx/better-xcloud#183]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 120.0.2210.61
 - Better xCloud Version: 2.0.5

**Describe the bug**
I've been using Better xCloud to strech my resolution, but after 2.0 I've got some input delay when playing.
I tried re-installing, clearing cache, deactivating every setting, go back to older versions, but nothing seems to work. Even reloading the page doesn't fix it.

**Comment by redphx** [comment]
Does it still happen when you disable Better xCloud?

**Comment by ghost** [comment]
No.

**Comment by ghost** [comment]
Nevermind, it was a ping issue, I marked the "Prefer IPv6 server" setting.

Sorry to bother you.
