### ISSUE TITLE
[Feature] Live translation

### ISSUE THREAD

**Issue by Chuoi97** [redphx/better-xcloud#185]
**I'm using:**  
- Device: Android 
- OS:
- Browser:mises
  
**I want to suggest this feature:**  
...
Added the feature to translate all sub languages ​​displayed in the game so players can clearly understand the plot 🥰😍

**Comment by subby2006** [comment]
Not possible. xCloud simply streams a video feed of the game from Microsoft servers to you, so game translations would largely have to be done by the developers themselves
