### ISSUE TITLE
[Feature] ...Add keyboard and mouse support for smartphones 

### ISSUE THREAD

**Issue by Chuoi97** [redphx/better-xcloud#187]
**I'm using:**  
- Device:Android 
- OS:
- Browser:Kiwi
  
**I want to suggest this feature:**  
...You can add a keyboard and mouse for smartphones and ipad

**Comment by redphx** [comment]
Duplicate #98

**Comment by Pixelgoku2** [comment]
https://github.com/redphx/better-xcloud/issues/187#issue-2045874723
