### ISSUE TITLE
tried to use better xcloud on android phone now xcloud doesnt work at all on any browser or even gamepass app

### ISSUE THREAD

**Issue by ramonQAQ** [redphx/better-xcloud#189]
**Platform**
 - Device: phone
 - OS: android 12
 - Browser: all
 - Browser Version:all
 - Better xCloud Version:latest

**Describe the bug**
after i tried using better xcloud and now xcloud service doesnt work on any browser i tried uninstalling kiwi but still 

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.
![Screenshot_20231225-131329](https://github.com/redphx/better-xcloud/assets/96535082/e0f2adff-14be-4d0a-8dc3-0f12a3c18d84)
![Screenshot_20231225-124952](https://github.com/redphx/better-xcloud/assets/96535082/dfbca5c9-61a7-4e16-9cdb-394d506836de)

**Comment by redphx** [comment]
If it doesn't work in GP app then it's xCloud's bug.
