### ISSUE TITLE
[Bug] Black screen when playing

### ISSUE THREAD

**Issue by Pelezin0** [redphx/better-xcloud#19]
**Describe the bug**
When starting the game the screen goes black, you can only hear the sound of the game. I use Kiwi Browser on android.

**Platform (please complete the following information):**
 - OS: Android
 - Browser: Kiwi Browser
 - Browser Version: 116.0
- Better xCloud Version: I tested the last one and version, and another older one

**Comment by redphx** [comment]
Which phone are you using?

**Comment by Pelezin0** [comment]
> Qual telefone você está usando?

Redmi 9C 64gb, Android 10, 32 bits

**Comment by redphx** [comment]
Please disable the "Force high quality codec" setting and try again.

**Comment by Pelezin0** [comment]
> Desative a configuração "Forçar codec de alta qualidade" e tente novamente.


https://github.com/redphx/better-xcloud/assets/139387859/f984c540-a377-4fb7-a9a8-c697619260aa

I can't access the extension's settings.

**Comment by redphx** [comment]
You installed it incorrectly. Please remove it and follow [this instruction](https://github.com/redphx/better-xcloud#how-to-use) to install Tampermonkey & Better xCloud.

**Comment by Pelezin0** [comment]
> Você o instalou incorretamente. Remova-o e siga [estas instruções](https://github.com/redphx/better-xcloud#how-to-use) para instalar o Tampermonkey & Better xCloud.

I installed both now, I followed the instructions, but the "new server" as mentioned does not appear.

![Screenshot_2023-07-24-12-39-52-981_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/139387859/6a4ef342-a57a-4639-be1c-bc8432b06749)
![Screenshot_2023-07-24-12-40-01-376_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/139387859/9b66184a-b9a3-4752-b82f-6157ab28b02a)
![Screenshot_2023-07-24-12-39-58-204_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/139387859/0a77cc8d-e2b6-4c15-b88c-281c851fb2b3)

**Comment by Pelezin0** [comment]
Here at Tampermonkey it's like this

![Screenshot_2023-07-24-12-43-04-284_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/139387859/cae32311-77a7-4243-97b5-49796a15fb1e)
![Screenshot_2023-07-24-12-43-13-606_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/139387859/bdfb8b28-5a9d-49e7-b79c-4f2186981ba8)

**Comment by redphx** [comment]
Your website didn't have a profile picture on the right like this:  

<img width="469" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/01d965c0-42d3-44c7-b4b1-fbf70a9232d0">  

Please try to disable all other xcloud scripts (Anti-AFK...) and try again.  

Also remove the old "Better xCloud" script in the extensions page.  

<img width="709" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/8d3e417d-4f5d-4449-8ec6-4efdef946a1c">

**Comment by Pelezin0** [comment]
> Seu site não tinha uma foto de perfil à direita como esta:
> 
> <img alt="imagem" width="469" src="https://user-images.githubusercontent.com/96280/255751345-01d965c0-42d3-44c7-b4b1-fbf70a9232d0.png">
> Tente desativar todos os outros scripts xcloud (Anti-AFK...) e tente novamente.
> 
> Remova também o antigo script "Better xCloud" na página de extensões.
> 
> <img alt="imagem" width="709" src="https://user-images.githubusercontent.com/96280/255754437-8d3e417d-4f5d-4449-8ec6-4efdef946a1c.png">

Show me where the "new server" is.
![Screenshot_2023-07-25-11-24-12-949_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/139387859/7adaae87-0e69-450a-b35d-a02adfe9702c)

**Comment by abdoria** [comment]
I'm having this exact issue playing on PC (using Edge). Unchecking "Force high quality codec" indeed solves it.
Any thoughts on how to get it to work with this option enabled?

**Comment by redphx** [comment]
> I'm having this exact issue playing on PC (using Edge). Unchecking "Force high quality codec" indeed solves it. Any thoughts on how to get it to work with this option enabled?

1. Open [DevTools](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview) in Edge.
2. Enter this code in the Console tab: `RTCRtpReceiver.getCapabilities('video').codecs`
3. Take a screenshot of the results.  

You'll see something like this:  

<img width="1007" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/bb1aeef6-948e-4dca-94d8-95e017c206b9">

**Comment by PnSajdak** [comment]
> > Seu site não tinha uma foto de perfil à direita como esta:
> > <img alt="imagem" width="469" src="https://user-images.githubusercontent.com/96280/255751345-01d965c0-42d3-44c7-b4b1-fbf70a9232d0.png">
> > Tente desativar todos os outros scripts xcloud (Anti-AFK...) e tente novamente.
> > Remova também o antigo script "Better xCloud" na página de extensões.
> > <img alt="imagem" width="709" src="https://user-images.githubusercontent.com/96280/255754437-8d3e417d-4f5d-4449-8ec6-4efdef946a1c.png">
> 
> Show me where the "new server" is. ![Screenshot_2023-07-25-11-24-12-949_com kiwibrowser browser](https://user-images.githubusercontent.com/139387859/255931735-7adaae87-0e69-450a-b35d-a02adfe9702c.jpg)

Eu estava tendo o mesmo problema e a solução para mim foi baixar o better xcloud pelo tampermonkey diretamente.
I was having the same issue and for me the solution was downloading better xcloud directly by tampermonkey.
