### ISSUE TITLE
[Bug] Clarity Boost applies scaling to games when playing on a 4k screen

### ISSUE THREAD

**Issue by ghost** [redphx/better-xcloud#191]
**Platform**
 - Device: Laptop with external display
 - OS: Windows 11
 - Browser: Edge
 - Browser Version: Latest build
 - Better xCloud Version: Latest build

When turning Clarity Boost on, the the game window is scaled back down. This is intermittent. sometimes it worse, sometimes it doesnt. This only happens when Better xcloud is enabled. Works fine with native Edge xCloud

**Clarity Boost on**
![image](https://github.com/redphx/better-xcloud/assets/153085225/214e0e41-6343-4222-840e-e4042a30cc04)

**Clarity Boost off**
![image](https://github.com/redphx/better-xcloud/assets/153085225/a5703769-6b39-4412-99a9-870fd302adf5)

**Comment by redphx** [comment]
Did you change brightness/contrast/saturation before enabling CB? Try to set them back to 100%

**Comment by ghost** [comment]
> Did you change brightness/contrast/saturation before enabling CB? Try to set them back to 100%

Sorted it, its the first time I've played on this device for a while and wondered why Clarity Boost wasn't enabled, I've been and checked and the Better xCloud Clairty was set to 1. Turned it off and Clarity Boost works as normal. I've tested by redoing/undoing etc a few times and its definitely that that was causing it.

Thanks for the quick reply, hope you had a good christmas.

**Comment by redphx** [comment]
Happy holiday!
