### ISSUE TITLE
[Bug] Battery drain?

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#192]
**Platform**
 - Device: Logitech G Cloud / Lenovo Y700
 - OS: Android
 - Browser: Kiwi
 - Browser Version: 120
 - Better xCloud Version: 2.1.2

**Describe the bug**  

It's used to be 5% battery life for 30' playing, but now it's over 10% for 30'.  

Not sure what caused this change: Better xCloud, Kiwi, Tampermonkey or xCloud?  

Please report your battery usage if you're playing on Android/iOS/iPadOS.  

Thanks.

**Comment by DrSay123** [comment]
Also confirim this issue. Its not associated with kiwi browser itself, since Firefox also has this problem. So I assume its problem of xCloud or better xCloud. Almost 
![Screenshot_20240209_230325](https://github.com/redphx/better-xcloud/assets/87112480/f906be67-50f5-40c1-905d-b17e8cf8285a)
![Screenshot_20240209_230328](https://github.com/redphx/better-xcloud/assets/87112480/db382207-a9f2-4410-9589-90559b8554fd)

**Comment by redphx** [comment]
@DrSay123 what is the refresh rate of your screen?

**Comment by DrSay123** [comment]
@redphx 144hz, but I set 60 for kiwi browser

**Comment by redphx** [comment]
@DrSay123 are you sure it's 60Hz when using Kiwi? You can very this by enable the "Show refresh rate" in phone's Developer mode.

And do you play with touch control or controller?

**Comment by DrSay123** [comment]
@redphx ,yep,im 100% sure its 60hz
Im playing with Bluetooth controller, with touch  battery usage is even higher

**Comment by redphx** [comment]
@DrSay123 yes, using touch control drains battery faster because it has to redraw the control every frames.  

Do you use the Clarity feature? If yes, which value is it?

**Comment by DrSay123** [comment]
@redphx No, im never used it
But even without clarity boost kiwi still somehow maxes out adreno 650 gpu.

**Comment by redphx** [comment]
Yeah, it's difficult to track down the culprit. It could be anything. I check Better xCloud's code multiple times to make sure that it was not my fault.  

Edge on Android will be supporting extension soon. Hopefully it won't have the same problem as Kiwi.
