### ISSUE TITLE
[Bug] Remote play  with Internet is not working

### ISSUE THREAD

**Issue by KaristoCR** [redphx/better-xcloud#196]
**Platform**
 - Device: Phone, 
 - OS: Android, 
 - Browser: kiwi
 - Browser Version:
 - Better xCloud Version: 2.1.2

**Describe the bug**
...
Last version, is not possible to use remote play 
Early version work very well, but this not..
**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Does it work in the Xbox app?

**Comment by KaristoCR** [comment]
Hi, yes in the Xbox app, work ok.

**Comment by KaristoCR** [comment]
Is something wrong, I try to open another port, but is not working, I degrade the version, but nothing, In the xbox app, work without problems.

**Comment by redphx** [comment]
Does your network use IPv6?

**Comment by KaristoCR** [comment]
Hello, I have IP v6 enabled but the Xbox does not grab IP v6, only v4, the
strange thing is that before it works fine without problems from the
outside. Even the official app connects well. My Nat is open, internally
the better xcloud works very well, but from the outside it no longer
connects and the message appears saying to try again later.

**Comment by redphx** [comment]
@KaristoCR please try this version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by RKoldborg** [comment]
It seems this problem is still present. I cannot connect via the remote play feature from outside my network, but it works perfectly through the Xbox app.
