### ISSUE TITLE
[Bug] Mouse having to move to the edges of the screen when you need to rotate the camera

### ISSUE THREAD

**Issue by L4nzinhu** [redphx/better-xcloud#197]
**Platform**
 - Device: Laptop
 - OS: Windows
 - Browser: Chrome
 - Browser Version:119
 - Better xCloud Version: 2.1.2

Bug descrition:
It is only possible to rotate the camera a little, it is limited to the edges of the screen, this becomes even more problematic when taking the camera to look at the ground.

Solution idea: lock the mouse in the center of the screen and make it invisible, but in a way that whenever we rotate the mouse it will not leave the center but the camera will be rotated.

VIDEO:

https://github.com/redphx/better-xcloud/assets/155100711/81d4229c-16ac-43f5-8032-1f3a3e89ad8a

**Comment by redphx** [comment]
Report it in #98
