### ISSUE TITLE
[Feature Request] Hide Cursor

### ISSUE THREAD

**Issue by LifeDreamer24** [redphx/better-xcloud#2]
Would be nice if you could implement the feature like in the official Xbox desktop app where the mouse pointer hides itself after a certain amount in seconds of using the controller.

- [ ] Implement the feature by default.
- [x] Add a checkbox so users can decide whether they want it or not by toggling it in the menu.

**Comment by redphx** [comment]
That's a nice idea. Thanks for the suggestion.  
I think I'll pick 4 seconds.

**Comment by LifeDreamer24** [comment]
> That's a nice idea. Thanks for the suggestion.  
> 
> I think I'll pick 4 seconds.

Awesome! Glad you took that in consideration as otherwise i had to move my mouse in the corner of my screen each time i start a game lol

Thanks again for making this extension, really helpful and the ipv6 fixed most of my issues with the input delay!

**Comment by redphx** [comment]
Bad news, I think the IPv6 feature is not working properly 😆 I'll fix it soon.  
Thanks for using.

**Comment by LifeDreamer24** [comment]
Oh nose! Let me know when you do XD

**Comment by redphx** [comment]
> Oh nose! Let me know when you do XD

I fixed the IPv6 feature in the [Dev version](https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js). Please try.

**Comment by LifeDreamer24** [comment]
Idk how to see if it's actually using IPv6 although there seems to be almost no delay on my side..
Thanks!

**Comment by redphx** [comment]
> Idk how to see if it's actually using IPv6 although there seems to be almost no delay on my side.. Thanks!

If you're using Firefox, you could check it in `about:webrtc`.  
For Chrome it's `chrome://webrtc-internals`.  
Btw, future comments about this feature please move to #3.

**Comment by redphx** [comment]
@LifeDreamer24 do you want to hide cursor only when playing in fullscreen mode?

**Comment by LifeDreamer24** [comment]
I mean I always use fullscreen because of the user agent so I honestly don't mind haha
I would personally do an option to toggle this too such as adding a "Toggle Cursor" section and adding both "While Fullscreen" and "While Windowed" as toggle options. If you don't plan doin any of this or and/or wish skipping time, hide it completely even in windowed as it could confuse people if you know what I mean...

**Comment by LifeDreamer24** [comment]
The thing is that if they always play windowed and then they try to toggle the "Hide Cursor" feature while this one only affects fullscreen, they'll think it's useless XD

**Comment by redphx** [comment]
@LifeDreamer24 you can test this feature in the Dev version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js  
Enable it in the Settings first. The cursor will hide after 3s.

**Comment by LifeDreamer24** [comment]
Thank you! It works flawlessly.
