### ISSUE TITLE
[Bug] Can't access the xCloud menu within the game

### ISSUE THREAD

**Issue by DVergil** [redphx/better-xcloud#20]
**Describe the bug**
When I activate fullscreen mode, I can't access the Xcloud menu within the game 

**Platform (please complete the following information):**
 - OS: [e.g. Android]
 - Browser: [Kiwi Browser]
 - Browser Version: [116.0.0.0]
- Better xCloud Version: [1.6]

**Comment by redphx** [comment]
Please add a screenshot or a screen recording. I still don't know what the problem is.

**Comment by DVergil** [comment]
Hi, I'm using kiwi browser through sideload on android TV, I can't register

**Comment by DVergil** [comment]
Basically when I'm in fullscreen mode, I can't access the Xcloud menu. In non-full screen mode it opens normally

**Comment by danfozzy** [comment]
If you have hidden the 3 dots as part of the better xcloud settings, you can still press it whilst full screen, use your mouse to point to the top corner and left click, it will appear.
If your mouse won't appear, double click and it will then show up.

If using a touch screen, press in the top left corner

**Comment by redphx** [comment]
Have you tried switching User-Agent profile to Edge?

**Comment by danfozzy** [comment]
Pretty sure this can be closed off
