### ISSUE TITLE
[Feature] Upcoming Mouse & Keyboard features

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#200]
- [ ] Import/Export presets
- [ ] Online presets library
- [ ] Automatically load different presets for different games
- [ ] Buttons cheatsheet

**Comment by Panzer123** [comment]
Hello. Just installed the script. But have a hard time figuring out where to enable keyboard and mouse settings :)

**Comment by Panzer123** [comment]
These doesn't exists in my settings. I am using windows 11 & chrome. 
![issue](https://github.com/redphx/better-xcloud/assets/155651520/fb06aae3-521c-48a4-93bc-2a9d6220e484)
This is what i see.
unless there is something i misunderstanding and there are a second settings i simply can't find it

**Comment by redphx** [comment]
That's an old screenshot that I forgot to update. Please create a new issue for this.

**Comment by Usuario6837** [comment]
Can native keyboard and mouse be reactivated again?
