### ISSUE TITLE
[Bug] Kiwi browser stopped working with the new update

### ISSUE THREAD

**Issue by Linxz0** [redphx/better-xcloud#201]
**Platform**
 - Device: Phone
 - OS: Windows, Android
 - Browser: Chrome, Kiwi
 - Browser Version:. 120.0.6099.116
 - Better xCloud Version: 3.0 and 2.1.2

**Describe the bug**
Today, when I updated, it didn't work, I no longer enter the website. I tried to go back to the old version but it still persists. But before it worked perfectly, but now it doesn't work at all.

**Screenshots/Videos**
![Screenshot_20240104-112825](https://github.com/redphx/better-xcloud/assets/155654545/3d4a3ab0-7fdf-49b6-ad63-f1bb9f49c587)
(This is in Portuguese, because I'm Brazilian)

**Comment by redphx** [comment]
This is xCloud's bug: https://www.reddit.com/r/xcloud/comments/18yc8rp/an_error_occurred_while_processing_your_request/

**Comment by Linxz0** [comment]
but how can I solve it? I can't even access the website

**Comment by redphx** [comment]
https://twitter.com/xboxsupport/status/1742930610291962183
