### ISSUE TITLE
[Bug] ... xcloud dont work after this update.

### ISSUE THREAD

**Issue by GuhdVibe** [redphx/better-xcloud#202]
Hello! Today i and some players had an issue accessing xCloud (in html pages)...  Despite trying various ways to access, the same error persisted until i disabled the Tampermonkey extension and cleared cookies. (note that only clearing cookies doesn´t work; it's mandatory to disable Tampermonkey. So, by doing that, the issue is resolved to me (but i cant use betterxcloud for now). 
Xbox just posted a little while ago that they're aware some players are having trouble accessing the site. So, idk if it's related to Tampermonkey only; or microsoft dont wanting betterxcloud with kbm; or microsoft own system. For now, i'll keep playing this way and hope that something gets resolved so i can play with betterxcloud. 

i hope this helps. 
and sorry for my english... im learning :)

Edit: XboxSupport just posted that the problem is solved... for me it is. 
betterxcloud working 100%

**Comment by Dege22** [comment]
I'm suffering from the same problem, however I haven't cleaned the cookis, I'll do it now, I've already disabled the tampermonkey extension and re-installed the script, but so far without success,

**Comment by zsaakul** [comment]
New update broke my xcloud on steam deck completely, doesnt work even after disabling tampermonkey and reinstalling Microsoft Edge, any solution would be grateful. thanks

**Comment by redphx** [comment]
https://twitter.com/xboxsupport/status/1742937682492448808
