### ISSUE TITLE
[Bug] "An error occurred while processing your request."

### ISSUE THREAD

**Issue by mgafpd** [redphx/better-xcloud#204]
**Platform**
 - Device: Phone
 - OS: Android
 - Browser: Kiwi
 - Browser Version: 120.0.6099.26
 - Better xCloud Version: 3.0

**Describe the bug**
Hello, dear developer!

 After updating UserScript, I faced this error. Deleting the script doesn't help, the other device has the exact same error. I tried to uninstall the script and install 2.1.2, but after the first reload of the site, the error returns. Everything works in the app itself, but not in all other browsers

I hope you can help with this problem

Thank you =)

**Screenshots/Videos**
![Screenshot_2024-01-04-19-25-42-779_com kiwibrowser browser](https://github.com/redphx/better-xcloud/assets/151776763/031dea8a-46cc-496a-8964-ef86b2c73fc2)

**Comment by redphx** [comment]
https://twitter.com/xboxsupport/status/1742937682492448808
