### ISSUE TITLE
[Bug] Keyboard and Mouse not working on Safari iOS/Chrome Android

### ISSUE THREAD

**Issue by Trashinated1** [redphx/better-xcloud#206]
**Platform**
 - Device: iPad 7
 - OS: iPadOS 16.6
 - Browser: Safari
 - Browser Version: 16.6
 - Better xCloud Version: 3.0.0

When trying to click on the “click to activate” pop up to activate keyboard and mouse controls on my iPad, it doesn’t do anything.

**Screenshots/Videos**
<img width="1080" alt="image" src="https://github.com/redphx/better-xcloud/assets/104871230/3d02b421-9d88-486a-8639-24ac74e9f799">

**Comment by redphx** [comment]
This is another limitation of Safari on iOS and Chrome on Android: it doesn't support [Pointer Lock API](https://caniuse.com/pointerlock), which is required for this feature

<img width="856" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/c087dd0f-963e-4192-82cb-a52f0fe36f22">

**Comment by Trashinated1** [comment]
Is it possible to make a setting that gets around this?

**Comment by redphx** [comment]
I can make this work without the API, but you'll have a much worse experience. Another thing: I don't have an iOS device that runs iOS 15 or later, so I can't test it.

**Comment by Trashinated1** [comment]
I’ll test.

**Comment by Nauj749** [comment]
I need help, I'm Brazilian and when I play with the keyboard and mouse, Fortnite doesn't recognize the clicks, I use the Kiwi browser, which is a Google extension, can you give me a solution?

**Comment by redphx** [comment]
This feature can't be used on mobile

**Comment by Leal779** [comment]
> Preciso de ajuda, sou brasileiro e quando brinco com teclado e mouse o Fortnite não reconhece os cliques, utilizo o navegador Kiwi, que é uma extensão do Google, vocês podem me dar uma solução?

tambem nao consigo

**Comment by redphx** [comment]
This feature won't be supported until Chromium implements the [PointerLock API on Android](https://bugs.chromium.org/p/chromium/issues/detail?id=153419).

**Comment by redphx** [comment]
**May 29:**: [Better xCloud Android app](https://better-xcloud.github.io/android) now supports emulated Mouse & Keyboard.
