### ISSUE TITLE
[Bug] Device vibration is not working

### ISSUE THREAD

**Issue by spikewj** [redphx/better-xcloud#207]
**Platform**
 - Device:  Lenovo Y700 + Gamesir G8(no rumble support)
 - OS: Android
 - Browser: Kiwi
 - Browser Version: 120
 - Better xCloud Version: 2.1.2, 3.0

**Describe the bug**
Device vibration is not working.
Note that I have enabled gamepad vibration on flag in chrome://flags in kiwi browser.
FYI, I used to play remote play with xbplay app, which supports device vibration as expected.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by Tak-attack** [comment]
これは私も同じことになったことがあるのですが、サイレントモードを解除することで動作しました。デバイスはサイレントモードになっていませんか？

**Comment by Tak-attack** [comment]
I have had this happen to me, but it worked by deactivating silent mode.Is the device in silent mode?

**Comment by spikewj** [comment]
> I have had this happen to me, but it worked by deactivating silent mode.Is the device in silent mode?

No, the device is not in silent mode. I'm wondering if device vibration is related to the silent mode of the device?

**Comment by redphx** [comment]
@spikewj  
Is your device vibration setting "On" or "On when not using gamepad"?  

Does it work when not attaching to the G8?  

I also have an Y700 (2022) and it works fine for me.

**Comment by spikewj** [comment]
@redphx 

Yes, my device vibration setting is "on' and it's still not working with "On when not using gamepad"

It doesn't work when not attaching to the G8.

Note that I'm using an Y700 (2023).

**Comment by redphx** [comment]
Does it work on this page in Kiwi? https://googlechrome.github.io/samples/vibration/  

Which game are you playing? Could you try it with Cocoon?

**Comment by spikewj** [comment]
Thank you for your comment.
It doesn't work on the page you mentioned, which means kiwi browser or Y700(2023) is not handling vibration event, right?
Then it's not the issue of better-xcloud, I guess.

Sure, It's not working with Coccon.

**Comment by redphx** [comment]
If so then most likely this is your device's problem. My device is running ZUI 14 so I can't help you further.  
 
I'm gonna close this issue.

**Comment by redphx** [comment]
You should also check that test page on Chrome. It it works then it's Kiwi's problem, otherwise it's the system's.

**Comment by spikewj** [comment]
Thanks for your comment.
Unfortunately it doesn't work on chrome either, so it looks like a system issue as you mentioned.
My y700(2023) is on latest zui 15.

**Comment by spikewj** [comment]
FYI, I found out the workaround for my case. When "Vibrate on touch" is turned on, the vibration works!

Open the "Settings"
Scroll down and tap "Sound & vibration."
Scroll down and tap "Vibration & haptic."
Scroll down and tap "Vibrate on touch."
Turn on the "Vibrate on touch" toggle switch.

**Comment by redphx** [comment]
It shouldn't be like that. It's definitely a system bug.

**Comment by spikewj** [comment]
> It shouldn't be like that. It's definitely a system bug.

Yes, it's a system bug, I hope lenovo fix this in the next firmware.
