### ISSUE TITLE
[Feature] Native Mouse & Keyboard support

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#208]
The native Mouse & Keyboard support feature can be disabled by xCloud anytime so I don't want to enable it by default.  

If you want to try it, follow these steps:

1. Open the script in Tampermonkey editor.

2. Change the `ENABLE_NATIVE_MKB_BETA` flag to `true`.

3. Add the game you want to try to the `window.NATIVE_MKB_TITLES` list, or remove the `//` symbols to un-comment that game.

4. Save the script.

⚠️ There is no guarantee that it will work.

**Comment by redphx** [comment]
@Usuario6837

**Comment by igalarey** [comment]
I thought it was disabled server-side. Is is enabled again?

**Comment by redphx** [comment]
> I thought it was disabled server-side. Is is enabled again?

Yes it was, but it doesn't hurt to try

**Comment by Usuario6837** [comment]
It's sad to see someone who managed to activate the native keyboard for games and then xCloud deactivates this function, in my view Microsoft could just buy the source code, leaving that aside I'll test what you said

**Comment by igalarey** [comment]
I tried some games and it only worked on flight simulator for me.

**Comment by redphx** [comment]
> It's sad to see someone who managed to activate the native keyboard for games and then xCloud deactivates this function, in my view Microsoft could just buy the source code, leaving that aside I'll test what you said

xCloud developed this feature, all I do is enabling it.

**Comment by AngusDLX** [comment]
Enabling it to true doesn't seem to work. At least here, the Xcloud interface doesn't even change to show the keyboard and mouse symbol.

Redphx is this expected? Flight simulator is on the list below in the code but it doesn't work. Is it necessary to remove the \\ //?

I had success using your test version but I formatted my disk and lost it. I went to issue 98 to try to download again but it won't download

**Comment by redphx** [comment]
@AngusDLX you need to remove the `//` to un-comment the line

**Comment by CodeZerou** [comment]
How do I add and test more games? I mean, the game code as there are a few.

**Comment by NasiWaarteG** [comment]
what do you mean by add the game you want to try to the window.NATIVE_MKB_TITLES list? should i write the name of the game or the code of the game? example fortnite?

**Comment by LuizH2409** [comment]
How do I find out the code of the games? for example, 9NG07QJNK38J it's the Among Us' code

**Comment by redphx** [comment]
Since version 3.0.5 it's no longer required to enable the MKB feature in the Settings UI, just setting `ENABLE_NATIVE_MKB_BETA` flag to `true` is enough.

**Comment by heitor231233** [comment]
remote play doesn't find my console

**Comment by vresade** [comment]
how can i add fortnite to the list?

**Comment by Zooen7** [comment]
Bom

**Comment by redphx** [comment]
xCloud now has official native MKB support
