### ISSUE TITLE
[Bug] Can't leave the queue

### ISSUE THREAD

**Issue by echolane** [redphx/better-xcloud#210]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 109.0.1518.140 (Official build) (64-bit)
 - Better xCloud Version: 3.0

**Describe the bug**
When you click on the arrow/button located in the upper left corner of the screen, only the “superficial” part of the site used by Better xCloud (game art, countdown) is removed. I don't have any other extensions or userscripts. When Better xCloud is disabled, everything works fine.

**Screenshots/Videos**
[Video](https://github.com/redphx/better-xcloud/assets/103898992/cf0bfaab-1f11-479a-949a-8a2e0fb2b9c1)

**Comment by redphx** [comment]
Thanks for reporting. I noticed that too. It was caused by an xCloud's bug.  

This version should fix it: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js
