### ISSUE TITLE
[Feature] Bind to mute/unmute mic

### ISSUE THREAD

**Issue by GuhdVibe** [redphx/better-xcloud#211]
**I'm using:**  
- OS: windows
- Browser: edge
  
**I want to suggest this feature:**  
...Is it possible to add a method to mute/unmute the microphone, like push-to-talk or something similar? I play some games where I can't assign additional binds for push-to-talk, so having an alternative method to disable the microphone by the betterxcloud would be very useful!

**Comment by redphx** [comment]
Yes, I'm planning to overhaul the shortcuts feature, but I don't have a timeline at the moment

**Comment by redphx** [comment]
Move to #378
