### ISSUE TITLE
[Bug] Uncaught Error: [Better xCloud] Executing workaround for Safari     at <anonymous>:2696:11

### ISSUE THREAD

**Issue by estebananex** [redphx/better-xcloud#212]
**Platform**
 - Device: MacOS 
 - Browser: Electronjs - Browser Version:
 - Better xCloud Version: 3,0,1

**Describe the bug**
Uncaught Error: [Better xCloud] Executing workaround for Safari
    at <anonymous>:2696:11

I have this error in console of my electron app im making. I want to create a xbox client with remote play and xcloud with social functionalities with electronjs because it's the most familiar language for me, I'm a little developper and I can't create the system alone so I tried to use this userscript and inject it into my app but it show this error and it says "Failed to run better xbox "
I tried to diable safari workarround there isn't errors but the setting button not showing. If someone wants to work with me on this project I'm open to any suggestions

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
The `better-xcloud.user.js` script should be executed before the page is loaded (similar to `@run-at document-start`)

**Comment by estebananex** [comment]
Thanks it solves some errors but there are so many errors at this Time I cant fix all of it so I am going to discord to find some help.
