### ISSUE TITLE
[Bug] Section title obscures setting

### ISSUE THREAD

**Issue by echolane** [redphx/better-xcloud#215]
**Platform**
 - Device: Desktop
 - Browser: Edge
 - Browser Version: 109
 - Better xCloud Version: 3.0.2.1

**Describe the bug**
The stream section title is too large (perhaps in other sections in other languages ​​too) and therefore obscures the setting itself.

**Screenshots/Videos**
[image](https://github.com/redphx/better-xcloud/assets/103898992/b8c0b6f7-f959-4fc1-9ec5-32803498148c)

**Comment by redphx** [comment]
Thanks for reporting

**Comment by redphx** [comment]
Fixed: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by echolane** [comment]
Thanks.
