### ISSUE TITLE
[Bug] Keyboard and mouse extension to move the character to the right and left in Fortnite is slow

### ISSUE THREAD

**Issue by ghost** [redphx/better-xcloud#216]
**Platform**
 - Device: Laptop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 120.0.2210.121
 - Better xCloud Version: 3.0.2.1

**Describe the bug**

Moving the character to the right and left using A and D takes time when playing Fortnite (I’m not talking about ping). This doesn’t happen when I use another extension called “Keyboard & Mouse for Xbox xCloud”. I will send a link to a YouTube video that will help you understand better by watching. I tried to find a solution but couldn’t, and this affects gameplay because Fortnite requires speed. Sorry for the English, I used the translator.

**Screenshots/Videos**
Youtube video:
https://youtu.be/m_1btKJVrys

**Comment by redphx** [comment]
I tested and didn't have that problem. Have you tried disabling the "Keyboard & Mouse" extension entirely in `chrome://extenions` ?

**Comment by GuhdVibe** [comment]
I'm having the same problem. When i need to strafe, the character just have a delay to move. 
I will test disabling the kbm extension entirely and then come back to give the feedback.

Edit: I just removed the KBM extension and the problem persist... 
Also, when i tried to assign mouse button4 (side button) the kbm tab on betterxcloud just closed.

**Comment by ghost** [comment]
The first thing I did was disable and remove the 'Keyboard & Mouse' extension, but the problem persisted.

**Comment by redphx** [comment]
Try to change [this line](https://github.com/redphx/better-xcloud/blob/main/better-xcloud.user.js#L4199) to:

```
index: 0,
```

**Comment by ghost** [comment]
I changed but I still have the problem of taking too long.

**Comment by ZouninJK** [comment]
maybe dead zone on the left analog stick?

**Comment by redphx** [comment]
I was able to re-produce the problem. Working on a fix.

**Comment by redphx** [comment]
@Suitt01 @GuhdVibe pls test this version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by redphx** [comment]
Fixed in 3.0.3  

I'd recommend not using the "Keyboard & Mouse for Xbox xCloud" extension along with Better xCloud as it might cause problems.

**Comment by ghost** [comment]
how do you also fix mouse is not feeling like on playing with mouse but feels like its still controller?

**Comment by Lokizinnn** [comment]
Hello, I just discovered this extension and wanted to ask if it only works in Fortnite or is it in another game? I tested Battlefield 2042, Plague Tale and Sniper Elite and the keyboard and mouse don't work. awaiting

**Comment by ghost** [comment]
Thanks, it's better now.
