### ISSUE TITLE
[Bug] Sound - transmission

### ISSUE THREAD

**Issue by OverlandSokka** [redphx/better-xcloud#217]
**Platform**
 - Device: Desktop
 - OS: Windows 11
 - Browser: Edge
 - Browser Version: 120.0.2210.121 
 - Better xCloud Version: 3.0.2.1

I was playing today and for no reason my stream started to crash for 1 sec and back to normal, but later when i was playing Starfield my stream started to fail the sound and it was not the internet because i tested before. After this i refreshed the page and tried to play but this time i had no sound.

**Comment by redphx** [comment]
xCloud sometimes doesn't have sound in the game. You have to quit it and connect to a new session. Refreshing the page won't work.
