### ISSUE TITLE
[Feature] Enable mic support on Safari

### ISSUE THREAD

**Issue by ILikePlayingGames** [redphx/better-xcloud#22]
On Safari for Mac, xCloud does not officially support the microphone, however it works if the user agent is changed to Edge for Windows. Can you please add a switch to enable microphone support on Safari?

**Comment by redphx** [comment]
I checked. It won't be possible until I find a way to bypass their browser detection method without having to change the User-Agent.

**Comment by Hukolla** [comment]
> Я проверил. Это будет невозможно, пока я не найду способ обойти их метод обнаружения браузера без изменения User-Agent.

Hello. Please let's see. Is it possible to add a change of localization?

**Comment by redphx** [comment]
Good news: I found a way. Will add this feature in the next version

**Comment by ILikePlayingGames** [comment]
Thank you so much!

**Comment by redphx** [comment]
@ILikePlayingGames now available in the Dev version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js  
Try to change "User-Agent profile" to "Edge on Windows".  

<img width="456" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/245c9763-0167-40ba-af69-7132e8cddcdc">

**Comment by ILikePlayingGames** [comment]
Thanks! It works

**Comment by Diego-Perez-Botero** [comment]
xCloud just rolled out a fix. You should now be able to mute/unmute your mic from the in-stream overlay menu ("..." at the top left while streaming) on MacOS+Safari without having to do User Agent spoofing.

**Comment by redphx** [comment]
@Diego-Perez-Botero wow, a dev from xCloud team. Thank you so much for the fix!

**Comment by ILikePlayingGames** [comment]
@Diego-Perez-Botero Thank you so much!

**Comment by ILikePlayingGames** [comment]
@Diego-Perez-Botero Sorry for the 2nd ping. Can you please update the documentation at https://support.xbox.com/en-US/help/games-apps/cloud-gaming/troubleshoot-cloud-gaming-apple to indicate that the microphone is now supported on iOS?

**Comment by Diego-Perez-Botero** [comment]
I appreciate the ping! I actually reached out to the people in charge of documentation earlier today and pointed them to that article and some other support pages that need updates. It should get fixed soon 😉

**Comment by ILikePlayingGames** [comment]
Thank you!
