### ISSUE TITLE
[Bug] KBM - A key is pressed even if it is released

### ISSUE THREAD

**Issue by echolane** [redphx/better-xcloud#220]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 109
 - Better xCloud Version: 3.0.3

**Describe the bug**
Sometimes it happens that a key is pressed even if you release it. After this, the key is released after quite a long time (5-10 seconds), and sometimes it is not released at all.
The only thing that helps is minimizing the browser (or just clicking on another window) and going back.
It's not about Internet speed/latency. Changing to a lower resolution (1080p -> 720) did not help.
I don't have the Xbox xCloud Keyboard and Mouse extension.

**Screenshots/Videos**
[Video](https://github.com/redphx/better-xcloud/assets/103898992/1236e263-cda1-4d45-a17b-afa48527cad8) (trying to scroll the steering wheel to the left, but due to the fact that D (I'm using the WASD preset) is pressed, it scrolls only to the center)

**Comment by ghost** [comment]
having same issue, also mouse needs more adjustment. And maybe Presets for FPS, TPS etc.

**Comment by Dplay2626** [comment]
I have the same problem, I already tried changing browsers and it still didn't solve it.

**Comment by redphx** [comment]
Any chance you're using/enabling different input method (to type languages other than English) while playing?  

Does it happend with 3.0.2.1?

**Comment by Diegugo** [comment]
it hapens to me almost instantly

**Comment by WihelmHalevi** [comment]
Estou tendo o mesmo problema, rotineiramente...
É possível reinstalar a versão antiga? Pois tudo funcionava perfeitamente.

**Comment by MagnosLuan** [comment]
Same here.
Chrome with the 3.0.3 version.

**Comment by redphx** [comment]
> Any chance you're using/enabling different input method (to type languages other than English) while playing?
> 
> Does it happend with 3.0.2.1?

Please answer my question

**Comment by redphx** [comment]
Try to switch to English keyboard and try again

**Comment by Dplay2626** [comment]
> Alguma chance de você estar usando/habilitando método de entrada diferente (para digitar idiomas diferentes do inglês) durante a reprodução?
> 
> Isso acontece com o 3.0.2.1?

Yes, I use the Brazilian input to type, I'm Brazilian, but what I found strange was the fact that no one here in Brazil reported this problem.

**Comment by LH-blip** [comment]
> > Alguma chance de você estar usando/habilitando método de entrada diferente (para digitar idiomas diferentes do inglês) durante a reprodução?
> > Isso acontece com o 3.0.2.1?
> 
> Sim, eu uso a entrada brasileira para digitar, sou brasileiro, mas o que achei estranho foi o fato de que ninguém aqui no Brasil relatou esse problema.

I reported it but the adm closed it because it had already reported the bug... 

But is it just changing the keyboard to English?

**Comment by HQ672** [comment]
I have the same problem after I updated to better xcloud 3.0.3

**Comment by HQ672** [comment]
> > Alguma chance de você estar usando/habilitando método de entrada diferente (para digitar idiomas diferentes do inglês) durante a reprodução?
> > Isso acontece com o 3.0.2.1?
> 
> Sim, eu uso a entrada brasileira para digitar, sou brasileiro, mas o que achei estranho foi o fato de que ninguém aqui no Brasil relatou esse problema.

I'm also Brazilian and I'm going through the problem

**Comment by echolane** [comment]
> Any chance you're using/enabling different input method (to type languages other than English) while playing?
> 
> Does it happend with 3.0.2.1?

Yes, but after switching to English language the problem still exists.

On version 3.0.2.1 I don’t see this problem.

**Comment by redphx** [comment]
Try this version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js  
This version also increase the responsiveness of the emulated sticks

**Comment by Dplay2626** [comment]
> Try this version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js This version also increase the responsiveness of the emulated sticks

Bro, I tested this version and it worked as far as I played, for about 20 minutes without any problems described, I only tested it on a server and so far I haven't had any problems.

**Comment by redphx** [comment]
> Bro, I tested this version and it worked as far as I played, for about 20 minutes without any problems described, I only tested it on a server and so far I haven't had any problems.

Thanks for testing. It should work with all servers and games.

**Comment by echolane** [comment]
> Try this version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js This version also increase the responsiveness of the emulated sticks

I tested this too and there were no problems. The sticks actually respond faster, which is nice. Thank you.

**Comment by LH-blip** [comment]
> > Bro, I tested this version and it worked as far as I played, for about 20 minutes without any problems described, I only tested it on a server and so far I haven't had any problems.
> 
> Thanks for testing. It should work with all servers and games.

I tested it here and it's working fine, thanks

**Comment by redphx** [comment]
Fixed in 3.0.4

**Comment by PabloSebas** [comment]
> Try this version: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js This version also increase the responsiveness of the emulated sticks

It works!, thank you very much

**Comment by PabloSebas** [comment]
> Fixed in 3.0.4

What I can say is that I felt that in version 3.0.3 in the shooters the right stick was more fluid, now it moves more square

**Comment by redphx** [comment]
> > Fixed in 3.0.4
> 
> What I can say is that I felt that in version 3.0.3 in the shooters the right stick was more fluid, now it moves more square

I didn't change the behaviour of the mouse movement
