### ISSUE TITLE
[Bug] ... D-pad keypad W,S,D,A bugging

### ISSUE THREAD

**Issue by LH-blip** [redphx/better-xcloud#221]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Edge Dev
 - Browser Version: 122.0.2325.0
 - Better xCloud Version: 3.0.3

**Describe the bug**
Keyboard of the directions W,S,D,A bugging when I press W the character goes to that direction, being necessary to deactivate the keyboard and mouse with F9, then it goes back to normal, but a few seconds later it bugs again

**Screenshots/Videos**

**Comment by redphx** [comment]
Duplicate #220
