### ISSUE TITLE
Native Keyboard and Mouse 

### ISSUE THREAD

**Issue by LuizH2409** [redphx/better-xcloud#223]
I went to tampermonkey and I activated the Native Keyboard and Mouse, it aparentely worked, so I did enter into the game and any keyboard did not work, it keeps stopped in the first page and I could not use F9 as well.

![Captura de tela 2024-01-16 220246](https://github.com/redphx/better-xcloud/assets/156271870/14e43e72-2b84-4fd9-80bc-7597c5ae7942)

![Captura de tela 2024-01-16 221300](https://github.com/redphx/better-xcloud/assets/156271870/65b78586-b2bd-472b-b6f1-f9524e07384e)

**Comment by redphx** [comment]
> There is no guarantee that this feature will work  
  
#208
