### ISSUE TITLE
[Bug] Stream stats says "SPF" instead of FPS

### ISSUE THREAD

**Issue by evanpaul14** [redphx/better-xcloud#224]
**Platform**
 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 120.0.6099.199
 - Better xCloud Version: 3.0.4

**Describe the bug**
Typo
**Screenshots/Videos**
![Screenshot 2024-01-17 at 2 45 52 PM](https://github.com/redphx/better-xcloud/assets/120766197/7e7ca534-4584-4a3e-bc09-cb3e7c5001cc)

**Comment by redphx** [comment]
The "FPS" text is hardcoded, not a translation. Something outside must be changing this. Same to "P.L." and "F.L." (should be "PL" and "FL")
