### ISSUE TITLE
[Bug] Can change video settings when clarity boost enabled

### ISSUE THREAD

**Issue by echolane** [redphx/better-xcloud#225]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 109
 - Better xCloud Version: 3.0.4

**Describe the bug**
I can change video settings when Edge built-in clarity boost is enabled. When you change any video setting, the stream moves up left.

**Screenshots/Videos**
[Video](https://github.com/redphx/better-xcloud/assets/103898992/bb8f055b-4fd1-4f7d-aaa9-04a82116d9e8)

**Comment by redphx** [comment]
Duplicate #64 #191
