### ISSUE TITLE
Zoom with clarity boost

### ISSUE THREAD

**Issue by gusttaaq** [redphx/better-xcloud#226]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 120.0.2210.133 
 - Better xCloud Version: 3.0.4

Bug:
When i active the clarity boost my screen give a BIG zoom and this is only with the extension activated 

Screenshots

![p3](https://github.com/redphx/better-xcloud/assets/157085502/6989cc14-dada-4663-9187-20025f5e6284)
![p2](https://github.com/redphx/better-xcloud/assets/157085502/f8821e5e-c690-4551-a85b-d9101c27b4a7)
![p1](https://github.com/redphx/better-xcloud/assets/157085502/d3f7ed2a-ae47-4854-bfc0-f30bf74df891)

**Comment by redphx** [comment]
Duplicate #191
