### ISSUE TITLE
[Feature] Work with electronjs

### ISSUE THREAD

**Issue by estebananex** [redphx/better-xcloud#227]
**I'm using:**  
- Device: HP Spectre x369
- OS: Windows 11 Professional 
- Browser: Electronjs
  
**I want to suggest this feature:**  
I want a support for using our of the tamper monkey extension because I want to make a Xbox cloud client with all your functionalities for my friends but when the script is directly injected into the page I have a safari workaround error or also when it's directly packaged into an extension

**Comment by redphx** [comment]
This is out of scope, and won't be supported. Please don't create another issue for it.
