### ISSUE TITLE
[Bug] Remote play doesnt work

### ISSUE THREAD

**Issue by tutorfr** [redphx/better-xcloud#229]
**Platform**
 - Device: Phone
 - OS: Android
 - Browser: Kiwi
 - Browser Version: latest
 - Better xCloud Version: latest

**Describe the bug**
The xcloud remoteplay doesn't even work whenever I try to open it it just shows a black screen after the xbox startup but on the xbox app it works just fine please fix this

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Same or different network?  
Is it the same as #196

**Comment by tutorfr** [comment]
> Same or different network? Is it the same as #196

It's different network but it still works on the xbox app and yeah I think it's the same as #196 but the screen just turns black and then refreshes whenever I try to remote play

**Comment by redphx** [comment]
Let's move the discussion to that issue
