### ISSUE TITLE
[Feature] Force 60 fps settings

### ISSUE THREAD

**Issue by RoonMoonlight** [redphx/better-xcloud#23]
**Is your feature request related to a problem? Please describe.**
Sometimes there should be the case that you should use other servers when the current server is very lagging, but if you change to other servers the cloud forces you to cap at 45 fps or less depending on ping.

**Describe the solution you'd like**
Would be like to see options to 'Force 60 fps' regarding of connection status.

**Describe alternatives you've considered**
None at the moment.

**Additional context**
Would work very well alongside with 'Force 1080p' settings.

**Comment by redphx** [comment]
Sorry but I don't think this is possible. The server decides the framerate and nothing I can do about that.

**Comment by ricardo404** [comment]
A bit of collaboration: I think this has to do with how Xbox understands what FPS is right for the game. For example, using Better Xcloud's Stream Status Feature, I notice that when using Microsoft Flight Simulator, it is capped at 30 FPS. Using GTA V, it uses 60 FPS. GTA V is more optimized on the Cloud than MSFS, so this is fixed and cannot be changed by Redphx on the Client side.
