### ISSUE TITLE
[Feature] Ban warning indicator in the Mouse & Keyboard Setup screen.

### ISSUE THREAD

**Issue by Tak-attack** [redphx/better-xcloud#232]
**I want to suggest this feature:**  
...
Although the documentation page for the better xcloud mouse & keyboard feature says "I would NOT RECOMMEND using this feature when playing online, as it can be considered cheating, It would be helpful if that statement was also indicated on the mouse & keyboard settings screen.

**Comment by redphx** [comment]
Thanks. I'll add this warning in the Settings.

**Comment by redphx** [comment]
Added in 3.1
