### ISSUE TITLE
[Feature] Custom touch layout for non-touch games

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#237]
![](https://github.com/redphx/better-xcloud/assets/96280/3597218f-58b8-405f-8cf0-914aac8a19e1)

It's possible to have a custom touch layout for non-touch supported games. Aiming with gyro is also supported.

Limitations:
- Only 1 layout per game

I'll start first with Palworld.  
Test version: https://github.com/redphx/better-xcloud/raw/feature/custom_tabs/better-xcloud.user.js

**Comment by redphx** [comment]
@Tak-attack: the bug with "basic controls" setting has been fixed

**Comment by redphx** [comment]
Added Remote Play support

**Comment by redphx** [comment]
Ready to be released. Not sure if the gyro's sensitivity is too high.

**Comment by Tak-attack** [comment]
@redphx 
Here are my thoughts on custom layouts.

- Gyro is working as expected, but it can be annoying if it is always on. can it only work when LT/RB/LR is pressed and only when it is on? (If it can't be toggled due to xcloud specs, it can be left as is)
- LB/RB should be button+joystick as well as joystick+RT, not toggle. If there is no space in the layout, it can be left as is.
- LS should also be non-toggle. (Because dash during long press is off by default)
- Can't the LS be pressed when the movement joystick is fully down to put the player in dash mode (Grounded has a layout like that).
- The Shot icon on the right is confusing and could be RT.
- It would be nice to be able to pull the trigger while moving on the left. The same notation could be RT.
- I think the gyro sensitivity is fine as it is now.
- The RS position is fine in the lower left corner as it is not used often (thanks for the update).

**Comment by redphx** [comment]
Thanks for the feedback. Reload the game for the new layout.

> - Gyro is working as expected, but it can be annoying if it is always on. can it only work when LT/RB/LR is pressed and only when it is on? (If it can't be toggled due to xcloud specs, it can be left as is)

I'm not sure if it's even possible.  

> - LB/RB should be button+joystick as well as joystick+RT, not toggle. If there is no space in the layout, it can be left as is.

Fixed. Now you can move around while holding LB/RB.

> - LS should also be non-toggle. (Because dash during long press is off by default)
> - Can't the LS be pressed when the movement joystick is fully down to put the player in dash mode (Grounded has a layout like that).

Fixed. Implemented same feature as Grounded and remove the LS button.

> - The Shot icon on the right is confusing and could be RT.

It has a different icon because it's a combination of LT and RT. Also you can hold it and aim around.

> - I think the gyro sensitivity is fine as it is now.

Changed sensitivity from 2 to 1 (same as Grounded).

> It would be nice to be able to pull the trigger while moving on the left. The same notation could be RT.

I don't understand this?

**Comment by Tak-attack** [comment]
Thank you for your quick response.

>・The Shot icon on the right is confusing and could be RT.
>It has a different icon because it's a combination of LT and RT. Also you can hold it and aim around.

OK. I did not notice RT and LT being pushed.

>・It would be nice to be able to pull the trigger while moving on the left. The same notation could be RT.
>I don't understand this?


RT is used for purposes other than shooting.
The Shot icon on the left side could be "RT".
<img width="346" alt="キャプチャ" src="https://github.com/redphx/better-xcloud/assets/149154024/acaa9956-55ef-466e-8e23-0724e4673f08">

**Comment by redphx** [comment]
> The Shot icon on the left side could be "RT".

Fixed.

**Comment by redphx** [comment]
Updated: now you can move around while holding LT  
With this change not sure if this "aim" button is no longer useful. Should I remove it @Tak-attack?

<img width="56" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/ecd13e1a-8d8c-4d5e-9150-55a1df176319">

**Comment by Tak-attack** [comment]
> Updated: now you can move around while holding LT With this change not sure if this "aim" button is no longer useful. Should I remove it @Tak-attack?
> 
> <img alt="image" width="56" src="https://private-user-images.githubusercontent.com/96280/300336756-ecd13e1a-8d8c-4d5e-9150-55a1df176319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDUwNDAsIm5iZiI6MTcwNjUwNDc0MCwicGF0aCI6Ii85NjI4MC8zMDAzMzY3NTYtZWNkMTNlMWEtOGQ4Yy00ZDVlLTkxNTAtNTVhMWRmMTc2MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA1MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NjUyNzliZTUyZDZhODI1YWU2MjY5MThmOWI1YzUzZWZlNjY4ZGRiN2U4NDBkNjg5Yjg3YmFjMDYwMmQ5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wWRD2mRuudxySt-4_ZbQgnmi2c7cqHTK_zK6D0VQYzc">

Moving while holding down LT/RB/LB seems to be more unstable than using the joystick.
If there is no particular reason, I think the aim button should remain in place.

**Comment by redphx** [comment]
Then I'll keep it. If there is no more changes I'll release this feature today.

**Comment by Tak-attack** [comment]
> それなら、私はそれを保管します。これ以上の変更がなければ、この機能を本日リリースします。

No further feedback from me at this time. Looking forward to the release!

**Comment by redphx** [comment]
Thanks for the help!
