### ISSUE TITLE
[Bug] In Remote play, selecting "All games" in the touch controller settings will show the basic controls.

### ISSUE THREAD

**Issue by Tak-attack** [redphx/better-xcloud#240]
**Platform**
 - Device: Black Shark 4
 - OS: Android
 - Browser: Kiwi
 - Better xCloud Version: 3.0.5-3.1

**Describe the bug**
In Remote Play, when "All Games" is selected in the touch controller settings, basic controls are displayed even for games that support custom layouts (except Palworld) .

The documentation states that "Games with custom layouts are not affected.”

For cloud games, custom layouts will still display correctly in the "All Games" setting.

I downgraded to 3.0.5 and confirmed the same behavior.

**Comment by redphx** [comment]
I saw this problem before, but it didn't always happen. I think reload the page will solve it.  

I pushed a new fix for the touch controller related to the custom layout feature: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js. Not sure if it also fixes this problem.  

Also, I added [a custom layout for Brotato](https://github.com/redphx/better-xcloud/discussions/241#discussioncomment-8295670)

**Comment by redphx** [comment]
@Tak-attack please test this version: https://github.com/redphx/better-xcloud/raw/feature/custom_layout_selector/better-xcloud.user.js

It fixes the bug you have in Remote Play.

I also added the ability to switch between custom layouts. You can test with Brotato.

![brotato](https://github.com/redphx/better-xcloud/assets/96280/197e111d-a1ab-4fbc-8dd6-4fca7a6097e4)

**Comment by Tak-attack** [comment]
Tested. We checked both remote play and cloud play.
We have confirmed that the remote play bug has been fixed. The ability to switch custom layouts is also working well.

However, inexplicably, the layout of the Palworld launched with this test version has reverted to the previous one(Dev Version?). (confirmed via remote play) (have not tried the cloud version yet due to long wait times)
![unnamed](https://github.com/redphx/better-xcloud/assets/149154024/ebc54c7b-c33a-4317-8b8d-a11f881248a3)

The official version, V3.1, still renders the correct layout.

**Comment by redphx** [comment]
Because the layout of Palworld in the dev version is still the old one. I've updated it. Please refresh and try again.

**Comment by Tak-attack** [comment]
The layout is the same as before, but we have confirmed that it is Type A on the custom layout switching screen.

**Comment by redphx** [comment]
Sorry I updated the wrong layout. It should be fixed now.

**Comment by Tak-attack** [comment]
OK.
We have confirmed that the Dev version layout has been updated. Thank you for your support!
