### ISSUE TITLE
[Bug] Message of activating keyboard/mouse doesn't disappear when clicking on the message.

### ISSUE THREAD

**Issue by LucasG021** [redphx/better-xcloud#247]
- Device: Desktop.
 - OS: Windows 10
 - Browser: Edge and Chrome
 - Browser Version: latest version
 - Better xCloud Version: 3.1.4

I can't play with keyboard and mouse because this message won't disappear from the screen. It only goes away if I disable the keyboard and mouse function.

![Captura de Tela (189)](https://github.com/redphx/better-xcloud/assets/47404380/96bd1152-e009-47fa-8f74-15c2441c6d79)

**Comment by redphx** [comment]
It didn't happen to me when I tested on both Chrome + Edge in Mac, same game

**Comment by LucasG021** [comment]
The new update that came out solved the problem

**Comment by redphx** [comment]
I didn't fix anything. It was caused your device.
