### ISSUE TITLE
[Bug] cannot get the list of consoles

### ISSUE THREAD

**Issue by KiriKira** [redphx/better-xcloud#248]
**Platform**
 - Device: Phone, Laptop
 - OS: Windows, Android
 - Browser: Chrome, Kiwi
 - Browser Version:
 - Better xCloud Version: 3.1.5

**Describe the bug**
Cannot get the list of consoles to start remote play since hours ago but it worked before, meanwhile the official Xbox Beta app is able to stream and play.
When I look into the dev tool, I find that it failed to connect to <https://wus2.gssv-play-prodxhome.xboxlive.com/v6/servers/home?mr=50> , which may relate to the problem.
By the way, I'm trying from China and also tried Japan's VPN.

**Screenshots/Videos**
![Screenshot_20240209_230138_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/32393884/c7bd236c-cbc3-4b18-9e19-429656e59cca)

**Comment by redphx** [comment]
The WestUS2 server for Remote Play is down at the moment.  
You can use this version to switch to EastUS: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by KiriKira** [comment]
That works, thank you!
