### ISSUE TITLE
[Feature] control vibration on mobile devices

### ISSUE THREAD

**Issue by Kagekaii** [redphx/better-xcloud#249]
**I'm using:**  
- Device: mobile
- OS: android
- Browser: kiwi/lemur
  
**I want to suggest this feature:**  
**I control vibration on mobile devices: think it would be interesting to implement this feature. I would like to get an answer as to whether or not it is possible to do this. I know that it is not possible to use a keyboard and mouse on Android due to the lack of an API, and I wanted to know if there is a limitation on using the controller's vibration**

**Comment by redphx** [comment]
What do you mean?  

Isn't it already implemented: https://better-xcloud.github.io/ingame-features/#controller

**Comment by Kagekaii** [comment]
> What do you mean? > > It is no longer implemented: https://better-xcloud.github.io/ingame-features/#controller only the mobile device vibrates, the joystick does not (my Joystick has the vibration option) but in none of the browsers mentioned above (lemur and kiwi) the joystick vibrates

**Comment by redphx** [comment]
Does your controller support vibration in browser? You can test it here https://hardwaretester.com/gamepad

**Comment by Kagekaii** [comment]
omg, no! but why in test applications does the vibration work normally, and on the website it says N/A?? It's a PS4 controller, is there any way around this?

**Comment by redphx** [comment]
Browsers don't always have the same controller support as system.  

So this is not a bug.

**Comment by vm06007** [comment]
> Does your controller support vibration in browser? You can test it here https://hardwaretester.com/gamepad

is there a way to trigger this with javascript just like on https://hardwaretester.com/gamepad when clicking vibration button? whats going on behind the scenes there?
