### ISSUE TITLE
[Bug] Game gallery fails to load when "disable social features" is on

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#250]
**Platform**
 - Device: Shield TV
 - OS: Android TV
 - Browser: Kiwi
 
**Describe the bug**

On the game detail pages Microsoft has added a gallery now with videos/screenshots of the game. But with "Better xCloud" enabled the gallery fails to load with showing an error message. I toggled some settings to find out what is causing this and noticed that this only happens if "disable social features" is on. If it's off the gallery shows up as expected.

So I hope this can be fixed so I can keep social features disabled without losing the ability to see the galleries.

**Comment by redphx** [comment]
Do you mean this feature?

<img width="769" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/a197779c-c215-495c-8b03-4a38599ec0df">

It works fine for me

**Comment by Tak-attack** [comment]
I also checked on Android (Kiwi) and similarly, if "Disable social features" is turned on, the gallery will not be displayed with an error.
![IMG_20240211_133930](https://github.com/redphx/better-xcloud/assets/149154024/3fdfc6c9-3c11-458c-8167-16e13a472f8e)

**Comment by Tak-attack** [comment]
Thanks for the fix. The gallery is displayed correctly in this Kiwi browser as well.

**Comment by KingNothing81** [comment]
@Tak-attack: Thanks for sharing the screenshot. I wanted to add one myself, but didn't use my Shield TV on the weekend.

@redphx: And thanks to you for fixing this so quickly. :)
