### ISSUE TITLE
[Bug] Profile page not loading 

### ISSUE THREAD

**Issue by mrdoitall2712** [redphx/better-xcloud#252]
**Platform**
 - Device: Phone, Laptop, Desktop, TV...
 - OS: Windows, Android, iOS...
 - Browser: Chrome, Safari, Kiwi...
 - Browser Version:
 - Better xCloud Version:

**Describe the bug**
... whenever you open see full profile in xcloud it never loads 

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Fixed https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js
