### ISSUE TITLE
[Bug] Remote play is completely bugged on Linux

### ISSUE THREAD

**Issue by Daniel908** [redphx/better-xcloud#257]
**Platform**
 - Device: Desktop
 - OS: Linux/Ubuntu
 - Browser: Edge
 - Browser Version: 121.0.2277.113
 - Better xCloud Version: 3.1.7

**Describe the bug**
... Remote play isn't work properly. I'm playing at home, on the same network as the console. I tested it on Windows and it is working normally. The image appears, but everything simply becomes buggy.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Try setting "Visual quality" option to "Normal"

**Comment by Daniel908** [comment]
Still doesn't work well, When I try to use it, the image appears with a
huge delay, often the image is static on "remote play" while on TV I'm in a
completely different place. It doesn't even work correctly in the console
menus, the delay is too long. Everything is pretty buggy, I've tried
everything.

Em qui., 15 de fev. de 2024 00:33, redphx ***@***.***>
escreveu:

**Comment by redphx** [comment]
I still think this is Linux's problem: https://www.reddit.com/r/xcloud/comments/174zs29/poor_performance_on_low_end_hardware/k4cp443/

**Comment by KingNothing81** [comment]
@Daniel908: The difference between using Windows and Ubuntu/Linux might be that you are using open source video drivers on Ubuntu that don't support hardware acceleration. If that's the case installing the restricted drivers for your hardware may help:


https://help.ubuntu.com/community/RestrictedDrivers

**Comment by Daniel908** [comment]
It worked. I installed the restricted drivers, and now it's working
normally. I didn't realize it was a problem with cloud gaming because I
wasn't using it anymore because of the queues, I just use remote play.
Thank you!!

Em qui., 15 de fev. de 2024 15:50, KingNothing81 ***@***.***>
escreveu:
