### ISSUE TITLE
[Bug] Stream without audio when internet drops

### ISSUE THREAD

**Issue by Willendes** [redphx/better-xcloud#259]
**Platform**
 - Device: Laptop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 122.0.2365.30
 - Better xCloud Version: 3.1.7

**Describe the bug**
Basically what the title says: when internet drops and the screen of "trying reconnect to server" shows, then when i return to game i need to refresh the page bcs it returns without audio

**Comment by redphx** [comment]
Fixed: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js
