### ISSUE TITLE
[Feature] Region switching feature on the xcloud page

### ISSUE THREAD

**Issue by Tak-attack** [redphx/better-xcloud#266]
We would like the ability to switch the region of the xcloud page (not the server region).

Especially in the Japanese store, games from other countries are often not released due to various reasons such as ratings, etc. There are a certain number of Japanese users who switch the store region to use the overseas version of the store.
Of course, we know that simply changing the URL will change the region of the xcloud page. However, it seems less complicated if the region can be selected from a drop-down list.

**Comment by redphx** [comment]
Does changing the URL really allow you to play unavailable games? I thought it was based on your IP address?

**Comment by Tak-attack** [comment]
> Does changing the URL really allow you to play unavailable games? I thought it was based on your IP address?

Here are the search results comparing the differences by changing only the region of the URL. (ja-JP and en-US)

<img width="1187" alt="スクリーンショット 2024-02-29 204505" src="https://github.com/redphx/better-xcloud/assets/149154024/7492688d-cfc5-49c0-b056-078e7e772653">

<img width="1174" alt="スクリーンショット 2024-02-29 204439" src="https://github.com/redphx/better-xcloud/assets/149154024/26f56641-a114-44d5-bac2-fa843d7ff656">

As you can see, there are many games that are not available in ja-JP, such as "Dead island", "Dead space", and "Walking dead". This is despite the fact that some of these games include Japanese in the game.

These games can be played on JapanEast servers, for example, regardless of the server region.
Since this is an official xcloud specification, changing the URL region should not be subject to a ban.

**Comment by redphx** [comment]
Nah, I don't think Xbox care. Just play it.
