### ISSUE TITLE
[Bug] MKB Support not working 

### ISSUE THREAD

**Issue by Sus002** [redphx/better-xcloud#269]
- Device: Desktop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 121.0.2277.128 
 - Better xCloud Version: 3.1.8

Hi, i've just upgraded to the last version of the extension and when i tried to change the script to enable the mkb support just like i was doing every time a new version droped since mouse and keyboard came out, for MS Flight Sim and it didnt work, the little mouse sign doesnt even appear anymore, and i wanted to know if its desabled or something like that, thx

![Screenshot 2024-02-23 123228](https://github.com/redphx/better-xcloud/assets/155697131/2978a1b6-a367-479b-be1a-b2f258c7f139)
![Screenshot 2024-02-23 123300](https://github.com/redphx/better-xcloud/assets/155697131/11b3d738-ae56-4540-b6e6-4bbd4502ad97)
![Screenshot 2024-02-23 123310](https://github.com/redphx/better-xcloud/assets/155697131/4b9250f4-4059-44a3-a99d-0ff72355fd09)

**Comment by redphx** [comment]
Fixed https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by Sus002** [comment]
Thank you so much! appreciate it! great work with the extension
