### ISSUE TITLE
[Bug] Latest update broke mic functionality

### ISSUE THREAD

**Issue by TC131** [redphx/better-xcloud#271]
After newest update the mic mute/unmute doesn't seem to work. I can hear game audio with headset on android and PC but I can't hear chat nor can I anyone hear me. I've narrowed it down to xcloud. Everything works fine through the browser with better xcloud disabled.

**Comment by redphx** [comment]
Try to disable the "volume control" feature in the Settings

**Comment by TC131** [comment]
Yeah, That did it. I must have accidentally turned that on. Is that option supposed to mess with mic input?

**Comment by redphx** [comment]
Maybe? Is there any game that allows me to test the voice chat feature by myself?

**Comment by TC131** [comment]
Not sure, I was testing with hell loot loose, I was just jumping in and using proximity. Was quicker to get into for tests than halo.
