### ISSUE TITLE
[Feature] using the gyroscope in fps/race game on the smartphone

### ISSUE THREAD

**Issue by Murilo0O** [redphx/better-xcloud#279]
I saw the use of the gyroscope in Gears of War and I was wondering if it would be possible to use it in other games. like in Forza Horizon 5 and use the cleular as a kind of steering wheel. or use it in any other game

**Comment by Tak-attack** [comment]
I made a similar suggestion (#233), but there is no generic gyroscope control and a custom layout control must be created for each game.

See the [Games with custom touch controls](https://github.com/redphx/better-xcloud/discussions/241) page for more information.
There are several games with custom layouts that support gyroscope, such as Palworld and RESIDENT EVIL 2.

**Comment by Tak-attack** [comment]
Also, there is a custom layout for the Forza series, but gyroscopes are not currently supported.
It should be possible to control the steering wheel with the gyroscope by editing the custom layout, but we have not tried it yet.

**Comment by redphx** [comment]
Duplicate #233
