### ISSUE TITLE
[Bug] Can not get remote play to work through kiwi browser on Android

### ISSUE THREAD

**Issue by NominalRabbit** [redphx/better-xcloud#280]
**Platform**
 - Device: Phone, Samsung S23
 - OS: Android 14
 - Browser: Kiwi
 - Browser Version: 120.0.6099.116
 - Better xCloud Version: 3.2.1

With all default settings on xCloud, the only thing I change is the enable remote play setting but it can not connect. It will load the xbox logo followed by a black screen that after awhile, it says we'll be right back and quickly reverts back to the xbox webpage. Xbox remote play works perfectly fine on the Xbox app. This is my first time using this version of xCloud and have not been able to get it to work. Not sure if it's a port issue or not as my nat is already open but if there is a specific port that would be better for xcloud then I can try changing it. I'm running Kiwi browser through Samsung Dex as well as just natively on the phone but neither have worked. I've not yet tried this on the same network as the Xbox is connected to so I can try that later and see if that works. I've attached screenshots of each step of the way. I couldn't get a screenshot of the we'll be right back screen because it happens so fast and goes away almost immediately.
...

**Screenshots/Videos**

![Screenshot_20240306_084610_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/162481230/ed0a44cf-c05f-4f08-82a8-a596bdf4992c)
![Screenshot_20240306_084657_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/162481230/7d55f22b-f5dc-4a59-bd3f-94f7bb9d7378)
![Screenshot_20240306_084638_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/162481230/6a96d0a7-abd1-46e2-9762-8b89bddd5857)
![Screenshot_20240306_084628_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/162481230/1c36a072-f3c4-4b97-8c72-b2ebc82981ec)
![Screenshot_20240306_084619_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/162481230/6ddf72db-5417-42af-9032-2e15c20d595a)
![Screenshot_20240306_084550_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/162481230/d4abfe0a-d64d-43f8-8701-b020b2a7e499)

**Comment by NominalRabbit** [comment]
Leaving an update

I can get it to work when it's on the same network. But not a different network.

**Comment by NominalRabbit** [comment]
I think I may have resolved the issue, I already had port 9002 open for the Xbox since that's what it said in the instructions. I had to delete all of the port forwarding and set them up again and that seemed to have solved the problem. Sorry for posting an issue, I don't know why the port didn't work since it was already open the first time.

**Comment by redphx** [comment]
Glad that it worked

**Comment by Jedibuji** [comment]
Are you using the script through kiwi because the apk standalone won't launch in DEX? I came here seeking advice on that__
