### ISSUE TITLE
[Feature] Set maximum vibration intensity

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#29]

**Comment by Hukolla** [comment]
Cool. Thanks a lot. Localization works!

**Comment by Hukolla** [comment]
[
![2023-07-29_141654](https://github.com/redphx/better-xcloud/assets/131584428/e4622901-2982-404a-b713-7a00e34a6bd5)
![2023-07-29_141845](https://github.com/redphx/better-xcloud/assets/131584428/b9436f87-4ca7-43ba-a7eb-458580e5f8a4)
](url)

**Comment by onwei2001** [comment]
Can you add controller sensitivity adjustment. Driving in gta v, steering is too sensitive.

**Comment by redphx** [comment]
Added in 2.1
