### ISSUE TITLE
[Bug] Timer stay on the screen even when game is already open

### ISSUE THREAD

**Issue by MatLudke** [redphx/better-xcloud#295]
**Platform**
 - Device: Laptop
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Browser Version: 123.0.2420.41 (Official build)
 - Better xCloud Version: 3.2.4

Timer stays on the screen even when the game is already open 

**Screenshots/Videos**
![Screenshot 2024-03-17 171502](https://github.com/redphx/better-xcloud/assets/61805286/5d48c99c-6753-44f4-bd1e-c1c9a1eae03e)

**Comment by redphx** [comment]
Fixed in 3.2.5
