### ISSUE TITLE
[Bug] IPv6 feature is not working

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#3]
xCloud still connects to IPv4 server

**Comment by LifeDreamer24** [comment]
What is it to see if it works on edge?
For Windows 11 you have to use canary for kiosk mode to work btw

**Comment by redphx** [comment]
I don't have Windows so I'm not sure. Maybe it's also `chrome://webrtc-internals`?

**Comment by LifeDreamer24** [comment]
I mean to see if the IPv6 works on the Edge browser.
The other thing is just a reminder about kiosk mode

**Comment by redphx** [comment]
Have you tried openning `chrome://webrtc-internals` in Edge?  
I'll add a feature to show "IPv6" and "HQ stream" statuses in the future (#7)

**Comment by redphx** [comment]
Fixed in [1.3.2](https://github.com/redphx/better-xcloud/releases/tag/v1.3.2)
