### ISSUE TITLE
15 fps on every Game on Noblex Android TV

### ISSUE THREAD

**Issue by Kashe89** [redphx/better-xcloud#301]
**Platform**
 - Device: TV (Noblex)
 - OS: Android
 - Browser: Kiwi Browser and Better Xcloud Web
 - Browser Version: Lastest
 - Better xCloud Version: Lastest

**Describe the bug**
When i start any Game this one runs on 15 fps and randomly can get fixed When the screen freezes like resident evil 2 where this one keeps freezing every time, i tried using 720p too but i can't fix it and i use 50 mbps of internet speed

https://github.com/redphx/better-xcloud/assets/163880555/374f85a9-44f2-46e1-ac28-a17825f35caf

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem. 
![17107754553852048255872447159081](https://github.com/redphx/better-xcloud/assets/163880555/9acadc76-6906-4387-8fe1-39d24819fb2d)

**Comment by vresade** [comment]
it's the same with me, but on windows with a delay of up to a minute

**Comment by redphx** [comment]
Probably because your device doesn't support hardware accelerated for H.264  
Chrome & Kiwi browser were build with H.264 support, but not Android WebView

**Comment by KingNothing81** [comment]
You can also check codec support with the AIDA64 app. It’s compatible with Android TV. So no need to sideload for Android TV users.

https://play.google.com/store/apps/details?id=com.finalwire.aida64

![PNG-Bild](https://github.com/redphx/better-xcloud/assets/146887651/30f48128-a436-493d-9dbc-23f0b475b7ac)

**Comment by redphx** [comment]
for hardware accelerated h.264, look for rows with "video/avc" that don't start with "omx.google"
