### ISSUE TITLE
Resolution bug

### ISSUE THREAD

**Issue by Mattterek** [redphx/better-xcloud#303]
Well... So i installed better xcloud on my **Android** device (Xiaomi Redmi Note 9) and i got problem with resolution (scretched one) so when i use **scretched resolution** in fortnite then the touch buggs and for example: when i click on **Item Shop** (in fortnite) then it just clicks on **battle pass** instead of place i clicked on please fix that i really like scretched res but it's unplayable

**Comment by redphx** [comment]
This is too complicated to fix. Just stop using one of those features.
