### ISSUE TITLE
I can't start any games.[Bug] ...

### ISSUE THREAD

**Issue by Ovelhakr** [redphx/better-xcloud#305]
**Platform**
 - Device: Phone
 - OS: Android
 - Browser: Kiwi
 - Browser Version: 124.0.6327.1
 - Better xCloud Version:3.2.4

**Describe the bug**
Any game that I open, I enter the queue when the game starts, the Xbox logo appears but the game closes and it looks like this screen.
![Screenshot_20240320-192245_Kiwi Browser](https://github.com/redphx/better-xcloud/assets/164264899/cee1c8f6-6e13-40c9-b3e6-4ebd51ab7694)

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by Ovelhakr** [comment]
I've already tried uninstalling and installing kiwi and better xcloud but it's still on this screen

**Comment by redphx** [comment]
It's xCloud bug, not Better xCloud

**Comment by Ovelhakr** [comment]
It's probably from better xcloud, if I open it from another browser or through the app it works normally

**Comment by redphx** [comment]
It's kiwi's problem. Install version 120 and try again.
