### ISSUE TITLE
Games not loading in Kiwi Browser

### ISSUE THREAD

**Issue by LukesHub** [redphx/better-xcloud#311]
**Platform**
 - Device: Phone
 - OS: Android
 - Browser: Kiwi
 - Browser Version: 124.0.6327.2
 - Better xCloud Version: 3.2.4

Every game i try to load in through Kiwi browser using better xcloud it is simply not working and everytime appers this
...
![WhatsApp Image 2024-03-21 at 12 22 45 PM](https://github.com/redphx/better-xcloud/assets/119813435/2cb1c4d7-2f52-46ed-a6bb-146f92bbfcc4)

**Comment by redphx** [comment]
Downgrade kiwi to v120 and it will work again. Or try the Better xCloud Android app.
