### ISSUE TITLE
Force console mode in Fortnite

### ISSUE THREAD

**Issue by CharlesSousaOp** [redphx/better-xcloud#318]
**I'm using:**  
- Device: Smartphone
- OS:  Android
- Browser: Kiwi Browser
  
**I want to suggest this feature:**  
...When I enable force fortnite in the console version, the fortnite mobile buttons disappear because I use xCloud on my cell phone, I wanted to suggest being able to force this mode and that the native fortnite mobile buttons remain (for those who play on cell phones), if possible. Thanks!

**Comment by redphx** [comment]
Console version doesn't have touch control
