### ISSUE TITLE
I'm correcting the text I wrote.

### ISSUE THREAD

**Issue by Ronaldes10** [redphx/better-xcloud#319]
**Platform**
 - Device: Phone
 - OS:Android
 - Browser:Kiwi
 - Browser Version:124
 - Better xCloud Version:3.3.0

**Describe the bug**
...Excuse me red, I wanted to report an error. Sometimes when pressing the run or jump button or aiming in fortnite. It always keeps changing the weapon slot. And sometimes when I press the fire button the shots don't come out. Now I'm playing on the Xbox Cloud gaming screen controller. I ask that you can correct it.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by CharlesSousaOp** [comment]
Esse erro está acontecendo no fortnite mobile/xcloud, não é por causa do script. Vá ao suporte da Epic Games para resolver o problema.

**Comment by redphx** [comment]
This is fortnite's bug
