### ISSUE TITLE
[Feature] "Parsec" style screen presenter

### ISSUE THREAD

**Issue by L4nzinhu** [redphx/better-xcloud#322]
- Device: Laptop
- OS: Windows
- Browser: Chrome
  
**Freature:**

There is an app called "Parsec" it is used to play on someone else's computer using a system based on displaying the screen.

I would like to use this in Xcloud for the new "Local Coop" update, however, when using Parsec + Xcloud, this results in lag (for obvious reasons).

So I would like this system to be added to Better Xcloud (If possible) :D

**Comment by redphx** [comment]
Not possible
