### ISSUE TITLE
[Bug] Better-XCloud sound is delayed on Chromecast w/ Google TV

### ISSUE THREAD

**Issue by francieslima** [redphx/better-xcloud#331]
**Platform**
 - Device: Chromecast 4 
 - OS: Android 
 - Browser: Kiwi
 - Browser Version: 124
 - Better xCloud Version: 0.6.1(7)

**Describe the bug**

When entering any game, the sound is choppy and with delays on the App or through the Kiwi Browser when I play via Chromecast 4 with Google TV. The Chromecast is connected to the network via Ethernet cable through a Usb-C Hub.

On my MotoG52, which I use via Wi-Fi, both through the App and Kiwi Browser, the games run very well. I suspect that the Chromecast 4 does not have the capacity to run the Better-XCloud App.

I tested the official Microsoft app, installing it via Aptoide. It ran smoother but the game freezes between a change of scenery or a CG load.

Thank you for your attention.

**Comment by redphx** [comment]
https://github.com/redphx/better-xcloud-android/issues/41
