### ISSUE TITLE
[Bug] DOOM 64 touch controls not displaying. iPhone 12 Pro.

### ISSUE THREAD

**Issue by Kode-Z** [redphx/better-xcloud#332]
Default controls load fine when selected, but the custom touch controls don't show up at all.

iPhone 12 Pro
Safari
Better xCloud version 3.3.0

**Comment by Kode-Z** [comment]
Seems to be related to after mouse/keyboard support was added to xCloud.

**Comment by Kode-Z** [comment]
Just noticed this applies to Halo Infinite too.

**Comment by Kode-Z** [comment]
![image](https://github.com/redphx/better-xcloud/assets/162533196/1952a44c-584c-4b86-bc27-39c446549970)

All these games which recently had mouse/keyboard support added have issues with touch controls. Even if you want to use the standard one, you have to select "Basic" from the touch control options to display them!

Games with custom touch controls provided by Xbox load fine.

**Comment by redphx** [comment]
You can test this one: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by redphx** [comment]
Fixed in 4.0.1
