### ISSUE TITLE
[Bug] "We are sorry..." Error After Changing User Agent to Edge

### ISSUE THREAD

**Issue by ILikePlayingGames** [redphx/better-xcloud#34]
**Describe the bug**
xCloud returns a 404 page after changing the user agent to edge on macOS due to missing `window.navigator.platform` and `window.navigator.userAgentData` values

**To Reproduce**
1. Open xCloud
2. Change user agent to edge
3. Save and reload the page

**Platform (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Safari
 - Browser Version: 16.6
- Better xCloud Version: [746e32e](https://github.com/redphx/better-xcloud/commit/746e32ecae7793b8dc6b9d339792ea01be616adc)

**Additional context**
I also encountered this issue during my testing with changing the user agent. Copying the values from Edge and loading them at document-start resolved it. xCloud appears to use these values as part of the platform detection process.

**Comment by redphx** [comment]
I also had this issue. Just refresh the page several times and it will be ok again.

**Comment by ILikePlayingGames** [comment]
Thanks, refreshing a few times did not work for me initially but I cleared the cookies, set everything up again, and it works now

**Comment by redphx** [comment]
Glad that it worked.  
FYI, this feature doesn't really change browser's User-Agent. It only changes the variable that xCloud reads from, so it doesn't affect other sites.

**Comment by ILikePlayingGames** [comment]
Thanks, that's good to know

**Comment by redphx** [comment]
Thanks for reporting. I'm gonna close this.

**Comment by ILikePlayingGames** [comment]
This issue seems to recur after changing to a different network and refreshing the page. Does this happen for you?

**Comment by redphx** [comment]
I reopened the issue. I still got it from time to time but do 1 refresh and it's gone. Maybe xCloud validates something. I need to check.

**Comment by ILikePlayingGames** [comment]
@redphx im getting it on iOS safari 16.6 for edge user agent again and it's taking 5-6 refreshes to clear. Can you please check?
