### ISSUE TITLE
[Bug] Buttons in top right don't always appear

### ISSUE THREAD

**Issue by modemman11** [redphx/better-xcloud#342]
**Platform**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Edge
 - Browser Version: 123.0.2420.65
 - Better xCloud Version: 3.4.0

Better xcloud doesn't always put the buttons on the top right of the page. The two icons in the top right for remote play and server location just don't appear. Sometimes refreshing the page multiple times is needed to get them to appear.
...

**Screenshots/Videos**
https://www.youtube.com/watch?v=mOSYeYQtScE

**Comment by redphx** [comment]
Are you using other userscripts, like no vpn?

**Comment by modemman11** [comment]
Better xcloud is the only script in tampermonkey. Only browser extension that even has access to the xbox.com domain is Ublock Origin but it's also disabled. Aside from those there should be nothing else interfering with better xcloud. No outside VPNs either.

**Comment by redphx** [comment]
Check Chrome/Edge DevTools console for error messages

**Comment by redphx** [comment]
Fixed: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by codingbutstillalive** [comment]
So, do I understand it correctly that an update to the latest script should solve the issue?
