### ISSUE TITLE
[Bug] The server button only showed up once

### ISSUE THREAD

**Issue by codingbutstillalive** [redphx/better-xcloud#344]
**Platform**
 - Device: Macbook Pro
 - OS: MacOS  Sonoma 14.4.1
 - Browser: Microsoft Edge
 - Browser Version: 123.0.2420.65
 - Better xCloud Version: Latest Version

**Describe the bug**

The button with the server name only showed up once after I had initially refreshed the page.

I then selected some of the available options. And hit refresh.

Since then, the server name button is not displayed anymore, or only sporadically.

**Steps to solve the problem**

I reinstalled Tampermonkey and the User script

**Comment by redphx** [comment]
#342
