### ISSUE TITLE
[Feature] 30FPS Limit on a Stream

### ISSUE THREAD

**Issue by skowriii** [redphx/better-xcloud#345]
**I'm using:**  
- Device: Laptop
- OS: Linux
- Browser: Google Chrome
  
**I want to suggest this feature:** An FPS limiter option in the settings that will limit the FPS of a stream to 30.

My laptop doesn't like 60 FPS. Whenever I'm streaming a game, I can play for a bit and then it starts slowing down and speeding back up every 10 seconds because my laptop can't catch up to the 60 FPS of the stream. So, it would be nice to have an option like that. If it's possible of course :)

**Comment by redphx** [comment]
#44
