### ISSUE TITLE
[Bug] Ping in stats always showing 0 in safari

### ISSUE THREAD

**Issue by evanpaul14** [redphx/better-xcloud#346]
**Platform**
 - Device: Phone
 - OS: iOS 17
 - Browser: Safari
 - Browser Version: 17 (I'm pretty sure)
 - Better xCloud Version: 3.4.0

**Describe the bug**
Ping always shows as 0 only on Safari. This happens even when I stream from outside my home or in other situations where I know the ping is more than 0.
**Screenshots/Videos**
![image](https://github.com/redphx/better-xcloud/assets/120766197/ff2a0293-f9c2-438d-9f4d-e184bb869c30)

**Comment by redphx** [comment]
Because Safari (& Firefox) doesn't provide this info

**Comment by evanpaul14** [comment]
I could've sworn it did show up at one point but I guess I was remembering wrong.

**Comment by redphx** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidatePairStats/currentRoundTripTime
