### ISSUE TITLE
[Bug] Wont let me play

### ISSUE THREAD

**Issue by Copito123ABC** [redphx/better-xcloud#347]
**Platform**
 - Device: Laptop
 - OS: Windows
 - Browser: Edge
 - Browser Version: 119.0.2151.72
 - Better xCloud Version: 3.4

**Describe the bug**
I enter xbox cloud and in the upper right corner my region does not appear, I have to restart the page so that in that corner some "???" appear, I enter options, I go to region and I do not see the options to select my region and when I try to enter the game Fortnite says "Sorry, we are working to fix the problems,   come back later" what do I do?

**Comment by TrappyTrav** [comment]
same problem

**Comment by redphx** [comment]
What do you see in chrome://extensions?
