### ISSUE TITLE
[Bug] PS4 controller not recognized and works temporarily 

### ISSUE THREAD

**Issue by Kriftt** [redphx/better-xcloud#348]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Browser Version: Newest I know that
 - Better xCloud Version: 3.4.0

**Describe the bug**
... So I play mlb the show 24 and get into the game and then randomly when I go to the menu of the game it stops working and/or very delayed. It shows two gamepads sometimes under the same name and also says vibration is on when it isnt? Then sometimes it doesnt work when i get to pitching screen and if u look it up reddit people says its cause of two controllers.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
This is either OS or browser's problem
