### ISSUE TITLE
[Feature] disable (new) xcloud kyb mouse support

### ISSUE THREAD

**Issue by DocS788** [redphx/better-xcloud#350]
**I'm using:** 
- Device: pc
- OS: windows 10
- Browser: edge

i have tried new xcloud keyboard support, but it's simply worse than betterxcloud one, i can not use "betterx "support kyb in the games that actually support the keyboard in native mode, cause it creates some conflicts .  Is it possibile to disable it and using only betterxcloud emulation ?

**Comment by btncua** [comment]
Click on profile picture > Settings > Disable "Preview features" > Refresh page.

**Comment by DocS788** [comment]
![Immagine](https://github.com/redphx/better-xcloud/assets/82037823/bca09993-27e4-4a79-a0f9-18c9d1281e88)

thanks a lot for your settings advice, but unfortunately the native keyboard put in by microsoft still exists ;(

**Comment by DocS788** [comment]
fixed!!! Thank you a lot !!!!! In the first time the option flag " preview features " was not saved, i have enabled it again and click " no " on the pop up window asking me to activate the function.

You are great
