### ISSUE TITLE
[Bug] Touch controller icon is always visible in the HUD bar although controller availability is set to “Off”

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#351]
- Device: Nvidia Shield TV
 - OS: Android TV 11
 - Better xCloud Version: 3.5.0

Although “Touch Controller” > “Availability” is set to “Off”, the touch controller icon is always visible in the stream HUD bar.

![IMG_0249](https://github.com/redphx/better-xcloud/assets/146887651/5998b315-cf5e-4215-a629-c68fe20e1bb4)

It’s there for all games, even those that don’t have native touch support (e.g. Control shown in the screenshot).

This happens in Kiwi Browser and the Android app.

I don’t know if this happens because the setting isn’t respected. Which might also affect performance in a negative way. But apart from that I also think that when “Availability” is set to “Off”, the touch controller icon should never be visible in the HUD bar.

**Comment by redphx** [comment]
It's just visual glitch. Fixed in 3.5.1
