### ISSUE TITLE
[Feature] Remove "Are you still playing?" Prompt

### ISSUE THREAD

**Issue by skowriii** [redphx/better-xcloud#354]
**I'm using:**  
- Device: Laptop
- OS: Linux
- Browser: Google Chrome
  
**I want to suggest this feature:**  
Remove the "Are you still playing?" prompt that pops up after a period of inactivity.

**Comment by skowriii** [comment]
I know but if I'm playing a game like The Quarry for example, the cutscenes in this game are long and sometimes the prompt pops up in the middle of the game, just before a QTE and I miss it and a character can die and it ruins my run.

I don't think it's that much of an ask, if not removed completely maybe add a toggle for it in the settings menu?

**Comment by redphx** [comment]
Because Better xCloud doesn't have anti-AFK measurement it's necessary to keep this message. I'd suggest building a habit of moving the sticks every once in a while while watching cutscenes.
