### ISSUE TITLE
[Bug] Guide button is not responding in remote play.

### ISSUE THREAD

**Issue by Tak-attack** [redphx/better-xcloud#355]
**Platform**
 - Device: Zenfone 10 and Steam Deck
 - OS: Android 14 and Steam OS
 - Browser: BX App v0.10.1 and Edge
 - Better xCloud Version: 3.5.0

**Describe the bug**
There was a recent update on the Insider preview xcloud site that changed the behavior of the Guide (Xbox) button.
It now opens the xcloud site interface instead of the Xbox interface within streaming.
Due to this, the guide button does not respond at all in Xbox remote play.

**Comment by redphx** [comment]
Current workaround: Use the Remote control feature in Xbox app to bring up the Guide

**Comment by redphx** [comment]
Fixed in 3.5.1
