### ISSUE TITLE
[Bug] Remote Play won't find Xbox console.

### ISSUE THREAD

**Issue by oolubayo** [redphx/better-xcloud#357]
**Platform**
 - Device: Desktop
 - OS: Mac OS
 - Browser: Chrome
 - Browser Version: 123.0.6312.107
 - Better xCloud Version: 3.5.0

**Describe the bug**
When clicking the Remote Play icon, it says: "Getting the list of consoles..." for a few seconds. And then it disappears with no list of consoles displayed. Remote play works fine on the android app, so the Xbox can be found and accessed. This also worked with no issues one week ago (Apr 1, 2024).

**Screenshots/Videos**

https://github.com/redphx/better-xcloud/assets/16298095/15181b99-ad06-408b-bd15-9fe42bc8fc38

**Comment by redphx** [comment]
I fixed it few hours ago: https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js
