### ISSUE TITLE
[Bug] Flag emoji are not displayed

### ISSUE THREAD

**Issue by btncua** [redphx/better-xcloud#359]
**Platform**
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 123.0.6312.123
 - Better xCloud Version: 3.5.1

**Describe the bug**
Flag emoji are not displayed

**Screenshots/Videos**
![01](https://github.com/redphx/better-xcloud/assets/166375403/d7907604-a3b2-4424-874f-f193a1359e7b)

![02](https://github.com/redphx/better-xcloud/assets/166375403/654d2300-cf1f-4f5c-892b-3690381137f7)

**Comment by btncua** [comment]
This extension fixes that

https://chromewebstore.google.com/detail/jhcpefjbhmbkgjgipkhndplfbhdecijh

**Comment by redphx** [comment]
Does it fix flags in region selection box?

**Comment by btncua** [comment]
![01](https://github.com/redphx/better-xcloud/assets/166375403/d8e050b4-40d5-4e90-ba22-2692ca2fd5f7)

**Comment by btncua** [comment]
I use the extension mentioned above, Windows and Chrome never fix this, so some developers use pngs instead of emoji or ready-made solutions that add Twemoji Country Flags font based on Twemoji. I am closing this issue because it is not a problem with Better xCloud script
