### ISSUE TITLE
[Bug] Android phone vibration not working

### ISSUE THREAD

**Issue by legendaddy53837** [redphx/better-xcloud#360]
**Platform**
 - Device: Blackshark 5
 - OS: android
 - Browser: Kiwi
 - Browser Version: 124..0.6327.2
 - Better xCloud Version: 3.5.1

...
After xcloud interface update, vibration of phone no longer working

**Comment by redphx** [comment]
Still working fine for me.  

Make sure this setting is on  

<img width="897" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/53be0c97-f98a-4d09-b85b-f743f9bf6fec">
