### ISSUE TITLE
response.clone.json() should be response.clone().json()

### ISSUE THREAD

**Issue by ElliotChong** [redphx/better-xcloud#361]
There is a bug here:

https://github.com/redphx/better-xcloud/blob/ec6c3fc8a39d12b297b48b63aba9646820e15c13/better-xcloud.user.js#L10472

`response.clone.json()` should be `response.clone().json()`

**Comment by Diego-Perez-Botero** [comment]
With the current code, you're getting `response.clone.json is not a function` errors ;)

**Comment by redphx** [comment]
Thank you! And sorry for making the unrelated exception logs.
