### ISSUE TITLE
Xcloud doesn't launch game with Better xcloud script 

### ISSUE THREAD

**Issue by onwei2001** [redphx/better-xcloud#365]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

124.0.6367.61

### Better xCloud Version

3.5.2

### Reproduction Steps

The game won't launch with better xcloud script. It is happening from today. It is fine in microsoft edge but the problem is on chrome. The same problem on microsoft edge beta. When I disable better xcloud script and refresh the page it will launch. It was fine 3-4 hours ago. I'm also using better xcloud no vpn script.

**Comment by redphx** [comment]
Use this https://github.com/redphx/better-xcloud/raw/main/better-xcloud.user.js

**Comment by onwei2001** [comment]
Thanks it worked
