### ISSUE TITLE
[Bug] Not working with Kiwi Browser 124.x

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#366]
### Device

Phone/Tablet

### Operating System

Android

### Browser

Kiwi Browser

### Browser Version

124x

### Better xCloud Version

All

### Reproduction Steps

If you're using Kiwi Browser 124, do either one of these to fix the problem:
- Downgrade to 123.x or older.
- Use the `Kiwi Browser v123` User-Agent profile in the script's settings.

If not you can't play the game at all.  
This is [Kiwi's fault](https://github.com/redphx/better-xcloud/issues/366#issuecomment-2081328090).

**Comment by KingNothing81** [comment]
Kiwi Browser 124.x still works for me when using a custom UA string.

So how about adding an additional “Android + Kiwi” UA profile for Kiwi users? This way people can set it and continue to use Kiwi 124.x with BXC.

That’s my current custom user agent string:

> Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.118 Mobile Safari/537.36

I just took Kiwi’s default user agent string and changed the Chrome version number. And everything is working fine again. Maybe a version number is needed here that really exists?

And for now, if other Kiwi users are reading this and want to continue using Kiwi 124.x, you could just copy und use my custom UA string.

**Comment by redphx** [comment]
This problem was caused by multiple things:

1. Kiwi Browser saying it's Chromium 124 even though it's only 122-123.  
2. In Chromium 124 they changed some API in WebRTC. Kiwi Browser didn't apply this change.  
3. The xCloud website handles things differently depends on whether you're using <= 123 or >= 124. Kiwi Browser told the website it's 124 (even though it's 123), so the stream crashed because the WebRTC API didn't act the way it should.  

That's why if you use User-Agent as <= 123 it works again.

**Comment by KingNothing81** [comment]
Thanks for the update on this. I wanted to report that this issue also exists with the new Typescript version, but I see that you already addressed this by adding a Kiwi profile.

https://github.com/redphx/better-xcloud/commit/7a79546831c040fe622b88dd7a82605db7f4893e

By the way ... I'm low on space on my device. So I'm planning to remove Kiwi. And only use the Android app in combination with sideloaded Chrome as WebView implementation. As it feels that this is giving me the best results in my case.

**Comment by phsreis** [comment]
I installed normally, Kiwi's latest version, tampermankey and xbetter, than I deleted tampermankey and xbetter worked again. The problem it's not with xbetter itself.

**Comment by phsreis** [comment]
https://youtu.be/XoO-IofbRnI?si=ebYqSyNROF-QbGm2

I don't know what I did, but it's working again.

**Comment by redphx** [comment]
Fixed in 5.1.0
