### ISSUE TITLE
[Bug] Stream crashing

### ISSUE THREAD

**Issue by Cloudplayer77** [redphx/better-xcloud#371]
### Device

Phone/Tablet

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

124.0

### Better xCloud Version

3.5.3

### Reproduction Steps

Good evening, The game does not open and a screen appears saying "we will be back soon". I tested other browsers without scripting and it worked. Does not start on the computer (edge browser).

**Comment by KingNothing81** [comment]
If you are using Edge beta, try using the stable version.

**Comment by Amiell3** [comment]
> If you are using Edge beta, try using the stable version.

The same has happened to me, edge version: 124.0.2478.51 

not a test/dev/canaryan version

https://www.youtube.com/watch?v=kJ6O6PSMNgE
https://www.youtube.com/watch?v=GjFDEm3KLLM

Better xClooud 3.5.3

cleaned cookies, login again, same effect.

Without Better xCloud works lol

**Comment by KingNothing81** [comment]
Have you both tried out the other UA profiles available? 
This sometimes helps to make things work again.

**Comment by Amiell3** [comment]
UA works perfect as default, but another as edge fail, thank u :D

**Comment by KingNothing81** [comment]
The other UA profiles are about simulating other systems and/or browsers than what you are actually using. So if you are really using Edge on Windows, there is no real reason to use the "Windows + Edge" UA profile. "Default" will use the real UA string of your installed browser. And it's recommended to always try this setting first and only change the UA profile if you have problems.
