### ISSUE TITLE
[Feature] Add a button to cast the screen to another device/TV (button similar to Youtube)

### ISSUE THREAD

**Issue by henriquemdimer** [redphx/better-xcloud#372]
### Device

Phone/Tablet

### Operating System

Android

### Browser

Kiwi Browser

### Suggestion

Add a kind of button/option that allows you to transmit the game screen to another device, such as laptop, TV, etc.

**Comment by redphx** [comment]
I don't think it's possible. Even if it does the latency will be increased a lot.
