### ISSUE TITLE
[Feature] kbm windowed mode

### ISSUE THREAD

**Issue by vresade** [redphx/better-xcloud#373]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Suggestion

an option to use the official xcloud keyboard and mouse without having to go into full screen to use it

**Comment by redphx** [comment]
The native mkb feature is designed around fullscreen mode. Need time to research more about it.

**Comment by redphx** [comment]
I was able to play in windowed mode, but you can't pause the game using the Esc key because it will also disable the MKB feature. So this feature can't be implemented.
