### ISSUE TITLE
[Bug] Crash with Edge+Windows User Agent

### ISSUE THREAD

**Issue by Galcian79** [redphx/better-xcloud#375]
### Device

Desktop

### Operating System

Linux

### Browser

Chrome/Edge/Chromium

### Browser Version

Edge/Chromium 124.0 

### Better xCloud Version

3.5.3

### Reproduction Steps

If User Agent is set to Edge+Windows the stream crashes with:

`ERROR:rtp_transceiver.cc(81)] Invalid codec preferences: invalid codec with name "AV1". (INVALID_MODIFICATION)`

Happens both with Edge and Chrome and previous versions of the script.

**Comment by jeffgedler** [comment]
I don't know if it's the same problem, but today I tried to play and when I tried to load the game, it returned me to the main menu of xbox cloud.

**Comment by KingNothing81** [comment]
Could be the same issue as here ... https://github.com/redphx/better-xcloud/issues/371

Please read my comment ... maybe it also helps in your case.
https://github.com/redphx/better-xcloud/issues/371#issuecomment-2077750053

It seems something is wrong with the "Edge + WIndows" UA profile. Maybe the browser version the UA profile uses is too outdated now and @redphx would have to modify it.

**Comment by Galcian79** [comment]
> Could be the same issue as here ... #371
> 
> Please read my comment ... maybe it also helps in your case. [#371 (comment)](https://github.com/redphx/better-xcloud/issues/371#issuecomment-2077750053)
> 
> It seems something is wrong with the "Edge + WIndows" UA profile. Maybe the browser version the UA profile uses is too outdated now and @redphx would have to modify it.

Yes that's exactly what i did.

**Comment by KingNothing81** [comment]
@Galcian79: Sorry, but do you mean that it works for you now when using the "Default" UA profile? Or is it still broken, no matter what UA profile you use?

**Comment by Galcian79** [comment]
> @Galcian79: Sorry, but do you mean that it works for you now when using the "Default" UA profile? Or is it still broken, no matter what UA profile you use?

Yes. I usually set the UA to Edge+win because some services turn into nerfed mode if they detect Linux.

**Comment by redphx** [comment]
Fixed in 4.0.0
