### ISSUE TITLE
[Bug] The app is very slow on my Mi Tv Stick 4K, the audio and video are delayed and out of sync, please fix this 

### ISSUE THREAD

**Issue by BrabuH** [redphx/better-xcloud#376]
### Device

TV

### Operating System

Android

### Browser

Other

### Browser Version

125.0.6422.14

### Better xCloud Version

0.11.0 (14)

### Reproduction Steps

When opening the app it takes time to load, the game loads slowly, and when playing the audio is delayed and out of sync.

**Comment by redphx** [comment]
https://github.com/redphx/better-xcloud-android/issues/41
