### ISSUE TITLE
Test TypeScript version

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#377]
# What is this?
It's still Better xCloud but was rewritten using TypeScript for easier maintainance.  

# What to expect when using this version
- Works on all devices: Desktop, Android, iOS...
- It should works the same way as the original script
- Have all features of the original script
- No new features

# How to install in browser
1. Install: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js
2. Disable the original script.

<img width="738" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/c5df14b2-a6cf-4aa4-a8f2-49685bc64274">

# How to test in Android app
> [!important]
> Apparently you can't install the script in the app, so ignore this for now

1. Open Settings > Click on `Better xCloud x.x.x` link to open this GitHub repo  
    <img width="458" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/d2bcffc6-44a5-4c96-8af5-f43953f3fab4">
2. Navigate to this issue
3. Clink on the link to install: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

# I found a bug. What should I do?
Please post a comment below with these info (don't create separate issue):
- Device info:
    - Script version    
    - Device name
    - Device type (Desktop/Android/iOS...)
    - Browser name + version
    - OS + version
    
- Screenshot or video record of the problem

Thanks

**Comment by btncua** [comment]
Device info:

Script version: 4.0.0-beta.1 
Device type: Desktop
Browser name + version: Chrome 124.0.6367.92
OS + version: Win 10

Unable to bind mouse Scroll Up or Scroll Down in Emulate controller whith M&K, binds Left Click instead

It works fine in version 3.5.3

Other new problems, not including those that were in version 3.5.3, I did not see

**Comment by vresade** [comment]
Device info:

Script version: 4.0.0-beta.1
Device type: Laptop
Browser name: Microsoft Edge
OS + version: Win 10

kbm emulation without linked key is causing the native keyboard and mouse to be enabled without going full screen

**Comment by redphx** [comment]
@vresade what do you mean? Which game did you test?

**Comment by BS-JI** [comment]
Script version: 4.0.0-beta.1
Device type: Android
Browser name + version: Firefox Nightly 127.0a1
OS + version: Android 14

Remote play is not working. No ship launching animation. Just black screen and no response.
Cloud play is working.

**Comment by redphx** [comment]
@BS-JI re-install and try again

**Comment by redphx** [comment]
@btncua fixed

**Comment by KyrosWeb** [comment]
Device info:

Script version: 4.0.0-beta.1
Device name: MacBook Pro M2
Device type (Desktop/Android/iOS...): macOS
Browser name + version: Chrome 124.0.6367.91
OS + version: macOS 14.4.1

I can't  adjust "clarity". It stucks on 0

**Comment by btncua** [comment]
@vresade don't use Emulate M&K and Native M&K at same time, turn off what you not use: 

- To disable Emulate M&K, go to Better xCloud settings 

- To disable Native M&K, see this: #350

**Comment by redphx** [comment]
@KyrosWeb fixed

**Comment by redphx** [comment]
4.0.0 has been released. Thanks for testing.
