### ISSUE TITLE
[Bug] Notifications won’t show up in message tray when script is enabled 

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#381]
### Device

Other

### Operating System

Android

### Browser

Kiwi Browser

### Browser Version

124.x

### Better xCloud Version

4.0.1

### Reproduction Steps

I just opened the xCloud homepage on my tablet (where I don’t use the script). And noticed that there was a little green dot beside the bell icon notifying me of pending notifications. And in my message tray there was a notification about earned trophies. But shortly before I had opened the Android app and the bell had no green dot. And my message tray looked empty.

So I opened Kiwi Browser to further investigate. And found out that when the script is enabled my message tray seems empty. But when I disable the script, the notification I saw on my tablet also shows up.

**_Script enabled = message tray seems empty_** 
![PNG-Bild](https://github.com/redphx/better-xcloud/assets/146887651/cb8b0a6b-d731-4367-9026-0b5114229802)

**_Script disabled = notification shows up_**
![PNG-Bild2](https://github.com/redphx/better-xcloud/assets/146887651/d6f7a775-fa3f-4d06-8129-c8f97e1a6c4f)

The Android app is also affected. My message tray looks empty, although there is still that an unread notification in it. 

![PNG-Bild3](https://github.com/redphx/better-xcloud/assets/146887651/afd0552a-10ea-4fbb-8b1b-917b15c69dad)

So it seems that the script is somehow “blocking” the message tray from showing pending notifications.

**Comment by redphx** [comment]
Don't use the "disable social features" setting

**Comment by KingNothing81** [comment]
But if the “disable social features” option makes the message tray non-functional, wouldn’t it be better to also hide the bell icon in that case? So it’s more obvious for the user that the message tray won’t work this way?

And I wouldn’t mind enabling social features again, if that big, ugly “search friends” box wouldn’t pop up again. Which is the main reason I keep this disabled.

![IMG_0253](https://github.com/redphx/better-xcloud/assets/146887651/a5fc0681-d8ee-4903-802f-86e7383e14a3)

So maybe you can consider always hiding the box if a user has an empty friends list. No matter if social features are disabled or not. Because that box is nothing more than a shortcut to the friends tab in the guide menu. So it always felt unnecessary to me.
