### ISSUE TITLE
[Bug] Update notification for old version

### ISSUE THREAD

**Issue by SilentException** [redphx/better-xcloud#382]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

125.0.2535.13 (Official build) beta (64-bit)

### Better xCloud Version

4.0.1

### Reproduction Steps

Open, https://www.xbox.com/en-US/play.
The Better Xcloud icon is showing new update is available. But I'm on latest version.

![image](https://github.com/redphx/better-xcloud/assets/613606/26f82119-f0ab-4113-9b27-7c8faae7ae44)
Also 4.0.1 in Tampermonkey.

**Comment by redphx** [comment]
Check again in > 2 hours. It should go away.

**Comment by SilentException** [comment]
I Ctrl+F5'd the Xcloud page and it's fine now (before it didn't help). So guess you fixed it already, thanks!
