### ISSUE TITLE
[Bug] Servers don't show

### ISSUE THREAD

**Issue by zer-oss** [redphx/better-xcloud#386]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

idk

### Better xCloud Version

4.1.2

### Reproduction Steps

An unfortunate thing occurred to me today (05/05/2024), I went to enter gamepass to play through the browser, and when I entered the site, nothing loaded, when a while passed I saw, that in the server choice settings, all available servers had disappeared. well, I changed browsers and it worked again, but I played on Microsoft edge because I already had everything of mine there, whatsapp, Youtube and among others
![WhatsApp Image 2024-05-05 at 20 05 43](https://github.com/redphx/better-xcloud/assets/68794717/6cebcf5e-319a-4b68-8006-4dd5b052abf2)

**Comment by redphx** [comment]
Does it work with 4.1.1 or older versions?

**Comment by zer-oss** [comment]
No, but thanks for the answer, you can close the ticket, the servers are
back to normal, I don't know why the bug happened, but it's back to normal,
thank you

Em dom, 5 de mai de 2024 22:20, redphx ***@***.***> escreveu:
