### ISSUE TITLE
[Bug] 720p high doesn't work

### ISSUE THREAD

**Issue by Dnmastr** [redphx/better-xcloud#387]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

109.0.1518.0

### Better xCloud Version

4.1.2

### Reproduction Steps

1.I set it to 720p high
2.open any game
3.the setting is 720p low instead of high

**Comment by redphx** [comment]
Try with latest browser version

**Comment by Dnmastr** [comment]
It didn't work, I tried using your app and it's the same thing

**Comment by KingNothing81** [comment]
Did the combination "720p + High" ever work? Because I could imagine that xCloud doesn't provide 720p resolution with the high codec profile, as it's intented for desktop PCs and Smart TVs.

What do you get with 720p when you set "visual quality" to "default" or "normal"?

**Comment by redphx** [comment]
This will be fixed in the the next version

**Comment by redphx** [comment]
Try this version: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by Dnmastr** [comment]
It worked, you're the best
