### ISSUE TITLE
[Bug] "Click to activate" popup not going away

### ISSUE THREAD

**Issue by NamelessXVI** [redphx/better-xcloud#390]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

124.0.2478.80 (Microsoft Edge)

### Better xCloud Version

4.2.0

### Reproduction Steps

After the 4.2.0 update, the option "click f8 to enable/disable the keyboard" remains on the screen even after I enable or disable the keyboard, like no mather what I do it remains on my screen.
![20240509_074828](https://github.com/redphx/better-xcloud/assets/169356087/edf0a096-cfe0-41d2-8023-e3cadc76de42)
![20240509_074805](https://github.com/redphx/better-xcloud/assets/169356087/dda27438-e6a5-45f7-8d58-d1cc4ade4e79)

**Comment by redphx** [comment]
Did you try again by refreshing the page?  
Did you test with older versions?

**Comment by NamelessXVI** [comment]
> Did you try again by refreshing the page? Did you test with older versions?

Yes, I tried to close the browser and open it again, but the problem continues. Also, the previously version of better xcloud was running perfect.

**Comment by redphx** [comment]
Check this https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by redphx** [comment]
What is the status with 4.3.0? Try other games than Fortnite as it's native MKB game, and emulated MKB won't show.

**Comment by NamelessXVI** [comment]
> What is the status with 4.3.0? Try other games than Fortnite as it's native MKB game, and emulated MKB won't show.

Yeah, the problem remains in the 4.3.0 update. I wish I could know if this is happening only with me.

**Comment by NamelessXVI** [comment]
Now, I think the problem is definitely my browser, because I made a downgrade for the 4.1.2 and 4.1.0 versions of better xcloud and the problem remains.

**Comment by NamelessXVI** [comment]
> What is the status with 4.3.0? Try other games than Fortnite as it's native MKB game, and emulated MKB won't 

> What is the status with 4.3.0? Try other games than Fortnite as it's native MKB game, and emulated MKB won't show.

I FIXED IT. I just realized that I had two tampermonkeys installed, that was the problem. Appreciate your support!

**Comment by btncua** [comment]
@redphx So all these corrections were in vain, so maybe it is worth canceling them

- #397
