### ISSUE TITLE
[Feature] Hide settings on unsupported devices

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#393]
### Device

Other

### Operating System

Android

### Browser

Chrome/Edge/Chromium

### Suggestion

Have you thought about hiding settings (sections) if they are not supported on certain devices?

For example, the MKB feature does not work on Android OS. So how about just hiding the "Keyboard & Mouse" section on Android?

And on Android TV you can't use touch control. So you could also hide the "Touch Controller" section there.

Or if this is more easy to do, how about hiding those settings for users that have set a smart TV profile?

P.S.: I saw that with the new Game Bar you are hiding the touch controller icon on devices without touch support. But how opening the Game Bar in the first place without touch support? I also liked that it was possible to completely disable the screenshot button, as I don't use that feature. So maybe you can also consider to make the Game Bar just optional.

**Comment by redphx** [comment]
- I thought about having different builds for each type of devices, but refused doing so. In current version I already put a message explain why the MKB feature didn't work on mobile and they didn't bother to read. Removing it entirely gonna makes the problem worse. I don't have time to answer that question again and again.

- The touch controller button visible on non-touch devices is a bug.

**Comment by KingNothing81** [comment]
> * I thought about having different builds for each type of devices, but refused doing so. In current version I already put a message explain why the MKB feature didn't work on mobile and they didn't bother to read. Removing it entirely gonna makes the problem worse. I don't have time to answer that question again and again.

Ok, that’s totally understandable. So let’s close this again.

> * The touch controller button visible on non-touch devices is a bug.

No, sorry. You misunderstood. The touch controller button is hidden as intended on my Shield TV. So there is no bug to fix. 

But you need touch support (or a mouse) to bring up the game bar and push the buttons. So it won’t be very useful on non-touch devices. And don’t you think that some touch users might trigger it accidentally sometimes? So I’m thinking that maybe the game bar shouldn’t be enabled by default for all users if there is no option to disable it.
