### ISSUE TITLE
[Bug] KBM not working.

### ISSUE THREAD

**Issue by TornadoRTX** [redphx/better-xcloud#394]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

124.0.6367.201

### Better xCloud Version

4.20

### Reproduction Steps

1. Opening a game such as Fortnite.
2. Loading in.
3. The the popup saying KBM is available doesn't show up while KBM is turned on. Trying to press F8 doesn't work either.
(Video can't send because it's too big of a file size)

**Comment by redphx** [comment]
Test this version: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

Fornite supports native MKB.
