### ISSUE TITLE
[Feature]  smaller script

### ISSUE THREAD

**Issue by jvpoke** [redphx/better-xcloud#395]
### Device

Other

### Operating System

Android

### Browser

Other

### Suggestion

It is possible to make a smaller version with only one language option, English or only with high bitrate and co-op mode, preferably lower than 280kbps, use for a browser where the maximum size is this

**Comment by redphx** [comment]
Which browser has this limitation?

**Comment by jvpoke** [comment]
berry browser, as it is a very specific use it is not necessary that much dedication, it is better to try and ask

**Comment by redphx** [comment]
Sorry but this will take a lot of work
