### ISSUE TITLE
[Bug] Emulated MKB not working in Fortnite

### ISSUE THREAD

**Issue by gusttaaq** [redphx/better-xcloud#396]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

124.0.2478.97 

### Better xCloud Version

4.3.0

### Reproduction Steps

The keyboard and mouse feature doesnt work on fortnite
![image](https://github.com/redphx/better-xcloud/assets/157085502/00fcb690-f0d3-499e-a24f-b1f420561fd2)
![image](https://github.com/redphx/better-xcloud/assets/157085502/47f489ef-3481-4dd2-a3f0-7ad67c9e765d)

**Comment by redphx** [comment]
Emulated mkb will be disabled in native mkb games. Fortnite is one.

**Comment by btncua** [comment]
- @gusttaaq Do you have Native M&K disabled? : #350

**Comment by gusttaaq** [comment]
yeah the xcloud mk is disabled, the xcloud mk only works in preview features and im not on preview

**Comment by btncua** [comment]
I'm using [4.2.0](https://github.com/redphx/better-xcloud/releases/tag/v4.2.0) until  @redphx  fixes it 

- #397

**Comment by gusttaaq** [comment]
im using that version too

**Comment by redphx** [comment]
Install this version and disable native MKB in the settings: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by gusttaaq** [comment]
thxxxxxxxxxxxxxxxxxxxxxxx, you do the best work i ever seen in my life, you're great man
