### ISSUE TITLE
[Bug] Emulate M&K does not work even when Native M&K is completely disabled

### ISSUE THREAD

**Issue by btncua** [redphx/better-xcloud#397]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

124.0.6367.202

### Better xCloud Version

4.3.0

### Reproduction Steps

- Emulate M&K does not work even when Native M&K is completely disabled #350 Everything worked fine in [4.2.0](https://github.com/redphx/better-xcloud/releases/tag/v4.2.0)

**Comment by redphx** [comment]
Install this version and disable native MKB in the settings: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by btncua** [comment]
@redphx Thanks, it works fine now

**Comment by btncua** [comment]
@redphx It works fine only if "Previous Features" is disabled, but when you enable this and enter game, after activating Emulate M&K, mouse grabs and shows cursor in game, even though Native M&K is disabled in Better xCloud settings

**Comment by redphx** [comment]
Fixed https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by btncua** [comment]
@redphx Thanks again for your work
