### ISSUE TITLE
[Feature] Ability to completely disable Native M&K

### ISSUE THREAD

**Issue by btncua** [redphx/better-xcloud#398]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Suggestion

- Ability to completely disable Native M&K or block it. This is to avoid turning it off manually: #350, also preempting: if Native M&K goes beyond "Previous Features". It is also suitable for those who want to use other functions from "Previous Features" but do not need (don't like) Native M&K. I would suggest doing this as a toggle or completely disable when Emulate M&K is enabled

**Comment by redphx** [comment]
Install this version and disable native MKB in the settings: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by btncua** [comment]
@redphx Thanks, this will provide a choice of control method for most players
