### ISSUE TITLE
[Bug] I used to be able to play on a chromebook and now I can't.

### ISSUE THREAD

**Issue by Limon003** [redphx/better-xcloud#400]
### Device

Laptop

### Operating System

Other

### Browser

Chrome/Edge/Chromium

### Browser Version

124.0.6367.154 (Build oficial) (64 bits)

### Better xCloud Version

4.3.0

### Reproduction Steps

When i open fortnite the pop up to activate the emulator it dsnt appear, and i when i use the F9 key it dsnt work too.
I play on a chromebook, i used to be able to play on it.
Yesterday I was playing Fortnite and in the middle of the game session the emulator stopped, I was not able to play again

**Comment by Rnt05** [comment]
I have the same problem!

I tested it with other games (online and offline) too, it only happens with Fortnite

**Comment by Limon003** [comment]
> Rnt05

The only solution I have found so far is to go back to the previous version of xcloud better, although you have to keep an eye on it because it automatically updates to the current version, so you have to be going back to the previous version manually from time to time
This is the link from the previous version:
https://github.com/redphx/better-xcloud/releases/tag/v4.2.0
When you click the link, scroll down and click on bette-r-xcloud.user.js
![Screenshot 2024-05-15 12 14 36 AM](https://github.com/redphx/better-xcloud/assets/169712668/6abad9fd-e397-43bc-80c8-4a7df7e16e63)
Then click on that buttom (The "reinstall" button will not appear for you, it appears for me because I already have that version)
![Screenshot 2024-05-15 12 14 48 AM](https://github.com/redphx/better-xcloud/assets/169712668/57afd1ad-38ea-4b3c-ae45-e1cb26b45dff)

**Comment by btncua** [comment]
- @Rnt05 @Limon003 you can disable script auto-update in tampermonkey settings, you can also undo any fixes made by @redphx in last update, in Editor script

**Comment by Limon003** [comment]
> * @Rnt05 @Limon003 you can disable script auto-update in tampermonkey settings, you can also undo any fixes made by @redphx in last update, in Editor script

Ohhhh tyms

**Comment by redphx** [comment]
Install this version and disable native MKB in the settings: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js
