### ISSUE TITLE
[Feature] Extended key bindings (M&K)

### ISSUE THREAD

**Issue by Haisom** [redphx/better-xcloud#401]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Suggestion

Would be nice if we could bind the same key to more than one button in case they don't conflit with each other during gameplay.

Also, having modifiers for quick range changes on the Axis, AKA holding Shift would make Left Analog range decrease to 50 or 25% (Customizable if possible) making your character walk instead of run.

Plus, would be great if we could have access to the "file" of the mapping, so more advanced users could customize it their own way indepth on the coding side, like most console emulators works nowadays, allowing us to setup modifiers that would allow a partial mapping change. And not only that, this would allow us to save, export and share the mapping.

That would be useful in games like AC where you want to have your melee attacks and ranged attacks both mapped to your mouse. 

Also, maybe a third row for binding, allowing us to bind up to 3 keys per button instead of 2. Is that possible?

**Comment by redphx** [comment]
This is too complicated and out of scope. Please use third-party app like reWASD.
