### ISSUE TITLE
[Bug] Newer versions not working

### ISSUE THREAD

**Issue by UnwelcomeVariation** [redphx/better-xcloud#402]
### Device

Laptop

### Operating System

Other

### Browser

Chrome/Edge/Chromium

### Browser Version

124

### Better xCloud Version

4.3.0

### Reproduction Steps

The newer versions of Better Xcloud don't seem to work on my Chromebook. I click on the games and it does nothing. 

I have to use 1.11 to even get it to work at all. I'm assuming this has something to do with my Laptop being ancient but I figured i'd try anyways.

**Comment by redphx** [comment]
Does it work with Bx turned off?  Check Console tab of Chrome DevTools for error logs: https://developer.chrome.com/docs/devtools/

**Comment by UnwelcomeVariation** [comment]
Sorry I'm pretty new to this, how exactly would I go about turning that off?

**Comment by redphx** [comment]
Turn it off in the Tampermonkey dashboard

**Comment by UnwelcomeVariation** [comment]
Only two errors I got are.

userscript.html?name=Better-xCloud.user.js&id=fa6e000a-e6a8-492b-82ff-f1b5b833f369:10772 Uncaught ReferenceError: structuredClone is not defined
    at set (userscript.html?name=Better-xCloud.user.js&id=fa6e000a-e6a8-492b-82ff-f1b5b833f369:10772)
    at play:246

and

[Intervention] Blocked call to navigator.vibrate because user hasn't tapped on the frame or any embedded frame yet: https://www.chromestatus.com/feature/5644273861001216.

**Comment by redphx** [comment]
`structuredClone is not defined`. This is most likely because something's wrong with your browser. If you're really using Chrome 124 then it should work.

**Comment by UnwelcomeVariation** [comment]
Strange i'll try reinstalling chrome then.
