### ISSUE TITLE
no popup for keyboard an mouse

### ISSUE THREAD

**Issue by Drxlrt** [redphx/better-xcloud#403]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

Version 127.0.2594.0 (Official build) canary (64-bit)

### Better xCloud Version

website version 24.7.43

### Reproduction Steps

i open better xcloud and try to use keyboard and mouse and it doesnt show any popup so i cant use keyboard and mouse

**Comment by redphx** [comment]
Duplicate #397
