### ISSUE TITLE
[Bug] Game crashes when trying to buy stuffs

### ISSUE THREAD

**Issue by theguythatdidsomething** [redphx/better-xcloud#404]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

all vercions fail

### Better xCloud Version

all vercions fail

### Reproduction Steps

go on flight simulator and try buying plane on marketplace game crashes when game prompts warning of buying

**Comment by redphx** [comment]
Test without better xcloud
