### ISSUE TITLE
[Feature] Adding extra buttons for emulated KBM like if we had paddles on a controller.

### ISSUE THREAD

**Issue by TornadoRTX** [redphx/better-xcloud#407]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Suggestion

I would like to suggest that we could add extra keys to emulated KBM, like if we had paddles on a controller. This would allow for so much more extra customizability. Many people including myself that play competitive games would really enjoy extra buttons, and if we didn't want them, we could just unbind it.

**Comment by redphx** [comment]
What do you mean? Can you just map it to another key?

**Comment by btncua** [comment]
@AryanGamez1 paddles are simply an alternative to pressing a button that is already on controller. It doesn't add any other buttons. So what you're asking is simply not possible in controller itself, plus emulation already has ability to bind two M&K keys to one controller button, so it's actually a function performed by paddles on controller
