### ISSUE TITLE
[Feature] Controller Shortcut To Refresh The Stream (or to "Three Dot Menu")

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#408]
### Device

Other

### Operating System

Android

### Browser

Chrome/Edge/Chromium

### Suggestion

I'm very happy to see that the controller shortcuts will return soon. So good to have a controller with a home button now. =)

And for a future release I wanted to suggest to also add a controller shortcut that let's you refresh the stream / trigger a reconnect. 

Or maybe even better, a shortcut that will open the "three dot menu". Like this there would be direct way to the new refresh button you added there recently. And users would also be able to have a quick look at the stream badges to check resolution, codec, etc..

Thanks.

**Comment by redphx** [comment]
Available in the beta version

![telegram-cloud-photo-size-5-6235255387020442106-y](https://github.com/redphx/better-xcloud/assets/96280/85dd4f2c-ba3e-4ca0-b57d-1a05ac1bbd34)
