### ISSUE TITLE
[Feature] Lower bitrate setting

### ISSUE THREAD

**Issue by adnan-void** [redphx/better-xcloud#410]
### Device

Phone/Tablet

### Operating System

Android

### Browser

Kiwi Browser

### Suggestion

Can you please allow to change bit rate below 1Mb. currently we can only jump between 1Mb while setting bitrate. Please allow the opion to set variable bit rate for example i get better lag free stream when my bit rate is between 100kb-200kb but when it imcrease from that the stream gets laggy. please consider this feature as it will imporve the streaming experince on lower bandwidth.

**Comment by redphx** [comment]
Added in 4.6.0, but don't expect the bitrate value will be always lower than the max value. Even you set 0.1Mb/s, the bitrate most of the time will be higher than that.

<img width="463" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/63301a52-bfef-42aa-b0d6-d07f101c6185">
