### ISSUE TITLE
[Bug] Game not in full screen

### ISSUE THREAD

**Issue by btncua** [redphx/better-xcloud#415]
### Checklist

- [X] I will only use English in my report.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Device

Desktop

### Operating System

Windows

### Browser Version

Chrome 125.0.6422.113

### Better xCloud Version

4.6.1

### Game list

Fortnite

### Reproduction Steps

Game not in full screen when open it, work fine on [4.6.0](https://github.com/redphx/better-xcloud/releases/tag/v4.6.0)

### Screenshot/video

https://github.com/redphx/better-xcloud/assets/166375403/3afa851e-0502-4b6c-a6a1-767da5388946

**Comment by btncua** [comment]
Also, rocket animation is still displayed even if "Always hide" is selected in Better xCloud settings (this can be seen in the video before starting the game)

![2024-05-30_121233](https://github.com/redphx/better-xcloud/assets/166375403/ccb662e8-916c-4216-bc95-c8eea78a37f4)

Does this option hide it not completely or is it other animation that cannot be hidden?

**Comment by redphx** [comment]
Fixed https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by btncua** [comment]
@redphx Thanks, I tested it, works fine now. Rocket animation is also gone
