### ISSUE TITLE
[bug] TV TCL jeep flashing screen.

### ISSUE THREAD

**Issue by Jhonmaic** [redphx/better-xcloud#419]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [x] The bug doesn't happen when I disable Better xCloud script.
- [x] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

Tv TCL 

### Operating System

Android 10

### Android app/Browser Version

Android app

### Better xCloud Version

4.7.1

### Game list

ALL games 

### Reproduction Steps

The games in the better xcloud app on TCL TV keep flashing the screen and blocking the transmission, making it impossible to play, is there any solution?

**Comment by redphx** [comment]
https://github.com/redphx/better-xcloud-android/issues/41
