### ISSUE TITLE
[Bug]  Remote Play not working

### ISSUE THREAD

**Issue by Moskus** [redphx/better-xcloud#421]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Surface Laptop Studio

### Operating System

Win11

### Android app/Browser Version

Edge 125 (latest)

### Better xCloud Version

4.7.1

### Reproduction Steps

I can't connect to my Xbox Series X (Remote Play) when I'm actually remote. This works in the Xbox app, but not in the browser using Better xCloud. When I'm home, it works, but not when I'm remote.

I've forwared [these ports](https://www.reddit.com/r/xboxone/comments/js6j9p/i_found_the_ports_needed_for_remote_play/), which at least helps with the Xbox app.

**Comment by redphx** [comment]
https://github.com/redphx/better-xcloud/issues/434
