### ISSUE TITLE
[Feature] disable "type text" popup on kbm

### ISSUE THREAD

**Issue by vresade** [redphx/better-xcloud#422]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Suggestion

an option to disable the "type text" popup when playing on keyboard and mouse

**Comment by btncua** [comment]
@vresade another feature suggestion from category: "What's this for?" Just don't click on text input field in game and you'll never see this popup again

**Comment by redphx** [comment]
What game? Native or emulate? Video?

**Comment by vresade** [comment]
> @vresadeoutra sugestão de recurso da categoria: "Para que serve isso?" Apenas não clique no campo de entrada de texto do jogo e você nunca mais verá esse pop-up

every time i do this it always opens the popup

**Comment by vresade** [comment]
> Que jogo? Nativo ou emular? Vídeo?

fortnite using native support and have no problem with video

**Comment by btncua** [comment]
@vresade  você não poderá inserir o número da sua ilha Fortnite sem esse popup e, supondo que o Better xCloud o implemente, não faria sentido porque você não poderá inserir nada de qualquer maneira, se não quiser ver isso popup, apenas não interaja com o campo de entrada de texto do jogo. Além disso, @redphx 
 solicitou um vídeo ou captura de tela do que você deseja desativar, não de problemas de vídeo.

Sorry @redphx  that it's not in English, it will be easier for him to understand

**Comment by vresade** [comment]
> @vresade você não poderá inserir o número da sua ilha Fortnite sem esse popup e, supondo que o Better xCloud o implemente, não faria sentido porque você não poderá inserir nada de qualquer maneira, se não quiser ver isso popup, apenas não interaja com o campo de entrada de texto do jogo. Além disso, @redphx solicitou um vídeo ou captura de tela do que você deseja desativar, não de problemas de vídeo.
> 
> Sorry @redphx that it's not in English, it will be easier for him to understand

![image](https://github.com/redphx/better-xcloud/assets/107950091/96d40e70-5596-4f1b-9e98-7bbde267f337)

**Comment by btncua** [comment]
@vresade  repeti o momento e agora entendo do que você está falando, mas esse recurso deve ser implementado exclusivamente para controles nativos, já que o input funciona sem a necessidade de usar pop-ups do Xbox para digitar, mas não funcionará na emulação, já que essas janelas são a única maneira de inserir texto para emulação

https://github.com/redphx/better-xcloud/assets/166375403/06eed27b-44c0-4b15-a321-540ae9a43a4a

Claro, se o  @redphx  puder implementá-lo exclusivamente para nativos

**Comment by btncua** [comment]
@redphx  if you can implement this feature only for native controls as input works without having to use xbox popups for input and those windows are just an alternative (I showed how it works in the video) but it won't work in emulation because these windows are the only way to enter text for emulation

**Comment by redphx** [comment]
It's still a Xbox game even when playing with MKB, and you can't input text directly. You can't change that behavior.
