### ISSUE TITLE
[Feature] Game bar and settings on Android TV

### ISSUE THREAD

**Issue by skttbv** [redphx/better-xcloud#423]
### Device

TV

### Operating System

Android

### Browser

Other

### Suggestion

I use Better xCloud apk on my Nvidia Shield TV an I can't or I don't know how to open the Game bar with the Shield or the Xbox controller. Is there any way to do this or it is not implemented yet?

Thanks in advice

**Comment by redphx** [comment]
Use the Controller shortcuts feature
