### ISSUE TITLE
[Bug] No option to turn on Native Mouse & Keyboard in Kiwi

### ISSUE THREAD

**Issue by LK-0** [redphx/better-xcloud#424]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [x] xCloud officially supports my country/region.
- [x] The bug doesn't happen when I disable Better xCloud script.
- [x] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Phone/Tablet

### Device

Moto e22

### Operating System

Android 12

### Android app/Browser Version

kiwi versão 124.0.6327.4

### Better xCloud Version

5.0.0

### Reproduction Steps

Trying to use

### Screenshot/video

Doesn't appear to activate native mouse and keyboard
![Screenshot_20240622-104245](https://github.com/redphx/better-xcloud/assets/173553426/86e8c93c-f8f1-42e3-85a8-1a43ca14eb26)

**Comment by redphx** [comment]
Android app only

**Comment by LK-0** [comment]
I'm going to test, I'll be right back

**Comment by LK-0** [comment]
@redphx It doesn't read the keyboard, only the mouse

**Comment by LK-0** [comment]
The app also doesn't recognize something for me to be able to fix thisO aplicativo não reconhece também
