### ISSUE TITLE
[Feature] Possibility to use logitech g29

### ISSUE THREAD

**Issue by giovanit** [redphx/better-xcloud#425]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Suggestion

Add a function to enable the use of the Logitech G29 steering wheel

**Comment by redphx** [comment]
Test it in https://hardwaretester.com/gamepad  

If you can test it, do a screen record.  
If not, nothing I can do.

Edit: it may be possible using [WebHID](https://developer.mozilla.org/en-US/docs/Web/API/HID) and https://github.com/nightmode/logitech-g29, but since I don't have the device I can't test it.

**Comment by GopherTheCoder** [comment]
Tested with my G920 Xbox, in Edge, inputs can be received, but definitly need some remapping.
![image](https://github.com/user-attachments/assets/6330fb22-7a16-486f-8ab4-a755a0a484e4)
![image](https://github.com/user-attachments/assets/41099b6c-3f94-41c5-8db3-6a6a63efdc6e)
B0:A B1:B B2:X B3:Y B4:Right paddle B5:Left paddle B6:Menu B7:View B8:RSB B9:LSB B10:Home
B11\~B17 No response, maybe mapped to a gear shift which I don't have.
AXIS0: Wheel, turning right(clock-wise) is positive.
AXIS1: Throttle AXIS2: Brake AXIS5: Clutch These three paddles are mapped from 0~100 to 1.0~-1.0
And the most weird, Dpad is mapped to AXIS9, default value is 1.28571, ↑:-1.0 ↓:0.14286 ←:0.71429 →:-0.42857

The Throttle(AXIS1) seems to be recognized as left stick Y, cause in xbox.com/play, the selector keep scrolling down, same behaviour is observed when I open better-xcloud menu. I get into Forza Horizon 5(with mouse), there apears to be same mapping in-game.

**Comment by GopherTheCoder** [comment]
So I guess all we need is just #169 then.

**Comment by Jedibuji** [comment]
I was wondering if a wheel would work or not. I've been really enjoying being able to play Forza M on mobile with rumble feedback it's finally playable.

**Comment by redphx** [comment]
Try the new button mapping feature in 6.1  
If it still doesn't work then I can't do anything.
