### ISSUE TITLE
[Bug] xcloud page reloading endlessly saying there was an error saying it couldn't try to run better xcloud

### ISSUE THREAD

**Issue by vresade** [redphx/better-xcloud#426]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

laptop

### Operating System

Windows 10

### Android app/Browser Version

Chrome 126

### Better xCloud Version

3.5.0

### Reproduction Steps

well i don't know if this is a bug in my browser or tampermonkey but now every time i open xcloud it always restarts the page saying that there was an error executing the tampermonkey userscript i've tried updating my browser even trying chrome to see if it would fix the error and when i went to open xcloud the same thing happened i don't know what else i can do to fix thiswell i don't know if this is a bug in my browser or tampermonkey but now every time i open xcloud it always restarts the page saying that there was an error executing the tampermonkey userscript i've tried updating my browser even trying chrome to see if it would fix the error and when i went to open xcloud the same thing happened i don't know what else i can do to fix this

**Comment by btncua** [comment]
@vresade  reinstall Tampermonkey and Better xCloud using latest version [5.0.0](https://github.com/redphx/better-xcloud/releases/tag/v5.0.0), also are you using any other  extensions or scripts on your browser?

**Comment by redphx** [comment]
take a screenshot of chrome://extensions

**Comment by vresade** [comment]
> @vresade reinstale o Tampermonkey e o Better xCloud usando a versão [5.0.0](https://github.com/redphx/better-xcloud/releases/tag/v5.0.0) mais recente . Você também está usando alguma outra extensão ou script em seu navegador?

after I reinstalled tampermonkey and better xcloud the bug was fixed
