### ISSUE TITLE
[Bug] Script doesn't load properly

### ISSUE THREAD

**Issue by ShacoDelusions** [redphx/better-xcloud#428]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

positivo bgh portatil

### Operating System

winterOs

### Android app/Browser Version

Chrome

### Better xCloud Version

5.0.1

### Game list

todos

### Reproduction Steps

Upon entering the xbox.com page, it says: "better xcloud cannot be run, retrying." The page reloads and leads to one that says the requested page cannot be found. And so on continuously, better xcloud no longer runs and the page only works when I disable it in Tempermonkey.

### Screenshot/video

![image](https://github.com/redphx/better-xcloud/assets/174159777/0601151c-c34e-4d1d-bca4-596222f3688d)

**Comment by btncua** [comment]
- #426

**Comment by btncua** [comment]
- @ShacoDelusions reinstall Tampermonkey and Better xCloud, also send screenshot of chrome://extensions

**Comment by KingNothing81** [comment]
Maybe current version of Tampermonkey now needs "Developer Mode" enabled in the extension settings to continue to work? That's something they anounced on their website.

**Comment by ShacoDelusions** [comment]
![image](https://github.com/redphx/better-xcloud/assets/174159777/afc103ac-afb3-4f65-98f8-85bb0d35ebc3)
The error still continues, I reinstalled tempermonkey and better xcloud in an old version and the error still persists, I tried many previous versions of better xcloud, the extensions section is also in developer mode

**Comment by ShacoDelusions** [comment]
![image](https://github.com/redphx/better-xcloud/assets/174159777/6e72182c-526a-4e93-9fb1-9bc2fbc4342c)
I'm just on the version that "didn't have that problem" and it still doesn't work, I'm thinking that maybe it could be the tempermonkey version. Anything I can do to solve it?

**Comment by KingNothing81** [comment]
What's your Chrome version?

If it's Tampermonkey, you could try to downgrade by using "Tampermonkey Legacy":
https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn

**Comment by btncua** [comment]
I tested it, Better xCloud works fine on Tampermonkey version [5.1.1](https://www.tampermonkey.net/faq.php#Q408), but not on latest 5.2.1. Tested on Chrome version 126.0.6478.127

**Comment by redphx** [comment]
Try this: https://github.com/Tampermonkey/tampermonkey/issues/2086

**Comment by btncua** [comment]
On Tampermonkey BETA also does not work, failed to run Better xCloud, constantly

**Comment by redphx** [comment]
Tested on Chrome 126.0.6478.127, Tampermonkey 5.2.1 and it still works for me

**Comment by redphx** [comment]
This is an issue with Tampermonkey, not Better xCloud.  
However another user reported a possible solution [here](https://github.com/redphx/better-xcloud/issues/473#issuecomment-2266200663).

**Comment by btncua** [comment]
> Try this: [Tampermonkey/tampermonkey#2086](https://github.com/Tampermonkey/tampermonkey/issues/2086)

@redphx I tested it now option `UserScripts API Dynamic`, (which didn't work before), now works for me on latest version Tampermonkey and Better xCloud starts up fine, looks like they've fixed something, but still need to enable this option manually
