### ISSUE TITLE
[Bug] Remote Play black screen on local network

### ISSUE THREAD

**Issue by justinrhodes** [redphx/better-xcloud#431]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

MacBook Pro

### Operating System

macOS

### Android app/Browser Version

Google Chrome

### Better xCloud Version

5.1.0

### Reproduction Steps

1. Open Google Chrome
2. Go to xCloud website
3. Click Remote Play Icon in top right corner and connect to local Xbox Series X
4. View Xbox startup screen with sound
5. Black screen for ~15-20 seconds
6. Error screen flashes before returning to main xCloud home page.

This workflow was working for me fine a few days ago on the same network, xbox.

### Screenshot/video

<img width="701" alt="Screenshot 2024-07-01 at 11 32 12 AM" src="https://github.com/redphx/better-xcloud/assets/1434210/243809eb-8779-4bdc-b2b5-94cfc89772d0">

**Comment by justinrhodes** [comment]
My iPhone using the Xbox app does not have this issue. I'm able to use Remote Play without issue.

**Comment by redphx** [comment]
Restart Xbox. If it doesn't work, check https://github.com/redphx/better-xcloud/issues/434  

Xbox app uses different method so it can't be compared.

**Comment by justinrhodes** [comment]
@redphx I took a look, but that one seems to be about using a different network. I'm on the same network in this situation.
