### ISSUE TITLE
[Bug] WebGL2 consumes all CPU resources

### ISSUE THREAD

**Issue by heximing** [redphx/better-xcloud#433]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

i5-13600K + Intel Arc A750 + 64GB memory

### Operating System

Windows 10 22H2, OS build 19045.4529

### Android app/Browser Version

Chrome Version 126.0.6478.127 (Official Build) (64-bit)

### Better xCloud Version

5.1.1

### Game list

Octopath Traveler II

### Reproduction Steps

Using `WebGL2` (either `Unsharp masking` or `AMD FidelityFX CAS`) consumes all CPU resources.
I took a video of the whole Reproduction Steps (because GitHub limited attachment < 10MB, I made the video 2x speed).

### Screenshot/video

https://github.com/redphx/better-xcloud/assets/541861/2ff78398-08b9-427c-ad30-62b1070aaee2

**Comment by btncua** [comment]
Same with me, I just don't use it

**Comment by redphx** [comment]
Visit `chrome://gpu` and share the report file

**Comment by btncua** [comment]
[about-gpu-2024-07-03T09-33-14-896Z.txt](https://github.com/user-attachments/files/16081664/about-gpu-2024-07-03T09-33-14-896Z.txt)

**Comment by btncua** [comment]
Also, input delay increases significantly

**Comment by KingNothing81** [comment]
The WebGL2 renderer also doesn't work well on the Shield TV (Android TV 11). Using it, the stream gets very choppy. Like frames are constantly dropped. So I also can't use it. But maybe it's just another "too old Android OS" issue.

**Comment by redphx** [comment]
- Do you have the same problem on this page: https://www.shadertoy.com/view/ftsXzM  
- Try enabling the `ignore-gpu-blocklist` flag: `chrome://flags/#ignore-gpu-blocklist`

**Comment by heximing** [comment]
`chrome://gpu` report files: [about-gpu-2024-07-10T01-33-07-006Z.txt](https://github.com/user-attachments/files/16153889/about-gpu-2024-07-10T01-33-07-006Z.txt)

Either enabling `ignore-gpu-blocklist` or default (disable) will cause the same problem:
![2024-07-09_213339](https://github.com/redphx/better-xcloud/assets/541861/d44150e9-4b19-41ec-a788-332e27fc0680)

**Comment by redphx** [comment]
Looks like you have a similar problem on shadertoy. Rendering 640x360 uses 40% of CPU.

**Comment by KingNothing81** [comment]
I also tried to enable the "ignore-gpu-blocklist" flag with the WebView Dev Tool to see if it makes a difference. But the "WebGL2" renderer continues to give me a very choppy stream. Even with "Sharpness = Off". And no matter if using the "Android System WebView" or "Chrome Stable" as implementation. 

But I don't have any performance issues with the default renderer. I just wanted to give "AMD FidelityFX CAS" a try. So I wanted to ask: Was it a decision or is "AMD FidelityFX CAS" just not possible with the default renderer? Because it feels that the performance on my device might be strong enough to handle it. And maybe this would also solve the "cosuming CPU resources" problem for the other users.

**Comment by redphx** [comment]
Try this setting in 5.4.1. It was set to "High performance" in previous versions.  

<img width="403" alt="Screenshot" src="https://github.com/user-attachments/assets/9dfdb2de-6236-4799-bcf8-629d527eaa5d">

**Comment by heximing** [comment]
`WebGL2` will consume all CPU resources regardless GPU configuration is `Default`, `High performance`, or `Low power`.
When using `WebGL2`, the game play is very laggy. Using default renderer is very smooth.
Please check the video. (because GitHub limited attachment < 10MB, I made the video 2x speed).

https://github.com/user-attachments/assets/5653f057-dbad-48d6-a810-7a6a75a62daa

**Comment by redphx** [comment]
Please try with Firefox

**Comment by Regnuss** [comment]
Tried Firefox on Steam Deck OLED, runs way better BUT it locks at 90fps instead of 60fps (OLED 90hz) which causes stutter because of uneven fps/hz. 

The Steam Deck gets quite hot/loud + uses >12w instead of 7w. The CPU runs at max speed and quite hot (3.5GHz/ 71°-80°), which is not good for streaming.

**Comment by KingNothing81** [comment]
I think many users only want to set the WebGL2 renderer because they want to use "AMD CAS". But if using WebGL2 even decreases performance, why not allow people to also try out "AMD CAS" with the default renderer? Or is this impossible as it can't work without WebGL2?

**Comment by redphx** [comment]
Try to find this line in the script, replace `webgl2` with `webgl`

```js
// From
const gl = this.#$canvas.getContext("webgl2", {

// To
const gl = this.#$canvas.getContext("webgl", {
```

No, AMD CAS can't be implemented in default renderer.

**Comment by KingNothing81** [comment]
> No, AMD CAS can't be implemented in default renderer.

Ok, thanks.

> Try to find this line in the script, replace `webgl2` with `webgl`
> 
> ```js
> // From
> const gl = this.#$canvas.getContext("webgl2", {
> 
> // To
> const gl = this.#$canvas.getContext("webgl", {
> ```

I don't know if this for me or also for the other users having problems with WebGL2, but I don't know how I would be able to get that modified script into the Android app. So maybe the others can give this a try.

For most games I don't want to use "Clarity Boost" anyway. But some games appear very blurry. But I think I will just stick to "unsharp masking" in those cases.

**Comment by redphx** [comment]
Tested on Steam Deck, both Win10 and SteamOS 3.5, and didn't run into this problem

**Comment by heximing** [comment]
> Tested on Steam Deck, both Win10 and SteamOS 3.5, and didn't run into this problem

I also tested today with the same computer same Windows 10 system same browser, with the newest 5.7.3 version. Everything is the same. Using WebGL2 still consumes all CPU resources. Here is the video I just recorded:

https://github.com/user-attachments/assets/0a5847b4-2ae8-453b-a1b8-96ff7dfcbcb7

**Comment by redphx** [comment]
I still believe this is caused by your GPU. Chrome is using CPU and not GPU to render the video. Try to update the driver and check GPU's settings.

**Comment by heximing** [comment]
> I still believe this is caused by your GPU. Chrome is using CPU and not GPU to render the video. Try to update the driver and check GPU's settings.

Issue identified. I turned OFF `Use graphics acceleration when available` in Chrome.
You reminded me that `Chrome is using CPU and not GPU to render the video`. Indeed.

After turning ON `Use graphics acceleration when available`, using `WebGL2` rendering will NOT consume CPU.
(though I do not know how beneficial using `WebGL2` GPU rendering is compared to default rendering.)
