### ISSUE TITLE
[Bug] Remote play doesn't work

### ISSUE THREAD

**Issue by BigFrog666** [redphx/better-xcloud#434]
**Platform**
- Device name: ... Poco X3 NFC
- Device type (phone/TV): ... Phone
- Android version: ... 12
- App version: ... 0.3
- Script version: ... 3.2.4

**Describe the bug**

Remote play only works if I connect to the same network as the Xbox, if I connect to another it simply doesn't work.  I already opened ports 9002, 5050 and 4838, but it didn't solve the problem.  Problem only happens on better xcloud, it works on the official app.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.
![Screenshot_2024-03-19-11-23-59-388_com miui gallery](https://github.com/redphx/better-xcloud-android/assets/163888827/9be44114-5db4-412b-8345-10083821aefb)

https://github.com/redphx/better-xcloud-android/assets/163888827/47794cec-0b22-48c7-aa58-ac5673da1182

**Comment by redphx** [comment]
I can 100% confirm that it works for me in the Better xCloud app when I play using mobile data.  

Your situation is similar to this: https://github.com/redphx/better-xcloud/issues/280

**Comment by BigFrog666** [comment]
> I can 100% confirm that it works for me in the Better xCloud app when I play using mobile data.
> 
> Your situation is similar to this: [redphx/better-xcloud#280](https://github.com/redphx/better-xcloud/issues/280)

In my case, it didn't work even on mobile data 
yes, it's basically the same situation, but I couldn't solve it by opening the doors

**Comment by Pierre1533** [comment]
My game has the same bug, when the game starts, an error appears to update

**Comment by Aendros** [comment]
Not working for me either, tried with mobile data, and also changing DNS servers. Last time I've tried I saw a symbol like a play button fading... Could be something related to the video codec? It was working for me until 0.8 but I was using it inside my home network, so can't be completely sure.

Edit 1: I can confirm that I have the same issue with kiwi browser and Bx extension, no image.

Edit 2: I just arrived home and inside my home network remote play works fine, but if I try with mobile data, it does not. So, something weird with the network connection, but not a clue!

**Comment by redphx** [comment]
Try opening these ports (both TCP & UDP):  
- 4838
- 5050
- 9002
- 50302

**Comment by Aendros** [comment]
Hi all, opening the port 9002 solved the issue in my case. The other ports seem unnecessary so I keep them closed for the moment. You are limited to open the port to one IP address (at least that I could find), so if you have more than one console you will have to chose which one will have the port open.

**Comment by BigFrog666** [comment]
> Try opening these ports (both TCP & UDP):
> 
> * 4838
> * 5050
> * 9002
> * 50302

It didn't work. I stopped responding because I was without my Xbox, but now with it back the same problem persists, even with script and app updates and all ports open

**Comment by BigFrog666** [comment]
> Try opening these ports (both TCP & UDP):
> 
> * 4838
> * 5050
> * 9002
> * 50302

![IMG-20240424-WA0071](https://github.com/redphx/better-xcloud-android/assets/163888827/8d604aea-22f0-4ba6-bc40-d18a0fbef09a)

**Comment by Aendros** [comment]
> > Try opening these ports (both TCP & UDP):
> > 
> > * 4838
> > * 5050
> > * 9002
> > * 50302
> 
> ![IMG-20240424-WA0071](https://github.com/redphx/better-xcloud-android/assets/163888827/8d604aea-22f0-4ba6-bc40-d18a0fbef09a)
> 
Not sure if you can, but the image shows two rows for each port, try opening the port just for the xbox IP address, 192.168.1.3 in your case I guess. Try that and tell us what happened.

**Comment by redphx** [comment]
9002 port should be UDP, not TCP

**Comment by BigFrog666** [comment]
> 9002 port should be UDP, not TCP

![IMG-20240425-WA0001.jpg](https://github.com/redphx/better-xcloud-android/assets/163888827/4e39ad6d-8557-4412-a8b3-044bb456cec3)

I changed it but it doesn't work

**Comment by BigFrog666** [comment]
> > > Try opening these ports (both TCP & UDP):
> > > 
> > > * 4838
> > > * 5050
> > > * 9002
> > > * 50302
> > 
> > ![IMG-20240424-WA0071](https://github.com/redphx/better-xcloud-android/assets/163888827/8d604aea-22f0-4ba6-bc40-d18a0fbef09a)
> > 
> Not sure if you can, but the image shows two rows for each port, try opening the port just for the xbox IP address, 192.168.1.3 in your case I guess. Try that and tell us what happened. 

I talked to my ISP (they are the ones who make these changes per company rules) And they said it's already for just one IP address.

**Comment by BigFrog666** [comment]
> 9002 port should be UDP, not TCP

According to the image I sent, are there any changes I need to make to make it work?

**Comment by Aendros** [comment]
> > 9002 port should be UDP, not TCP
> 
> According to the image I sent, are there any changes I need to make to make it work? 

Not to my knowledge, but I have read that you may find some problems if your router is behind a CGNAT, which means that you don't have a unique  public IP. You could ask your ISP if this is your case, if so, ask them for a unique IP.

**Comment by BigFrog666** [comment]
> > > 9002 port should be UDP, not TCP
> > 
> > 
> > According to the image I sent, are there any changes I need to make to make it work?
> 
> Not to my knowledge, but I have read that you may find some problems if your router is behind a CGNAT, which means that you don't have a unique public IP. You could ask your ISP if this is your case, if so, ask them for a unique IP.

I just talked to the internet provider, they tried public ip and it didn't work. Nothing worked. And I was even told that the problem was in the script, not in the network and I'm starting to believe that because of the amount of changes I've made and it didn't work.

**Comment by Aendros** [comment]
> > > > 9002 port should be UDP, not TCP
> > > 
> > > 
> > > According to the image I sent, are there any changes I need to make to make it work?
> > 
> > Not to my knowledge, but I have read that you may find some problems if your router is behind a CGNAT, which means that you don't have a unique public IP. You could ask your ISP if this is your case, if so, ask them for a unique IP.
> 
> I just talked to the internet provider, they tried public ip and it didn't work. Nothing worked. And I was even told that the problem was in the script, not in the network and I'm starting to believe that because of the amount of changes I've made and it didn't work. 

Could be... I don't know. There is something else you can try. Install XBplay from the store and try playing with it. If remote play works on that app, it is quite possible that the problem is on the BX app

**Comment by Broklex** [comment]
Soo, is this ever gonna be solved? I've opened all the neccesary ports as other people redirected into this thread and it simply just doesnt work

**Comment by redphx** [comment]
Everything you need to make Remote Play work is here: https://better-xcloud.github.io/remote-play/

If it still doesn't work, check your network. The script can't fix it.  
The Xbox app uses a different method so it can't be compared.

**Comment by eritrium** [comment]
Remote play with android App doesnt t work black screen. Fix pleas
