### ISSUE TITLE
[Bug] Guide menu buttons "Reload Stream" &  "Back To Home" are missing & Feedback button is shown again

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#436]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.16.2

### Better xCloud Version

5.1.1

### Reproduction Steps

Hi ...

Since updating to script version 5.1.1, the buttons "Reload Stream" and "Back To Home" are missing in the Guide menu. Instead the newly added "Stream Settings" and "Android App Settings" buttons are shown. Which I think are supposed to only show when you are on the home screen, but not when you open the Guide during gameplay?

And another related little thing: I remember commit https://github.com/redphx/better-xcloud/commit/850afb4ca7c25e9ca6469ebed27c6565ba641d12 to hide the feedback button in the Guide when analytics are disabled. But the feedback button is shown again for me. So if you didn't revert the commit, it seems the method to remove it doesn't work anymore.

I can provide screenshots later.

Thanks.

**Comment by KingNothing81** [comment]
Here are the screenshots:

![IMG_0265](https://github.com/redphx/better-xcloud/assets/146887651/cfba708a-0ae6-49d3-8146-fbfbc9054d81)

![IMG_0266](https://github.com/redphx/better-xcloud/assets/146887651/3b9a72fe-63c0-4822-a026-2990ac05f5ff)

**Comment by redphx** [comment]
Fixed in 5.1.2
