### ISSUE TITLE
[Bug] Guide Menu buttons are being injected to the Settings dialog

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#438]
### Device

Other

### Device name

Shield TV

### Android Version

Android TV 11

### App version

0.16.1

### Script version

4.7.1

### WebView name and version

Chrome 125.x

### Reproduction Steps

Hi …

The glitch with the "Close app" button being injected to the Settings dialog, that was supposed to be fixed with 4.7.1, is still happening for me. 

The button still shows up in the categories “Audio and Video”, “Accessibility” & “Input”.

![PNG-Bild](https://github.com/redphx/better-xcloud-android/assets/146887651/0b2eef72-54ec-4268-875b-59db99141c69)

**Comment by KingNothing81** [comment]
Hi  ...

This issue is still happening with 5.1.1. But now not only the "Close App" button gets injected, but also the recently added two Settings buttons.

I  decided to reported the issue here, because the "Close App" button is only present in the Android app. But I guess this is something that has to be fixed in the script's code.

**Comment by KingNothing81** [comment]
Here is a video showing the issue …

https://github.com/redphx/better-xcloud-android/assets/146887651/9bc8fe9f-ef4c-4f1b-9159-90676dfdde60

At the beginning you can see another glitch I just discovered: When switching to another tab in the guide menu and going back, the buttons have disappeared. But they still get injected into the settings window afterwards.

Hope this helps.

**Comment by redphx** [comment]
Fixed in 5.1.2
