### ISSUE TITLE
[Bug]  better Xcloud script not always loading

### ISSUE THREAD

**Issue by Johan1976** [redphx/better-xcloud#439]
### Device

TV

### Device name

Philips AndroidTV 7304/12 

### Android Version

11

### App version

0.16.4

### Script version

5.1.1

### WebView name and version

Android System webview 126

### Reproduction Steps

1. Start app.
Server button not always showing (script not loaded)
2. Press green reload button (lower right corner) (not possible to press without a mouse on AndroidTV) 
Server button visible and possible to go to settings.

**Comment by redphx** [comment]
This is a known issue.  
also the app UI is not optimized for TV. You'll need a mouse no matter what.

**Comment by redphx** [comment]
Fixed in the beta version of the script: App setings > Script variant > Beta

**Comment by Johan1976** [comment]
Really? That's great! I'll try it out later. Even if not optimized it works really great on AndroidTV. Basically only some settings require mouse. I can even sign out and login with just the controller!

**Comment by redphx** [comment]
Fixed in 5.1.2
