### ISSUE TITLE
[Feature] 30/60 FPS

### ISSUE THREAD

**Issue by Hukolla** [redphx/better-xcloud#44]
Thanks a lot for your script. See if it's possible to make a choice of streaming frame rate? It will be useful for owners of weak laptops. My laptop does not run at 100% speed when using the default user agent. You have to use a mobile user agent. But the quality is worse

**Comment by redphx** [comment]
I haven't tested this yet, but isn't limiting the framerate gonna make the stream more choppy (from 60FPS game to 30FPS stream).

**Comment by Hukolla** [comment]
> 

Please take a look, maybe something will work out?)

**Comment by redphx** [comment]
I checked. It's not possible to adjust FPS from client-side.
