### ISSUE TITLE
[Bug] Getting redirected to a Xbox landing page before xCloud website has finished loading

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#440]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.16.4

### Better xCloud Version

5.1.2

### Reproduction Steps

Hi …

After updating to script version 5.1.2, I get redirected to a Xbox landing page before the xCloud website has finished loading. Making the app unusable for me.

I guess this happens because I’m using the Smart TV profile. But if this landing page has a code or button to sign in, it’s “out of area” on my 1080p TV. And I can’t scroll down to see the rest of it. 

It’s also impossible to open the script settings fast enough to change the UA profile back to default before the redirect happens. 

So I will try to reset all settings to default now by clearing app data and/or deleting & reinstalling the app.

### Screenshot/video

https://github.com/redphx/better-xcloud/assets/146887651/6a735371-c49d-4109-9ded-b9fb57b9eacc

**Comment by KingNothing81** [comment]
> So I will try to reset all settings to default now by clearing app data and/or deleting & reinstalling the app.

Clearing app data worked to get the app back working with the “default” profile. But when I switch back to the “Smart TV” profile, it happens again.

So if another user has set the “Smart TV” profile and is using the app on a 1080p TV, they will probably end up in the same situation when updating the script.

**Comment by redphx** [comment]
Use Meta Quest profile + TV layout for now

**Comment by redphx** [comment]
Fixed in beta script

**Comment by KingNothing81** [comment]
Thanks for the quick fix. I can confirm that installing the beta fixed this.

I also wanted to report that the top left stream HUD is not available anymore with the smart TV profile. But now I see that you have already fixed this too. =)

If you don't do it, I will close this issue when the changes have made it to the stable version. And thanks again for your great work.
