### ISSUE TITLE
[Feature] Close "Stream Settings" When Opening Guide Menu

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#441]
### Device

Other

### Operating System

Android

### Browser

Chrome/Edge/Chromium

### Suggestion

Hi ...

It's now possible to open the "Stream Settings" with a button in the Guide menu. 

But recently it happend to me that I opened the "Stream Settings" accidentally. I expected that I can close them again by re-opening the Guide menu. Or by pressing the "Stream Settings" button in the Guide a second time. But without success.

So I wanted to suggest that the "Stream Settings" will close when the user opens the Guide menu. Or if it's easier to do, if the user presses the button in the Guide again when the "Stream Settings" are already open.

I know that you can only adjust the stream settings with a mouse. But it would be useful if there is a way to just dismiss the settings window with the controller, if a user has opened it by accident.

Thanks.

**Comment by redphx** [comment]
Done. Test beta script.
