### ISSUE TITLE
[Bug] I can't use my custom controls while in game

### ISSUE THREAD

**Issue by rynahmd1** [redphx/better-xcloud#443]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Lenovo yoga

### Operating System

Windows 10

### Android app/Browser Version

Latest chrome version

### Better xCloud Version

Latest

### Game list

Fortnite

### Reproduction Steps

Dosent work in the first few minutes of my game

**Comment by redphx** [comment]
Is this virtual controller feature? Show video.
