### ISSUE TITLE
[Bug] A lot of input lag

### ISSUE THREAD

**Issue by Wallakk** [redphx/better-xcloud#444]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Samsung Essentials E30

### Operating System

win 10

### Android app/Browser Version

newest

### Better xCloud Version

newest

### Game list

Ark survival ascended

### Reproduction Steps

When I turn on better Xcloud, the transmission has a lot of input lag, transmission quality doesn't change, no image loss or aliasing, but the delay for the commands makes it unplayable, can you solve that, or do you know if this is some problem with Better xcloud?

**Comment by redphx** [comment]
not enough info  
what is your settings?
