### ISSUE TITLE
[Bug] Incorrect localization (Bypassing region restriction)

### ISSUE THREAD

**Issue by SashaTkachenko** [redphx/better-xcloud#445]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Lenovo flex5, acer aspire 5

### Operating System

Chrome OS, Windows 11

### Android app/Browser Version

Chrome 126.0.6478.132

### Better xCloud Version

Android better x cloud 0.16.4

### Game list

Fallout4

### Reproduction Steps

1. tap Bypassing region restriction
2. choosing a language for games Russian
3. reset BetterXcloud 
4. Launch BetterXcloud good 
5. Start Fallout4
6. The language in the game has changed to English

### Screenshot/video

I'm from Ukraine. I always turn on Poland via VPN, and then I have the correct translation

![Screenshot 2024-07-14 16 42 39](https://github.com/user-attachments/assets/dbd7f9dc-f7a5-4a1e-b24a-d834ce3697d7)
When VPN to Poland is simply turned on, it shows Russian localization
![Screenshot 2024-07-14 16 44 01](https://github.com/user-attachments/assets/470a7a2e-41d1-434b-a92e-eebff0fa6575)

when you enable Bypassing region restriction
![Screenshot 2024-07-14 16 46 52](https://github.com/user-attachments/assets/51be5bbe-da23-4539-944c-a59e95f25956)
The game is translated into English
![Screenshot 2024-07-14 16 48 08](https://github.com/user-attachments/assets/068d5a9e-1102-41b0-a695-66da6455ecda)

**Comment by redphx** [comment]
Try this version https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by SashaTkachenko** [comment]
Thanks, it works. Just perfect
