### ISSUE TITLE
[Bug] Controller Shortcuts Tab seems to forget settings

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#449]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Nvidia Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.16.4

### Better xCloud Version

5.4.0

### Reproduction Steps

Hi ...

I noticed a small issue with the controller shortcuts tab:

When the app was closed and I open it again, all "slots" in the controller shortcuts tab look like they have been reset. 

But this seems to be just a visual glitch, as my set shortcuts still work, They are just not shown in the UI. And when I set them again in the interface, all "slots" look empty again after closing and opening the app again. This "clearing" also happens when using the "reload page" button during gameplay.

I think this might be related to the changes you've made for the controller-friendly UI. Although I tried disabling it but it still happens even with the controller-friendly UI disabled.

P.S.: And thanks for implementing the settings "looping". I think this is really cool and makes using the controller-friendly UI even more comfortable. =)

**Comment by redphx** [comment]
Fixed in beta version. Thanks for reporting.
