### ISSUE TITLE
[Bug] Remote Play Icon missing

### ISSUE THREAD

**Issue by gh0sti** [redphx/better-xcloud#450]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Macbook Pro 2019 16in

### Operating System

macOS 14.5

### Android app/Browser Version

Brave Version 1.67.134 Chromium: 126.0.6478.186 (Official Build) (x86_64)

### Better xCloud Version

5.4.0

### Game list

xbox mian page

### Reproduction Steps

1. Launch xbox.com/play
2. have script load up
3. script shows running except for no remote play button

### Screenshot/video

<img width="1451" alt="xbox issue" src="https://github.com/user-attachments/assets/5c84108d-cc94-4e84-a9f7-19bbe9e2c7e6">

**Comment by gh0sti** [comment]
Remote play is enabled in the settings.

**Comment by redphx** [comment]
Xbox servers are down https://www.xbox.com/status

**Comment by gh0sti** [comment]
> Xbox servers are down https://www.xbox.com/status

well that's silly I didn't know that xbox was down.
