### ISSUE TITLE
[Bug] Using WebGL2 renderer causes error

### ISSUE THREAD

**Issue by acee9** [redphx/better-xcloud#451]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

HP 15s

### Operating System

Windows

### Android app/Browser Version

Edge 126.0.2592.113

### Better xCloud Version

5.4.1

### Reproduction Steps

.

**Comment by redphx** [comment]
Do you use controller-friendly ui setting? And share video pls.

**Comment by acee9** [comment]
I used to, now´s off

https://github.com/user-attachments/assets/8ea1ca42-16c9-4d8b-bda3-ec05caa1bd9a

**Comment by redphx** [comment]
<img width="101" alt="image" src="https://github.com/user-attachments/assets/4a391b9b-bfae-4553-b6f9-f1c7adfe07d6">  

The System menu bar doesn't show Better xCloud's buttons, which meant it wasn't loaded succesfully.  

I had this bug once but didn't run into it again.

**Comment by acee9** [comment]
Is there some solution?, I have already updated the new version 5.4.2 but still like that

**Comment by redphx** [comment]
My best guess is some other extension conflicted with the script.  

Pls share a screenshot of the [Web DevTools's Console tab](https://developer.chrome.com/docs/devtools) after loading the home page. If you don't see any line with "BxC Patcher" then my theory is correct.

**Comment by acee9** [comment]
![Cap](https://github.com/user-attachments/assets/897ac953-5aa6-4d09-97d9-d72d718d630e)

**Comment by acee9** [comment]
![Cap2](https://github.com/user-attachments/assets/ff43796d-68c6-4088-a92d-4719180f3a59)

**Comment by redphx** [comment]
Thanks. Now capture the entire Console after loading into the game.

**Comment by acee9** [comment]
https://github.com/user-attachments/assets/10d0d433-0dfa-4af4-bf2b-47888909d5c1

**Comment by redphx** [comment]
Apparently your device doesn't support WebGL2.

You can clear the settings by typing this line into the Console, then press Enter:
`localStorate.removeItem('better_xcloud')`

Refresh the page.

**Comment by acee9** [comment]
Yes it does support, but definitely that option cause the problem, i think its done, what'd you think?
https://github.com/user-attachments/assets/ba00b833-df56-4ba3-ab11-4c486aca67f2

**Comment by redphx** [comment]
So it worked again? That's weird. Maybe there is a combination of settings that caused the problem.
