### ISSUE TITLE
[Bug] Some little issues in the Stream Settings

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#452]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.17.0

### Better xCloud Version

5.4.1

### Reproduction Steps

Hi …

First a big thank you for all the effort and time you put into the controller-friendly UI. That’s really appreciated.

But updating to script version 5.4.1, I found some little issues with the Stream settings:

- In the controller tab, “false” is added at the end of every settings option.

- Looping through the settings doesn’t work. I know it’s only supposed to work in the stream settings at the moment, but it also doesn’t work for me here. _(Note: Sorry. No, the looping works. Just not how I expected. See second comment below.)_

- In the “Audio & Video” tab I can’t get past the “Clarity Boost” option anymore. So I can’t adjust “Sharpness”. This was not a problem with the previous beta version before. _(Not shown in the video, but I just noticed that this works again, if render engine is set to “WebGL2” and the “GPU configuration” option is not hidden anymore.)_
 
I’ve made a video trying to show all issues beginning with the controller tab. Then I tried to “loop” through the options of the “render engine”. And in the end I’m failing to reach the sharpness slider.

Hope this helps.

### Screenshot/video

https://github.com/user-attachments/assets/fc500ad0-9f34-4d44-a449-e1dd79348b44

**Comment by KingNothing81** [comment]
Sorry … it’s me again.

I just realized that there was a misunderstanding regarding “looping” the settings.

You implemented “horizontal” looping when pressing up/down at the top/bottom of the window.

But my original idea was to loop the actual settings. So the left / right arrow buttons never get inactive / greyed out, but you can just “loop” through the options. 

But maybe that’s not possible or means a lot of extra work. If that’s the case, let’s just forget about this. The current “looping” is also a nice addition.

**Comment by redphx** [comment]
These bugs should be fixed in 5.4.2  

Global settings section uses the navigation system from xCloud, so these changes don't apply to it. The idea is to migrate it to the same dialog as Stream settings, but that's for future updates.

**Comment by KingNothing81** [comment]
Yes, I can confirm that everything is fixed with 5.4.2. And that commit https://github.com/redphx/better-xcloud/commit/c796152bdd65a68387b3115974cb4e617ba2d5c6 was a great idea, just as effective as “looping” the settings. You’re a genius. 

And thanks again.
