### ISSUE TITLE
[Bug] I can't play in remote play, black screen or error

### ISSUE THREAD

**Issue by itssadri18** [redphx/better-xcloud#453]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

DESKTOP-2HRVHVQ

### Operating System

Windows 10

### Android app/Browser Version

Opera GX Version LVL 5 (core: 109.0.5097.142)

### Better xCloud Version

5.4.2

### Game list

Remote Play

### Reproduction Steps

1. I open the page 2. I hit the remote play icon 3. I hit connect 4. Error

### Screenshot/video

![imagen_2024-07-19_222914508](https://github.com/user-attachments/assets/108b9a53-f29d-4eb4-821e-3c4f312a29ce)
![image](https://github.com/user-attachments/assets/7a489a28-9c43-48d2-b628-bbd4a3ee7df6)

**Comment by redphx** [comment]
Dup #229
