### ISSUE TITLE
[Bug] Bypassing regional restrictions does not work on my iPhone8 Plus

### ISSUE THREAD

**Issue by Zakof1983** [redphx/better-xcloud#455]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Phone/Tablet

### Device

iPhone 8 Plus

### Operating System

iOS 16.3.1

### Android app/Browser Version

Safari

### Better xCloud Version

5.4.2

### Game list

each

### Reproduction Steps

It is able to display the full game page normally on the Home, but clicking on the game rocket icon will jump into an error screen after running, can you help see what the problem is, thank you

### Screenshot/video

https://github.com/user-attachments/assets/e5f77c45-a09e-4594-8f94-6f42709b67f5

**Comment by redphx** [comment]
Change User-Agent back to Default

**Comment by Zakof1983** [comment]
I've try that to default but it's the same, will showen We'll be right back the black screen

**Comment by Zakof1983** [comment]
I've try different settings of iOS/Safari , But this code below can be bypassing region what ever setting I changed, So maybe some problems has 
https://greasyfork.org/zh-TW/scripts/455741-xbox-cloud-gaming%E4%BC%98%E5%8C%96%E6%95%B4%E5%90%88/code

**Comment by redphx** [comment]
Make sure you don't use any other scripts along with Better xCloud.  

I tested on my iPad and didn't have this problem. Do you know how to use Web Inspector in Safari iOS? Here is [the guide](https://www.browserstack.com/guide/debug-website-using-safari-developer-tools).  

I need you to check the error logs in the Console tab after the game crashes.

**Comment by Zakof1983** [comment]
Yes, I just using Better xCloud one scripts
And sorry, I read the guide, but my MAC is broken can't assist my iPhone to test the page

**Comment by redphx** [comment]
Does this bug happen when you use VPN?

**Comment by Zakof1983** [comment]
yes, I also thought of testing this just now. When I VPN to a Japanese IP, the situation is still unable to connect to the game. I have also asked other Taiwanese friends to test that some iPhones can work, but occasionally Remote Play will fail; some also cannot.

**Comment by redphx** [comment]
Please ask them to check for errors in Safari's Web Inspector. I think it works on Safari Windows too.

**Comment by Zakof1983** [comment]
I borrowed a Mac and tried it several times but it always stopped at the enabling native controller 
(the last line in the screenshots is when the game crashes). 
Is this the information you want to refer to? If you have any other guides, please let me know,Thanks!

![image](https://github.com/user-attachments/assets/5917499e-8e7f-48ac-89e6-c0f7bef3348c)

![image](https://github.com/user-attachments/assets/ebb04a27-1070-4b1a-937f-6f43c991d22a)

![image](https://github.com/user-attachments/assets/dc222912-467f-4eb6-b2a0-f7c1b9833d87)

![image](https://github.com/user-attachments/assets/19fe1fd0-b80d-4906-a252-e3fed4aa9d59)

**Comment by redphx** [comment]
Thanks. Please try this version: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by Zakof1983** [comment]
It works! Thank you. I played with touch control for an hour. Switching between different games and remote play are all good. I will also ask friends to try this version and see if there is any problem. Thank you!

![image](https://github.com/user-attachments/assets/3c04a967-2052-4dd8-822a-cf87b130c29b)

![image](https://github.com/user-attachments/assets/eb5d0142-28b9-4af2-a4bd-77a9653897c2)

![image](https://github.com/user-attachments/assets/cd8a450c-057c-4f08-8deb-c8656574228a)

**Comment by redphx** [comment]
Thanks for taking time helping me to debug this issue
