### ISSUE TITLE
[Feature] More hiding options

### ISSUE THREAD

**Issue by RudyBugy** [redphx/better-xcloud#457]
### Device

Desktop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Suggestion

Hello. Please add more options to hide unnecessary sections from the main page.

section "Play with mouse and keyboard" - I think most people play xbox games with a controller, they are not interested in this section.

section "Most popular on cloud" - it's the same thing every day, it's not interesting, it just gets in the way.

I have already hidden the section with news and friends, if you also hide the suggested sections above, you will get a very convenient and informative page, after “Jump back in” immediately followed by “Recently added” and “Leaving soon”

**Comment by KingNothing81** [comment]
The "Play with Mouse and Keyboard" section only shows up on desktop browsers. So I think you should be able to hide it by changing the UA profile to one of the Smart TV profiles.

But I use the app on my TV and never really browse the game catalogue there. And when I want to start a game that's not in my "jump back in" row, I use the search on top. 

So maybe even an option that's hides everything except the "jump back in" row would be something that some users might like?

**Comment by redphx** [comment]
Added in 5.5.0
