### ISSUE TITLE
[Feature] Samsung Z Fold 6 and below Display

### ISSUE THREAD

**Issue by loveyounadeem** [redphx/better-xcloud#461]
### Device

Phone/Tablet

### Operating System

Android

### Browser

Chrome/Edge/Chromium

### Suggestion

Hey,

Geforce now allows us to change resolution which matches or close to feeling immersion on the z fold phones by Samsung which are amazing to play on.
However because game pass cloud is native 16:9, with stretch and 4:3, it looks terrible on the fold.

If we can natively or force display to certain resolutions, games will look amazing instead of stretch. When playing far cry 6, I notice it asks to push the screen boundary to match your screen, if we can have a feature like that to push beyond the given 16:9, it would be amazing. I was thinking if there was a way to trick it to think it is a certain resolution or force it to display.

These resolutions look good on the fold:
1600 x 900
1600 x 1024
1600 x 1200 
1680 x 1050
1440 x 1080
1440 x 900
1366 x 768
1360 x 768
1280 x 1024
1280 x 960
1280 x 800
1280 x 768
1280 x 720
1024 x 768

Best is 
1920 x 1200
1600 x 1024

Thanks a bunch!

**Comment by redphx** [comment]
Console games only support 16:9. You can't change that.
