### ISSUE TITLE
[Bug] Constant FPS Drops 

### ISSUE THREAD

**Issue by gustvtech2** [redphx/better-xcloud#464]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

PC

### Operating System

Windows 11

### Android app/Browser Version

Last Version

### Better xCloud Version

Last Version

### Game list

LEGO Fortnite

### Reproduction Steps

1 - Open the browser
2 - Run the game

The game fluctuates a lot in FPS, my monitor is 60FPS. When the FPS goes below 57, I feel the game freezing and when it goes above 60 it's the same situation. My mouse and keyboard lag as if they were not synchronized with the game. Ping always in 13ms, never much more or less. There is some way to make the FPS fixed like in mobile at 60FPS? 
Note: My PC is reasonably good and the connection too, so it's not the hardware/internet the problem.

### Screenshot/video

My Better xCloud settings:

<img width="340" alt="Captura de Tela (210)" src="https://github.com/user-attachments/assets/2b8c5c0d-25de-4406-96f9-b58430ee3086">

**Comment by redphx** [comment]
Try Default renderer

**Comment by gustvtech2** [comment]
FPS was stable between 54~60 FPS with the default renderer, when I leave the streaming window and come back it drops to 20 but then returns to normal. But I believe that is normal behavior

**Comment by redphx** [comment]
Then it's a dup #433
