### ISSUE TITLE
[Bug] Strange Behavior of the Script

### ISSUE THREAD

**Issue by gustvtech2** [redphx/better-xcloud#466]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

PC

### Operating System

Windows 11

### Android app/Browser Version

Last one

### Better xCloud Version

Last one

### Game list

Fortnite, LEGO Fortnite etc

### Reproduction Steps

1 - Enable just some settings of the script
2 - Run the game

I have noticed something strange happening with my transmission, using Better xCloud the image loses quality and most of the time it is pixelated. Now running without the script, the transmission improves and the pixelation stops. Another curious fact is that the default script (without configuring anything) also does not affect the transmission at all. I don't know what could be the cause of this problem, maybe is missing some optimization or have something broken.

### Screenshot/video

My configuration:
<img width="322" alt="Captura de Tela (218)" src="https://github.com/user-attachments/assets/4e247082-c1d7-480e-9bd8-9d4cdab83169">
<img width="326" alt="Captura de Tela (219)" src="https://github.com/user-attachments/assets/077acc84-0b3d-4867-9884-02f92d4222f2">

**Comment by gustvtech2** [comment]
Another observation, which I forgot to mention. With the script disabled, the bitrate is around 9-13 Mb/s, now with the script enabled (without configuring, or configured) the bitrate is between 3-6 Mb/s and sometimes 10 Mb/s for a few seconds

**Comment by gustvtech2** [comment]
For me, the difference in quality and stability of the transmission with the script deactivated and activated is really visible. I just don't understand, because the script was supposedly to improve the transmission

**Comment by redphx** [comment]
How do you know the bitrate value when the script is disable?

**Comment by gustvtech2** [comment]
Using the task manager, I only let the xCloud open in the browser. I just don't know if it's really accurate

**Comment by KingNothing81** [comment]
@gigaversebr: Are you sure that it's not the "Sharpness" setting that is causing the decrease in picture quality? Because for me even level 1 of "unsharp masking" already creates visible noise with some games. And I can see that you have set "Sharpness" level to "3".

**Comment by gustvtech2** [comment]
@KingNothing81 I thought about that too, but I already tried with this disabled and the same behavior remained. To be honest, in my perception this started to become more unstable after the bitrate speed adjustment setting was introduced. But I could be wrong, of course

**Comment by redphx** [comment]
The bitrate feature has nothing to do with this.  
Unless you can prove it, I still don't believe this issue is real.

**Comment by KingNothing81** [comment]
@gigaversebr: The option to prefer an IPv6 server is also not enabled by default. Maybe try to leave that disabled. Depending on your ISP / home network, using IPv6 might not work better and even decrease your connection quality. If that also doesn't make a difference, I'm out of ideas. Maybe you are facing some random and temporary connection / server issues that are on xCloud's side, but not caused by the script.

**Comment by redphx** [comment]
Invalid claim
