### ISSUE TITLE
[Bug] I went to test the session hiding feature and when reloading the page I came across this xcloud error.

### ISSUE THREAD

**Issue by Jhown-glitch** [redphx/better-xcloud#472]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Samsung Galaxy Book 2

### Operating System

Windows 10

### Android app/Browser Version

Chrome 127

### Better xCloud Version

5.5.1

### Game list

Sea of Thieves

### Reproduction Steps

1 - I updated Better xcloud.

2 - I looked at the new features that arrived since my last playthrough.

3 - I saw the hide sessions section and decided to test it.

4 - I reloaded the page and everything disappeared.

5 - I tried reinstalling better and it didn't work.

### Screenshot/video

![Xbox Cloud Gaming (Beta) em  Xbox com - Google Chrome 01_08_2024 18_59_18](https://github.com/user-attachments/assets/8420531e-1059-4ed8-ad9c-4981d9a6ae48)

**Comment by redphx** [comment]
Fixed in 5.5.2
