### ISSUE TITLE
[Bug] Page with "infinite" loading saying error.

### ISSUE THREAD

**Issue by Naltico** [redphx/better-xcloud#473]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Samsung Chromebook 4

### Operating System

Chrome OS

### Android app/Browser Version

Chrome 126.0.6478.214 (Official Version) 64-bit

### Better xCloud Version

5.5.2

### Game list

All

### Reproduction Steps

1. I select the game;

2. The screen says "failed to start Better xCloud";

3. The page reloads and says "the page you requested cannot be found";

4. And after more reloads it works normally again;

5. If I reload, the same thing happens again.

### Screenshot/video

(In the script failure image, Google Translate was used to translate, hence the strange letters.)

![3b2b4f1f-b27e-4371-84c2-a223b826300f](https://github.com/user-attachments/assets/39b6854a-e7d6-4b16-805a-24b6031c9420)

![Screenshot 2024-08-02 13 08 18](https://github.com/user-attachments/assets/41880e97-c3f2-486d-ba2b-6d3e33eccfce)

**Comment by btncua** [comment]
- Duplicate #428

**Comment by Naltico** [comment]
> - Duplicate #428 

Thank u, I solved it by putting Tampermonkey Legacy and Inject with Instantly.
