### ISSUE TITLE
[Bug] Hiding stream HUD bar leaves a black, semi-transparent rectangle

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#477]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.18.1

### Better xCloud Version

5.5.4

### Reproduction Steps

Hi ...

I don't know if this in the changelog ...

> "Fixed problems with the Stream's system menu bar (the one with Guide/Better xCloud/Streams stats buttons)"

... was about the same issue.

But if that's the case, it still happens when directly jumping from one game to another using the "recently played games" list in the guide menu: 

Then the stream HUD bar very often doesn't hide correctly, leaving a black, semi-transparent rectangle in the top left corner. When it happens, the icons in the HUD bar also don't have the usual order which might be part of the problem.

If needed I can provide a video / screenshots later.

Thanks.

**Comment by KingNothing81** [comment]
Couldn’t record a video that’s smaller than 10MB, but here a screenshots:

![PNG-Bild](https://github.com/user-attachments/assets/d5192bab-2d11-4a00-9c99-66ad8710f548)

That’s the black, semi-transparent rectangle that stays on screen when the HUD bar hides.

And that’s the mixed up order of the icons when it happens, with the stream stats button on the very left and not the three dots:

![ Bild2](https://github.com/user-attachments/assets/a8bd553e-09ed-41d4-a13b-666b16a90a7d)

As mentioned: This only happens when using the “recently played games” option in the Guide to directly jump between games.

And if other users find this: For now refreshing the page with the reload button makes the rectangle disappear again (and the icons return to their usual position).

Thanks.

**Comment by redphx** [comment]
Fixed in beta script. Thanks.
