### ISSUE TITLE
[Bug] "Bypass Region" banner makes the game unplayable

### ISSUE THREAD

**Issue by ZOBARCIK** [redphx/better-xcloud#480]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

Desktop PC

### Operating System

Windows 11

### Android app/Browser Version

Microsoft Edge 127.0.2651.98

### Better xCloud Version

3.5.5

### Game list

Yakuza 0

### Reproduction Steps

Whenever a new update is released for Better xCloud, "new version avaible" banner on the right side of the screen literally spams every minute or so. It happened for the last two or three updates, so it started with either 3.5.4 or 3.5.5 update.

It completely overrides the screen, so lets say when I was mashing X on the controller, new update banner appears and it directs me to the Github page. Even if I try to manually close the banner, it doesn't even pause the game so that's another problem.

I realized last night two update banners appear one on top of the other. I have to close two of them when that happens.

I couldn't get a screenshot as I usually play when that happens. All of these happened when I was playing Yakuza 0 but I'm not sure if it's related to the game.

**Comment by btncua** [comment]
What problem update to latest available version [5.5.6](https://github.com/redphx/better-xcloud/releases/tag/v5.5.6)?

**Comment by ZOBARCIK** [comment]
> What problem update to latest available version [5.5.6](https://github.com/redphx/better-xcloud/releases/tag/v5.5.6)?

It's not a problem with the update process. I can update just fine. It's the notification for the new version that causes the problem

**Comment by btncua** [comment]
Try reinstalling Tampermonkey and Better xCloud version [5.5.6](https://github.com/redphx/better-xcloud/releases/tag/v5.5.6), notification not should appear on latest version.

**Comment by ZOBARCIK** [comment]
> Try reinstalling Tampermonkey and Better xCloud version [5.5.6](https://github.com/redphx/better-xcloud/releases/tag/v5.5.6), notification not should appear on latest version.

**Comment by ZOBARCIK** [comment]
> Try reinstalling Tampermonkey and Better xCloud version [5.5.6](https://github.com/redphx/better-xcloud/releases/tag/v5.5.6), notification not should appear on latest version.

I reinstalled the add-on last week actually, its still the same. I will also reinstall tempermonkey and wait for the next update.

Note: my phone bugged ans I accidentally closed the issue a minute ago. Dont mind it

**Comment by ZOBARCIK** [comment]
Well I feel like a fool and I apoligize. It seems I was reading it wrong when I was quickly closing them. Its not new version avaible banner but "Bypass Region". I'm in a unsupported region and connect to the game via VPN, after connecting the game I disable the VPN continue playing. This thing happens after couple hours I start playing. Again, it started happening recently.

Reinstalling tempermonkey didn't solve the problem.
![Ekran görüntüsü 2024-08-24 015139](https://github.com/user-attachments/assets/fbc3ce12-965d-456f-a018-6bf877aaec7d)

**Comment by ZOBARCIK** [comment]
Can confirm that this only happens when I start the game using VPN, not when I use Better xCloud bypass feature.

**Comment by redphx** [comment]
share video
