### ISSUE TITLE
[Bug] I don't know if it is really a bug, but there's no more the opction with Region, Co-op support, etc

### ISSUE THREAD

**Issue by AugustinAbroba** [redphx/better-xcloud#482]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

Chrome 

### Operating System

Windows 10

### Android app/Browser Version

Crhome 27.0.6533.120

### Better xCloud Version

5.5.6

### Game list

Inicial Page

### Reproduction Steps

I oppened xCloud site onde day before this bug comes, and now i can't have access to other options, i didn't changed anything envolving the scrip, and tried to reinstall it.

### Screenshot/video

![image](https://github.com/user-attachments/assets/3c93fc0b-5ba4-4f8a-a3b5-86ea7be0199b)

**Comment by redphx** [comment]
Those settings are only available when you're logged in

**Comment by AugustinAbroba** [comment]
i was alredly logged in
![image](https://github.com/user-attachments/assets/b60b9013-c189-49c3-b05a-f453817f87e4)
