### ISSUE TITLE
[Bug] Black Screen during remote play while playing outside of local network

### ISSUE THREAD

**Issue by Broklex** [redphx/better-xcloud#483]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Asus Zenbook Fold 14

### Operating System

Windows 11

### Android app/Browser Version

Firefox 129.0.2

### Better xCloud Version

5.5.6

### Game list

every game

### Reproduction Steps

Whenever I load remote play outside of local network, right after the xbox splash screen I get stuck on black screen for about 10 seconds and then get disconnected

-happens on either web browser and android app
-doesn't happen while using the official xbox app 
-despite the dark screen, the console actually turns on every time
-NAT type is open
-tried forwading port 9002 as recomended by others, but didn't work

**Comment by redphx** [comment]
#434
