### ISSUE TITLE
[Bug] Activate button for virtual controller not showing up

### ISSUE THREAD

**Issue by Penguins700** [redphx/better-xcloud#486]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

PC

### Operating System

WIndows 11

### Android app/Browser Version

128.0.6613.84

### Better xCloud Version

5.5.6

### Game list

Fortnite

### Reproduction Steps

Load up fortnite on xcloud and sometimes the activate button to use the controller will not show up and if it does sometimes after around an hour it will randomly disappear and this didnt happen in version 3.5.1

### Screenshot/video

![image](https://github.com/user-attachments/assets/dfc4a136-2d43-4924-8456-ed01b74aa80c)

**Comment by redphx** [comment]
I don't understand what you're trying to say

**Comment by Penguins700** [comment]
![image](https://github.com/user-attachments/assets/efa7d74e-51ff-41fd-888f-10d3a87be2ad)

this button dosent show up sometimes even if i press f8

**Comment by levram99** [comment]
same issue for me, using browser script.

**Comment by levram99** [comment]
> I don't understand what you're trying to say

the button F8/F9 to emulate controller to keyboard and mouse is not showing on recent versions

but in older versions of better xcloud is working!

**Comment by redphx** [comment]
Should be fixed in 6.0  
If it's not, re-open the issue
