### ISSUE TITLE
[Feature] Multi-CloudPlay

### ISSUE THREAD

**Issue by devrainz** [redphx/better-xcloud#489]
### Device

All devices

### Suggestion

It would be awesome if there was any type of option that could possibly bypass the restriction that xbox does when trying to play on the Cloud on different games at the same time? Since you know, I share my account with some friends (3) ever since I got Game Pass Ultimate and it's been kinda difficult to share the time of playing on the cloud for each person. And because of that, I have been thinking of buying a Xbox Series X so I could play games on it without having to go all the time to the Xbox Gaming Cloud but still.

It would be nice if it had any similar feature that does that

**Comment by redphx** [comment]
Impossible
