### ISSUE TITLE
[Bug] Fullscreen bug

### ISSUE THREAD

**Issue by danfozzy** [redphx/better-xcloud#49]
**Describe the bug**
Since 1.9, when ever I start a game, it no longer starts it in the full screen mode. I now have to manually set the full screen setting in game everytime.

**Expected behavior**
Versions prior to 1.9, when starting a game it would automatically change to full screen.

**Platform (please complete the following information):**

OS: Android TV (shield TV pro and tube versions 2019)
Browser: Kiwi
Browser Version: 116
Better xCloud Version: 1.8.2

**Comment by redphx** [comment]
Does it also happen in older versions? You can uninstall the current version and reinstall a previous one without losing settings.

**Comment by danfozzy** [comment]
So playing around with different versions and different settings ive managed to narrow it down to the user agent option. If I keep it as default, I get the automatic full screen on starting a game. Selecting edge or Samsung TV will result in it not starting a game in full screen, I have to then manually select full screen from your in game menu. Is there away for it to automatically go full screen on these options or is it a default option only?

**Comment by redphx** [comment]
I think xCloud has this setting. I need to check again.

**Comment by Hukolla** [comment]
Probably because he uses a PC user agent. If you use mobile, it automatically turns on full screen

**Comment by danfozzy** [comment]
I don't think that's the case.

Now testing on 1.9 I no longer get auto full screen on the default or any other user agent. Rolling back to 1.8.2 and I get full screen when using the default user agent when starting a game.

**Comment by redphx** [comment]
Please share a video showing the bug

**Comment by danfozzy** [comment]
https://youtu.be/G_qIo8aodvY - 1.8.2 auto fullscreen working

https://youtu.be/1XQJMxA2U5Q - 1.10.1 no longer auto fullscreen (same for 1.9 onwards)

Both user agents set to default

**Comment by redphx** [comment]
Thank you. I know the problem. Will push a fix soon.

**Comment by redphx** [comment]
This should be fixed in version 1.10.2.  
Thanks everyone for reporting.

**Comment by redphx** [comment]
@danfozzy you can delete/hide the videos. Thanks.
