### ISSUE TITLE
[Bug] No sound in game when enable volume control feature

### ISSUE THREAD

**Issue by btncua** [redphx/better-xcloud#490]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Operating System

Windows

### Android app/Browser Version

Chrome 128.0.6613.120

### Better xCloud Version

5.7.0

### Game list

Fortnite

### Reproduction Steps

No sound in game when enable volume control feature. I tried change volume it doesn't work, but sound only plays again after disable this feature in Better xCloud settings. In previous version [5.6.1](https://github.com/redphx/better-xcloud/releases/tag/v5.6.1) it worked fine

**Comment by btncua** [comment]
![1](https://github.com/user-attachments/assets/4da23ce1-272b-43e9-becd-1457d24531c8)

![2](https://github.com/user-attachments/assets/93ebef0c-5a0f-4da4-9958-3e59ff0bdd33)

**Comment by redphx** [comment]
Fixed

**Comment by btncua** [comment]
> Fixed

Good, it work now
