### ISSUE TITLE
[Feature] Add toggle sound button to Game Bar

### ISSUE THREAD

**Issue by btncua** [redphx/better-xcloud#491]
### Device

Desktop

### Suggestion

- ### Add toggle sound button to `Game Bar`.

Now I used volume control feature as a toggle sound on stream.  
![1](https://github.com/user-attachments/assets/8459a147-5288-41ef-a4b2-e46aa1e3e890)

- Due to fact that this feature does not work in latest version [5.7.0](https://github.com/redphx/better-xcloud/releases/tag/v5.7.0) :

- [x] #490 , I decided to offer this

 
It would be more convenient to do it using a button, for example, in `Game Bar`.

Maybe you can advise me to use Chrome feature, that to turn off sound on each tab separately, but for this need to exit full-screen mode to do this, so it's not convenient at all, so I used slider as a toggle sound: 
![2](https://github.com/user-attachments/assets/f1133a43-3d56-4501-b622-c2c69cc6298f)

- I would suggest to implement it similar to this: 

![1](https://github.com/user-attachments/assets/eaa73536-6eaf-4b49-9b21-13bbdb373c5c)
_pasted Windows Speakers icon_ :)
![2](https://github.com/user-attachments/assets/eafdb4d7-f0e7-4fd9-bca9-c4e2d2c31478)

**Comment by btncua** [comment]
-  ### Also add ability to hide buttons in `Game Bar`, that you don't use.

**Comment by redphx** [comment]
Added in 5.7.2

**Comment by btncua** [comment]
> Added in 5.7.2

Thanks
