### ISSUE TITLE
[Bug] Using the “Smart TV” profile: Impossible to move from the “true achievements” button to the right & suggestion to add option to hide / replace the button

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#492]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

NVIDIA Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.20.0

### Better xCloud Version

5.7.0

### Reproduction Steps

Hi …

There is a problem with the new button layout in the Guide menu:

It’s impossible now to move from the “true achievements” button to the right to reach the other buttons. Because pressing right on the D-Pad (no matter if using a controller or a remote) will switch to the next tab in the Guide menu instead. I’ve attached a video to show the problem.

Apart from that I don’t really like that it’s not possible to hide the “true achievements” button for users that don’t want to use it. As it’s placed right next to the home / reload /quit button, so the chance to hit it accidentally is quite high in my opinion.

So maybe you can consider to add an option to hide the “true achievements” button. Or - to not break the layout - disabling it could replace it with another button. For example the quit app button could also be shown during gameplay instead.

Thanks.

### Screenshot/video

https://github.com/user-attachments/assets/ee0665c6-e335-4f2b-9abd-ce74a2151f24

**Comment by KingNothing81** [comment]
I thought this only happens when using the remote. But turns out, this problem also happens exists when using the controller.

So at the moment it’s not possible to press the home / reload / quit buttons in the Guide menu without touch support.

**Comment by KingNothing81** [comment]
Ok, another update: Turns out this only happens when using the generic “Smart TV” profile. Everything is fine when using the “Android TV” profile.

So no critical bug, as not many users will be affected.

**Comment by redphx** [comment]
<img width="526" alt="image" src="https://github.com/user-attachments/assets/1e5d3adf-4ad2-4a40-960e-777d9aa099d0">

Fixed. Buttons will be displayed like this on TV layout.  
No Quit button while playing because closing the app doesn't disconnect from the stream -> still taking slot on the server.

**Comment by KingNothing81** [comment]
Thanks for the quick update.

But I just wanted to point out that this only fixes the problem when using the “TV” layout. If someone uses the “Smart TV” profile with the “Normal” layout, the problem persists.

Which I did. Because with that combination the Guide menu (and other dialogs) don’t show a close button in the top right corner (see uploaded video). Which saves some space and looks better in my opinion. But I also don’t mind using the “Android TV” profile from now on. 

But maybe you can really consider to find another place for the “true achievements” button. Maybe have it right under the achievements progress bar? Because at the moment it feels a little bit misplaced in my opinion.

Thanks.

**Comment by KingNothing81** [comment]
After updating, I just noticed that 5.7.2 now also fixes this problem when using the “Normal” layout. So I can use the “Smart TV” profile again. And the new position of the “TrueAchievments” button is also nice.

So thanks a lot. =)
