### ISSUE TITLE
[Bug] "Failed to execute Better xCloud" 

### ISSUE THREAD

**Issue by Luiz2926tt** [redphx/better-xcloud#495]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Computer

### Operating System

Windows 10

### Android app/Browser Version

Brave 1.69.169

### Better xCloud Version

All

### Game list

All

### Reproduction Steps

Every time I open xCloud in my browser, I get the error "Failed to run Better xCloud". When I click on "How to Fix", I'm prompted to enable developer mode in my browser, but it's already enabled. I've tried enabling and disabling it several times, but the problem persists.

I've tested from the latest version (5.7.3) to version 5.5.4, but the error keeps occurring.

### Screenshot/video

![Capturar](https://github.com/user-attachments/assets/541ca9b3-3397-4360-a142-8933b3d52973)

**Comment by btncua** [comment]
- ### #428 

- ### #473

**Comment by btncua** [comment]
@Luiz2926tt enable option `UserScripts API Dynamic` in Tampermonkey settings

1.  **Settings**
2.  **General**  Config mode: `Advanced`
3.  **Security**  Content Script API: `UserScripts API Dynamic` 
4.  **Save**
5. Reload Xbox Cloud page
