### ISSUE TITLE
[Bug] Better cloud android app Internal Server error

### ISSUE THREAD

**Issue by ZweigOnly** [redphx/better-xcloud#497]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Phone/Tablet

### Device

Samsung Galaxy S23 Ultra

### Operating System

android 14

### Android app/Browser Version

android app 0.20.1

### Better xCloud Version

latest

### Game list

when opening the app

### Reproduction Steps

Everytime i open the app

### Screenshot/video

Dosnt load anything reports internal server error.

**Comment by redphx** [comment]
https://xbox.com/status
