### ISSUE TITLE
[Bug] Remote Controller and Local Controller not working at the same time

### ISSUE THREAD

**Issue by JannikGHG** [redphx/better-xcloud#500]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Steam Deck LCD

### Operating System

SteamOS Holo 3.5.19

### Android app/Browser Version

Chrome 128.0.66613.119

### Better xCloud Version

5.7.3

### Game list

General x cloud start screen, MK11, remoteplay

### Reproduction Steps

Issue:
I'm using Better xCloud on a Steam Deck and experiencing an issue with remote controller input during a Steam Remote Play Together session. My friend connects to my Steam Deck via Steam Link (Remote Play Whatever) on his iPhone, using an Xbox controller connected via Bluetooth. On the xCloud website, I can only use one controller at a time—either the Steam Deck controller or the remote Xbox controller—unless I deactivate one of them.

When I connect two controllers locally on the Steam Deck, everything works as expected.

Additionally, the same issue occurs when using Sunshine and Moonlight for streaming.

Steps to reproduce:

1. Use Better xCloud on Steam Deck.

2. Start a Steam Remote Play Together session, with a friend connecting remotely to the Steam Deck via Steam Link on an iPhone, using an Xbox controller (Bluetooth).

3. Attempt to use both the Steam Deck controller and the remote Xbox controller on the xCloud website

Expected Behavior:
Both the Steam Deck controller and the remote controller should work simultaneously without needing to deactivate either one.

**Comment by redphx** [comment]
Check how many controllers there are using this site: https://hardwaretester.com/gamepad  

If it only shows 1 controller then there is nothing I can do

**Comment by JannikGHG** [comment]
I tested and it's the same behaviour, only one controller at a time. So the issue is with Chromium?

**Comment by redphx** [comment]
It depends on how Stream Remote Play works. Maybe you'll have success with [Parsec](https://support.parsec.app/).  

I'm gonna close this issue.
