### ISSUE TITLE
[Bug] bx-gone flag being added to remote play button even after the feature is enabled

### ISSUE THREAD

**Issue by nolany** [redphx/better-xcloud#502]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Chromebook CX5501FEA/CB5501FEA (delbin, version 129.16002.0)

### Operating System

ChromeOS

### Android app/Browser Version

129.0.6668.37

### Better xCloud Version

5.7.3

### Game list

Remote Play

### Reproduction Steps

I had not used the remote play feature in a few weeks so I am unsure when this began as it was working the last time I attempted to use it.

I enable the remote play feature and the button does not appear after a reload. I was able to inspect the page and found that there is a tag that seems to be hiding the button even with the feature enabled: "bx-gone"

If I remove this tag, the button will appear and I can clock on it. However, once it is clicked it just shows a message at the top of the screen "Getting the list of consoles" and the typical window that pops up to select the console and remote play settings never appears.

Below is the default code that loads after enabling the remote play feature in the settings
`<button class="bx-button bx-ghost bx-focusable bx-circular bx-header-remote-play-button bx-gone" type="button" title="Remote Play" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#fff" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" viewBox="0 0 32 32"><g transform="matrix(.492308 0 0 .581818 -14.7692 -11.6364)"><clipPath id="A"><path d="M30 20h65v55H30z"></path></clipPath><g clip-path="url(#A)"><g transform="matrix(.395211 0 0 .334409 11.913 7.01124)"><g transform="matrix(.555556 0 0 .555556 57.8889 -20.2417)" fill="none" stroke="#fff" stroke-width="13.88"><path d="M200 140.564c-42.045-33.285-101.955-33.285-144 0M168 165c-23.783-17.3-56.217-17.3-80 0"></path></g><g transform="matrix(-.555556 0 0 -.555556 200.111 262.393)"><g transform="matrix(1 0 0 1 0 11.5642)"><path d="M200 129c-17.342-13.728-37.723-21.795-58.636-24.198C111.574 101.378 80.703 109.444 56 129" fill="none" stroke="#fff" stroke-width="13.88"></path></g><path d="M168 165c-23.783-17.3-56.217-17.3-80 0" fill="none" stroke="#fff" stroke-width="13.88"></path></g><g transform="matrix(.75 0 0 .75 32 32)"><path d="M24 72h208v93.881H24z" fill="none" stroke="#fff" stroke-linejoin="miter" stroke-width="9.485"></path><circle cx="188" cy="128" r="12" stroke-width="10" transform="matrix(.708333 0 0 .708333 71.8333 12.8333)"></circle><path d="M24.358 103.5h110" fill="none" stroke="#fff" stroke-linecap="butt" stroke-width="10.282"></path></g></g></g></g></svg></button>`

This is the message that appears after clicking on the button once I remove the bx-gone tag, nothing else happens after this
![image](https://github.com/user-attachments/assets/16af20e5-52ab-4c14-9f7d-9f102f3f5c9f)

### Screenshot/video

![image](https://github.com/user-attachments/assets/1ad8e34b-55dd-40ab-95be-830100791f59)

**Comment by redphx** [comment]
This button is only visible if the script is able to get a list of consoles. Switch to Network tab in DevTools, filter by "xhome" and check the response.

**Comment by nolany** [comment]
Just to note, my Xbox is on and confirmed on the same wifi as my laptop with all of the remote play features enabled, this also happens on my Steam Deck but I can do a lot more debugging on the laptop.

I get two results from a refresh

Request header:
```POST /v2/login/user HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 1581
Content-Type: application/json
DNT: 1
Host: xhome.gssv-play-prod.xboxlive.com
Origin: https://www.xbox.com
Referer: https://www.xbox.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Chrome OS"
```

Response:
```json
{"offeringSettings":{"allowRegionSelection":false,"regions":[{"name":"WestUS2","baseUri":"https://wus2.core.gssv-play-prodxhome.xboxlive.com","networkTestHostname":null,"isDefault":true,"systemUpdateGroups":null,"fallbackPriority":-1},{"name":"EastUs","baseUri":"https://eus.core.gssv-play-prodxhome.xboxlive.com","networkTestHostname":null,"isDefault":false,"systemUpdateGroups":null,"fallbackPriority":-1},{"name":"UkSouth","baseUri":"https://uks.core.gssv-play-prodxhome.xboxlive.com","networkTestHostname":null,"isDefault":false,"systemUpdateGroups":null,"fallbackPriority":-1}],"selectableServerTypes":null,"clientCloudSettings":{"Environments":[{"Name":"Int","AuthBaseUri":"https://gssv-auth-intxhome.xboxlive.com"},{"Name":"Prod","AuthBaseUri":null},{"Name":"Test","AuthBaseUri":"https://gssv-auth-testxhome.xboxlive.com"}]}},"market":"US","tokenType":"bearer","durationInSeconds":14400}
```

Request header:
```
GET /v6/servers/home?mr=50 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
DNT: 1
Host: wus2.core.gssv-play-prodxhome.xboxlive.com
Origin: https://www.xbox.com
Referer: https://www.xbox.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Chrome OS"
x-ms-device-info: redacted
```

Response:
```json
{"totalItems":0,"results":[],"continuationToken":null}
```

**Comment by redphx** [comment]
```json
{"totalItems":0,"results":[],"continuationToken":null}
```

Check the Remote Play setting on your console. The server returns empty list.

**Comment by nolany** [comment]
I have confirmed all Remote Play features are on in the Xbox settings. I can utilize Remote Play from the Xbox app on my Android phone without issues, I probably should have added that.

**Comment by nolany** [comment]
It does seem as though this is not a better-xcloud problem so if I run into a wall here that is totally understandable. I am going to go down the path of resetting all of my Remote Play features and testing again to see if I get the same results.

**Comment by redphx** [comment]
Don't share your token in the request/response. People can access your account with it.

**Comment by redphx** [comment]
Open Tampermonkey, modify [line 6336](https://github.com/redphx/better-xcloud/blob/typescript/dist/better-xcloud.user.js#L6336)

From:
```js
if (RemotePlay.#CONSOLES)
```

To:
```js
if (RemotePlay.#CONSOLES && RemotePlay.#CONSOLES.length > 0)
```

If it still doesn't work then I don't know.

**Comment by nolany** [comment]
Still the same responses when loading the page. Thank you for your prompt response and help. I will come back and update this if I find out what it is but I don't think it is related to better-xcloud now like I mentioned before.

**Comment by redphx** [comment]
Try this version: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js

**Comment by nolany** [comment]
I am going to go ahead and close this. Apparently my ISP did some service upgrades on my modem and turned off bridging so my router was causing Double NAT on my Xbox. I put my network settings back in place and was immediately able to use the Remote Play feature. Again thank you for the help and understanding.

**Comment by APotatoSquasher** [comment]
Who is your ISP? I'm having the same issue.
