### ISSUE TITLE
iOS Support in Web-Apps

### ISSUE THREAD

**Issue by ShukkaD** [redphx/better-xcloud#504]
### Device

Phone/Tablet

### Suggestion

Is it possible to add support for web-apps in iOS? As noted in the Safari 18 Beta Release Notes, they finally added support for extensions in web-apps. So, anybody using iOS/iPadOS 18 Beta should be able to use the extension in the web-app for Xbox Cloud Gaming, eliminating one of the main problems with the extension on Safari. Soon, once iOS 18 is out of beta, even regular users will be able to use it. However, when I try to use the extension in the web-app, it doesn’t work, so I’m thinking it’s something wrong in the extension code that prevents it from working in the web-app even though there is support now. I have linked the resources I used below:

Safari 18 Beta Release Notes (Check the Extensions Subtitle):
https://developer.apple.com/documentation/safari-release-notes/safari-18-release-notes

This was tested on iOS 18 Beta

Thanks!

**Comment by redphx** [comment]
You should ask this on https://github.com/quoid/userscripts instead
