### ISSUE TITLE
[Bug] no server icon on xcloud

### ISSUE THREAD

**Issue by KingRamulus** [redphx/better-xcloud#506]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

Desktop PC

### Operating System

Win11

### Android app/Browser Version

Version 129.0.6668.59 (Official Build) (64-bit)

### Better xCloud Version

v5.7.3

### Reproduction Steps

I followed the instructions but no server list pops up on either chrome or edge.

**Comment by btncua** [comment]
Share video or screenshot

**Comment by KingRamulus** [comment]
![Screenshot 2024-09-18 164515](https://github.com/user-attachments/assets/bf0bf7a6-0e18-4c6e-b652-26b1a78b6167)

I do not have the icon.

**Comment by btncua** [comment]
You enabled [`Developer Mode`](https://www.tampermonkey.net/faq.php?ext=dhdg&updated=true&version=5.3.0#Q209)?

**Comment by KingRamulus** [comment]
Do I need to if it says it successfully installed the client??

**Comment by btncua** [comment]
Yup

**Comment by KingRamulus** [comment]
Ah ok, working now. Thanks!
