### ISSUE TITLE
[Bug] constant stutters in games with wifi( fibre 25Mbps) but with my mobile data 5g network no stutters

### ISSUE THREAD

**Issue by remain2001** [redphx/better-xcloud#507]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Phone/Tablet

### Device

S24 plus

### Operating System

Android 14

### Android app/Browser Version

Better xcloud 

### Better xCloud Version

0.21.0(31)

### Game list

All games 

### Reproduction Steps

I really don't know tbh.

### Screenshot/video

https://github.com/user-attachments/assets/f3c466c6-fa6d-4ea1-af4b-cfc264bebf76

**Comment by redphx** [comment]
Fix your network. This has nothing to do with Better xCloud.

**Comment by remain2001** [comment]
U think reboot the router might work
