### ISSUE TITLE
[Bug] Black screen on chrome

### ISSUE THREAD

**Issue by austins414** [redphx/better-xcloud#508]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

PC

### Operating System

Windows 10 Pro

### Android app/Browser Version

Version 129.0.6668.58 (Official Build) (64-bit)

### Better xCloud Version

5.7.4

### Reproduction Steps

This is a remote play bug. I have a static IP now and the correct ports open. I can get remote play to work on the mobile app and on the xbox pc app. On better xcloud, the airplane comes up then the screen goes black after a few seconds. I've also tried greenlight and xbplay and the same thing happens. I'm not able to remote play unless on the official app.

**Comment by redphx** [comment]
#434

**Comment by Rindmann** [comment]
Having the same issues. Did you fix it?
