### ISSUE TITLE
[Bug] New Remote-Play popup cannot be navigated with controller.

### ISSUE THREAD

**Issue by ZeroFoxx** [redphx/better-xcloud#509]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Steam Deck OLED

### Operating System

SteamOS (arch based)

### Android app/Browser Version

Chromium 128.0.6613.137 (flathub)

### Better xCloud Version

5.7.4

### Game list

Remote Play

### Reproduction Steps

• Open Xbox Cloud Gaming page.

• Use a gamepad to navigate to remote play button and click it.

• Un-profit. 

(This worked as intended on the previous version, 5.7.3.)

**Comment by redphx** [comment]
Fixed: https://github.com/redphx/better-xcloud/raw/refs/heads/typescript/dist/better-xcloud.user.js
