### ISSUE TITLE
[Feature] Controller Deadzone

### ISSUE THREAD

**Issue by humanfriend22** [redphx/better-xcloud#511]
### Device

All devices

### Suggestion

My controller has a stick drift and I don't really want to fix it right since I dont use the joystick that much. Could there be a middleman between my controller and the game that applies a deadzone to the input? I know a virtual controller already exists as there is a keyboard emulator feature so maybe this wouldn't be too far off. This might be a really helpful feature to many and might not be that hard to add. Thank you.

**Comment by redphx** [comment]
Testing in #617

**Comment by redphx** [comment]
Added in 6.1.0
