### ISSUE TITLE
[Bug] The website says: "Failed to run Better xCloud"

### ISSUE THREAD

**Issue by FelipeJogos281** [redphx/better-xcloud#512]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Acer Aspire E5

### Operating System

Acer Aspire E5 64 bits.

### Android app/Browser Version

Opera GX LVL 6 (core: 113.0.5230.135)

### Better xCloud Version

5.3.0

### Game list

Fortnite

### Reproduction Steps

1. Open Xcloud site. 2. Error message apears. 3. I open the solution page and try to activate developer mode, even though it is already activated.

**Comment by btncua** [comment]
### Follow these [steps](https://github.com/redphx/better-xcloud/issues/495#issuecomment-2337360631)

**Comment by btncua** [comment]
### This is Tampermonkey problem, not Better xCloud

**Comment by btncua** [comment]
- ### #428 

- ### #473
