### ISSUE TITLE
[Bug] Interface keeps opening by itself, interrupting the game every time.

### ISSUE THREAD

**Issue by jsebs1** [redphx/better-xcloud#513]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

MacBook Air M1 (2020)

### Operating System

MacOS 15.0

### Android app/Browser Version

Microsoft Edge Version 129.0.2792.65 (Official build) (arm64)

### Better xCloud Version

5.7.7

### Game list

Skyrim, Crash bandicoot, Gears of war 3, FC24, Plants vs Zombies, etc

### Reproduction Steps

It happens randomly and with no specific previous actions for it to happen.

1. Open game
2. Play for a couple of minutes
3. Out of nowhere, the BxC interface opens by itself (interrupting gameplay)
4. I close it manually, resume my gameplay
5. Again, out of nowhere, the BxC interface opens by itself (interrupting gameplay)
6. Repeat steps 2 to 5, multiple times during the gameplay

### Screenshot/video

This is the interface that automatically pop-ups and interrupts the gameplay:
![error](https://github.com/user-attachments/assets/86d5a967-ea25-47d4-8d0e-679b1fd2ffef)

**Comment by redphx** [comment]
Fixed https://github.com/redphx/better-xcloud/raw/refs/heads/typescript/dist/better-xcloud.user.js
