### ISSUE TITLE
[Bug] Keyboard and Mouse Not Working on Microsoft Flight Simulator

### ISSUE THREAD

**Issue by ShukkaD** [redphx/better-xcloud#515]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Lenovo Ideapad Flex

### Operating System

Windows 11

### Android app/Browser Version

Edge 129.0.2792.65

### Better xCloud Version

5.7.7

### Game list

Microsoft Flight Simulator 2020

### Reproduction Steps

I turn on Keyboard in Mouse in settings and the emulation feature, then I launch Flight Simulator. It loads up, I am able to click Enter to start the game, but then nothing works. Touch controller doesn't work anymore, so I can't get past the menu, and Keyboard and Mouse doesn't work. Disabling the script makes touch work again and I can play the game with touch controls.

**Comment by redphx** [comment]
Try this https://github.com/redphx/better-xcloud/discussions/416#discussioncomment-9634698

**Comment by redphx** [comment]
Use this setting in 5.8.1

![telegram-cloud-photo-size-5-6066889860108631494-y](https://github.com/user-attachments/assets/8c184512-00d9-4b8b-a46d-c0104b827f31)
