### ISSUE TITLE
[Bug] Playing in IPv6 server having a IPv4 connection (?)

### ISSUE THREAD

**Issue by gustvtech2** [redphx/better-xcloud#517]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Notebook

### Operating System

Windows 11

### Android app/Browser Version

Edge 129.0.2792.79

### Better xCloud Version

5.8.1

### Game list

Fortnite

### Reproduction Steps

1. Open the game
2. Check statistics

I would like to report a strange bug that is happening to me, my internet is IPv4 and I do not have support for IPv6. For some reason, even without mark the ''prefer IPv6 server'' option, I'm connected to an IPv6 server (?)

My game is extremely unstable, with FPS drops, pixelation and ping spikes. My internet is 50 MB/s, DSL.

There is some way to just connect to a IPv4 server? I don't know, some option called ''prefer IPv4 server''?

Note: My notebook have support to IPv6, but is not used because the connection is just IPv4.

### Screenshot/video

![ipv6](https://github.com/user-attachments/assets/4b165f06-a023-49c1-96f8-40fc8864889d)
![ipv6-config](https://github.com/user-attachments/assets/3c65ab03-611e-4a5d-a9f8-1da490421161)
![ipv6-test](https://github.com/user-attachments/assets/106b3bb3-fda0-403c-9601-e2f3bb1e866b)

**Comment by redphx** [comment]
It's a visual bug. It always shows IPv6.

**Comment by gigaversebr** [comment]
> It's a visual bug. It always shows IPv6.

It's not always, when I play on other connections it appears @IPv4 and sometimes @IPv6 (in fiber connections, like TIM and Oi Fiber). 
I can test this on other connections and send you the screenshots, I don't think it's a visual problem

**Comment by gigaversebr** [comment]
My connection is PPPoE via DSL, but the switch outside my house is connected to a GPON router (fiber). I don't know if this creates some bug in the connection somehow

**Comment by redphx** [comment]
Fixed https://github.com/redphx/better-xcloud/raw/refs/heads/typescript/dist/better-xcloud.user.js  

It's just a visual bug. Chrome decides which server to connect to, not the script.
