### ISSUE TITLE
[Feature] Native Mouse & Keyboard Support for Remote Play

### ISSUE THREAD

**Issue by GeorgeSoryal** [redphx/better-xcloud#521]
### Device

Desktop

### Suggestion

I am unsure if this feature is already existing and intended to work or not, but what I am asking for is for a feature for remote play to accept inputs from a mouse and keyboard connected to a windows desktop running remote play instead of exclusively accepting inputs from controllers. 

The problem I am facing is that I will have my desktop running remote play and I will have a mouse and keyboard plugged into the desktop but the desktop will not accept inputs from the mouse and keyboard.

I have turned on native mouse and keyboard on the desktop (by editing the script) but that will not override the limit on mouse and keyboard on remote play. I also tried adding the game title to the *Better xCloud - Custom flags* script on top of the normal x-cloud script but that also did not work when following the instructions. 

I am unsure where to proceed from here, so I am suggesting that this feature of mouse and keyboard inputs being relayed to remote play be added (if possible). Thank you!

**Comment by redphx** [comment]
Dup #218  

It's possible, but difficult to make it work properly when switching between games. I don't have time to look into it yet.
