### ISSUE TITLE
[Bug] remote play framerate isn't smooth

### ISSUE THREAD

**Issue by voxdub** [redphx/better-xcloud#522]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Ayn Odin 2

### Operating System

Android 13

### Android app/Browser Version

App and kiwi browser 

### Better xCloud Version

5.8.4

### Game list

All games 

### Reproduction Steps

Upgraded to 5.8.4, realised framerate isn't smooth when using remote play. Downloading to 5.7.0 resolves issue, not sure which version introduced issue. Issue isn't present when using other apps to play via remote play. Unable to replicate when playing via cloud, issue seems to be only for remote play.

**Comment by redphx** [comment]
Remote Play uses the same code with xCloud, so I don't see why it only happens to RP. Unless you can identity the exact version I can't help.
