### ISSUE TITLE
[Feature] resizing browser window pop-up, when purchasing extra game content.

### ISSUE THREAD

**Issue by LiamAtkins90** [redphx/better-xcloud#523]
### Device

TV

### Suggestion

![Better xCloud_20241013_232132](https://github.com/user-attachments/assets/6835d280-a14b-45ce-96b5-3db895625dca)
This is the view when using an Android TV device, unable to scroll to the bottom, to make a selection. 

Being able to resize this window, will make selecting and purchasing of content feasible on Android TV devices.

**Comment by redphx** [comment]
This is xCloud's bug. You need to report it to them instead.
