### ISSUE TITLE
[Bug] Coop mode not working

### ISSUE THREAD

**Issue by Fernan20881208** [redphx/better-xcloud#524]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

LG 50nano80SQA 

### Operating System

Webos 7

### Android app/Browser Version

I dont know

### Better xCloud Version

Latest 5.8.5

### Game list

Fc 24 AND other cooperative games

### Reproduction Steps

I puto the 2 controles AND only detecta one but y van control this controller with the other teo gamepads

**Comment by Fernan20881208** [comment]
Please help me @redphx

**Comment by redphx** [comment]
This feature doesn't work on the webOS version and will be removed in later version
