### ISSUE TITLE
[Bug] Generic Smart TV Profile: Changed Behaviour

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#527]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

Nvidia Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.22.0

### Better xCloud Version

5.8.5

### Reproduction Steps

Hi ...

I noticed a changed behaviour with the generic "Smart TV" profile.

In the past it gave you the "Smart TV" UI when layout was set to "Default". But now you are getting the "Normal" layout by default. That also shows a close button in the upper right corner of the Guide menu again.

So currently using the "Smart TV" profile will give you the same results as using the "Android TV" profile. As it seems that adding "Smart TV" to the UA agent line doesn't have an effect anymore.

I don't know if you think it's worth spending time to fix this. But maybe you just want to remove the generic "Smart TV" profile now if it doesn't really make a difference anymore using it.

Thanks.

**Comment by redphx** [comment]
Fixed in beta script
