### ISSUE TITLE
[Feature] "Restart Game" Button on the Session Time Out Screen

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#528]
### Device

All devices

### Suggestion

Hi ...

When you are idle for too long (I think more than 5 minutes), your session will be terminated. And then you will see a screen that has two buttons: One to send feedback and another one that will bring you back to the home screen.

But I always missed not having a button that would just start a new gaming session. So I want to suggest to add a "restart game" / "start new session" button on that screen. So you don't have to go back to the home screen first to get back to gaming.

Or maybe as an alternative: I wonder why the xCloud team doesn't let people use the Guide menu on that screen. So you could use the Guide to start the game again (or another one). But maybe "Better xCloud" can make this possible?

Thanks.

**Comment by redphx** [comment]
I think it's better to suggest this feature to the xCloud team.

**Comment by KingNothing81** [comment]
I think just doing a page refresh might do the trick and start a new session for the timed out game. But as you can't access the Guide here, there is no way to do it with the remote / controller. But yes, I can suggest this to the xCloud team using the feedback option.

But talking about the xCloud team and I hope you don't mind the unrelated question: As you always have a look at the website's code, could you tell me if they fixed the issue with the achievement notifications showing up although set to disabled in the notification settings?

Thanks.
