### ISSUE TITLE
[Feature] Increase Xcloud AFK time

### ISSUE THREAD

**Issue by ricardo404** [redphx/better-xcloud#53]
I don't know what the current Xcloud Afk time is, but depending on the game can be too short. Would you have any way to explore the increase in this deadline?

**Comment by redphx** [comment]
I might be wrong but I think the server decides the AFK time.  
Even if it's possible, I'll only add a maximum of 5 more minutes. I don't want users to abuse this AFK feature.

**Comment by Hukolla** [comment]
I don't think it needs to be added. Servers are already loaded in some regions!

**Comment by redphx** [comment]
Yeah, I also don't want to implement this feature. It will make the queue situation worse.

**Comment by nathan130200** [comment]
> I don't think it needs to be added. Servers are already loaded in some regions!

@Hukolla Facts. Brazil server is fully loaded, almost impossible to get queues less than 30 minutes (weekend almost 60 ~ 240 minutes to start an session 💀 ).
