### ISSUE TITLE
[Feature] "Anti inactivity Disconnected" function

### ISSUE THREAD

**Issue by eduxz122** [redphx/better-xcloud#530]
### Device

All devices

### Suggestion

So, what i was thinking would be a nice function to add is the anti discconected by inactivity. 
what do i mean with this?
do you know when you get afk to do something and after 9 minutes it ask if you still here and you dont remember to click "yes" and you get disconected? thats what im talking about. my idea is to implement something that you can activate and, when it show the message that youre gonna be disconected if you dont press the button, it automatically presses the buttor for you. and when youre back again, u can just de-activatte the "AFK Mode" or something like that. 

u could activate it from the menu or select a button that when you press home button(xbox button) + the button you selected it activate the afk mode.

**Comment by redphx** [comment]
No #53
