### ISSUE TITLE
[Feature] Change the colors from the site

### ISSUE THREAD

**Issue by eduxz122** [redphx/better-xcloud#531]
### Device

All devices

### Suggestion

you know that the black and green are the main colors of the xcloud site;
my idea is to have some way to change this.
create a category like
"Color"
and the button to change the first/primary color (black) 
and the button to change the secondary color (green)

as i think that make a new UI or "themes" for the site is to hard and may lag sistems, we could just implement that option to change the color. 
like, i would really like to enter the site with the black and purple or black and red theme.
or maybe, white and red. 
thats the point of it, make the site looks more like we want and make it more customizable.
sorry for bad english.

**Comment by redphx** [comment]
xCloud website will have its own themeing feature
