### ISSUE TITLE
[Feature] add games to desktop(Windows)

### ISSUE THREAD

**Issue by eduxz122** [redphx/better-xcloud#532]
### Device

All devices

### Suggestion

implement a option in the 3 dots that appear in any game to make a desktop shortcut with the game that you want, with the icon and name....
make it open in a new tab just like an "app" (like the xcloud has it own app when you using chrome)

**Comment by redphx** [comment]
Do it manually https://www.wikihow.com/Turn-Your-Favorite-Website-Into-Desktop-Apps-With-Google-Chrome
