### ISSUE TITLE
[Bug] KBM support not working as intended

### ISSUE THREAD

**Issue by ozkanjanberk** [redphx/better-xcloud#533]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Macbook Pro 2019

### Operating System

MacOS Sequoia 15.0

### Android app/Browser Version

Microsoft Edge 130.0.2849.46 

### Better xCloud Version

5.8.6

### Game list

Callisto Protocol

### Reproduction Steps

Before the game starts, there are 3 legal notice that you have to agree to. Could not find any way to accept them. Rebinded keys, pressed every button on the keyboard. I can scroll between tabs but could not manage to accept it. Any help would be gladly appreciated.

### Screenshot/video

<img width="1440" alt="Screenshot 2024-10-21 at 16 25 11" src="https://github.com/user-attachments/assets/233f4c93-b3f2-4b4e-bf3f-137d5d211230">

**Comment by redphx** [comment]
Scroll to the bottom

**Comment by ozkanjanberk** [comment]
> Scroll to the bottom

Tried with arrows, left stick downwards key, right stick downwards key, with mouse, rebinded to different keys. Still no luck. It ain't scrolling.

Edit: Works like a charm in other games btw. Maybe it has something to do with this one particularly.

**Comment by redphx** [comment]
This is the game's problem, not caused by the script
