### ISSUE TITLE
[Bug] Vivaldi Browser black screen doing remote play

### ISSUE THREAD

**Issue by gh0sti** [redphx/better-xcloud#537]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

MacBook Pro 16 in 2019

### Operating System

macOS 15.1

### Android app/Browser Version

Vivaldi 6.9.3447.55/Chrome 128.0.6613.188

### Better xCloud Version

5.9.1

### Game list

Xbox Stream

### Reproduction Steps

1. Launch xbox.com/play
2. Click on stream from console
3. click play
4. rocket animation
5. black screen
6. well be right back and ends the stream

### Screenshot/video

No video
I know my streaming works b/c I did use Brave Browser latest version to stream my xbox just fine. I also don't have ublock origin running on xbox website with vivaldi and I turned off the built in adblocker for vivaldi. Vivaldi is another chromium browser similar to Brave where its a more privacy focus browser. I did try multiple settings within the better xcloud play script and I still get a black screen.

**Comment by redphx** [comment]
#434

**Comment by gh0sti** [comment]
> #434

If you read my info at the bottom, without making any changes to my network config the Brave Browser works just fine on similar setup. Vivaldi is what is breaking the xbox stream. Please let me know what logs I can provide to help assist with figuring out why Vivaldi browser doesn't work for xbox stream.

**Comment by gh0sti** [comment]
> #434

Ok I am sorry here. MacOS I forgot to enable in privacy local network access for Vivaldi Browser. BX works now. Sorry for the issue.

**Comment by jaydp17** [comment]
Thanks @gh0sti for your comment! I was having the same problem with Brave, and your message made me realise I should enable local network access.

@redphx I think it would be helpful to include this in the troubleshooting page for macOS users.
BTW, irrespective of whether we include it in the troubleshooting page or not, thank you for working on better xCloud ❤️
