### ISSUE TITLE
[Bug] Remote play from outside network not working after 5.9.0

### ISSUE THREAD

**Issue by RoligKanin** [redphx/better-xcloud#538]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Lenovo laptop

### Operating System

Windows 11

### Android app/Browser Version

Edge

### Better xCloud Version

5.9.1 and 5.9.1

### Reproduction Steps

First off, thanks for the amazing work you do. You are the reason I love my xbox. Been remoteplaying for a while now from work with Better Xcloud :)

The bug started after upgrading to 5.9.0/5.9.1. I cant remoteplay from cellular/wifi outside my house anymore.
The rocketship flies off, and I get a black screen (nothing more).

Remote play on the same wifi as the xbox works perfectly both with 5.9.0 and 5.9.1, but the second I`m not on the same network i get a black screen.

Downgrading back to 5.8.6 fixes the problem, but I cant set custom m/k inputs. Get an error saying "The requested version (1) is less than the existing version (2), so thats a bummer :)

**Comment by redphx** [comment]
Try this: https://github.com/redphx/better-xcloud/raw/22f1ebdd08c4885b9b4d0e6a13606e27969e6c33/dist/better-xcloud.lite.user.js

**Comment by redphx** [comment]
Fixed in 5.9.2  
Thanks for reporting

**Comment by RoligKanin** [comment]
Thanks! 5.9.2 fixed the issue :)
