### ISSUE TITLE
[Bug] Remote Play not working - Chrome/Edge tab says Fortnite, attempts connection before going back to main screen

### ISSUE THREAD

**Issue by mmmmm913** [redphx/better-xcloud#539]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Dell Laptop

### Operating System

Windows 11

### Android app/Browser Version

Chrome Version 130.0.6723.70 (Official Build) (64-bit)

### Better xCloud Version

5.9.1

### Reproduction Steps

Opened up ports 4838, 5050, 9002 and 50302.  Remote play works outside of home network on Android phone, via official app and XBPlay.  I've enabled Remote Play in Better xCloud, and when trying to connect the Chrome tab reads 'Fortnite', I see the spaceship and Xbox logo, screen goes black for 10 seconds and brings me back to the main Cloud screen.
Interestingly when being logged in via official XBOX app on Android, as soon as I attempt remote play via Better xcloud, it disconnects the XBOX app session as if another session is 'taking over', so it does recognize another remote play session, it just does not connect.

**Comment by redphx** [comment]
Check 5.9.2

**Comment by mmmmm913** [comment]
Thank you! it worked!
