### ISSUE TITLE
[Bug] In-game UI too long on iPhone 8 Safari 16.6

### ISSUE THREAD

**Issue by ILikePlayingGames** [redphx/better-xcloud#54]
![image](https://github.com/redphx/better-xcloud/assets/22475143/d4250c75-60a6-448f-b706-5b9787524b35)

The additional buttons have made the UI too long. Not sure if this also applies to other phones

**Comment by redphx** [comment]
I'll add an option to hide button's labels

**Comment by redphx** [comment]
<img width="652" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/fd032abe-392d-450f-85ac-f5ef0603f4f7">
  
You can test with this dev version: https://github.com/redphx/better-xcloud/raw/feature/simplify_stream_menu/better-xcloud.user.js  

Then enable the "Simplify Stream's menu" settin.

**Comment by ILikePlayingGames** [comment]
Thanks! It fits now
