### ISSUE TITLE
[Bug]  The option press F8 to change keyboard doesnt appear

### ISSUE THREAD

**Issue by Roxana2049** [redphx/better-xcloud#541]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Asus

### Operating System

Linux Mint 22

### Android app/Browser Version

Mozilla Firefox Versión 131.0.3 (64-bits) 

### Better xCloud Version

5.9.2

### Game list

Fortnite

### Reproduction Steps

1. I open any game of gamepass
2. The game starts normal and then appears the option to change of keyboard (F8)
3. The game runs normal
4. But in only fortnite the option doesnt appear
5. even if i tried to prees F8 it doesnt work
6. this error its only on fortnite, i tried to use brave, opera, chrome and everyone has the same issue 

### Screenshot/video

![Captura de pantalla_2024-10-25_15-26-00](https://github.com/user-attachments/assets/f6e1b067-72e6-4ed8-8efe-3289bd280f3c)
![Captura de pantalla_2024-10-25_15-27-19](https://github.com/user-attachments/assets/9dcfe1dc-f897-4721-bcb2-d6b63bb7820b)

**Comment by redphx** [comment]
Fortnite is a native mkb supported game. If you want to use virtual controller, disable native mkb in script's settings

**Comment by Roxana2049** [comment]
Man god bless you, thank you so much
