### ISSUE TITLE
Abiility to disable Press F9 to release the mouse

### ISSUE THREAD

**Issue by sachinpatl** [redphx/better-xcloud#543]
### Device

Desktop

### Suggestion

![image](https://github.com/user-attachments/assets/2487b1d0-ae6a-4b32-8d6c-4366991a1a67)
Enjoying COD BO 6 on my age old laptop with better xcloud.

It's buttery smooth, but when using mouse and keyboard I keep getting this popup during the cut scenes after around 5 seconds of not moving the mouse.

Can we add an ability to disable it in the mouse and keyboard setting.

**Comment by redphx** [comment]
Are you sure this message is from xCloud?  

The xCloud's message is `Press ... to release YOUR mouse`, not `THE mouse`.  

<img width="913" alt="image" src="https://github.com/user-attachments/assets/03ffb51e-b64a-4bb5-9829-895e52715adb">

**Comment by thegroosalugg** [comment]
> Are you sure this message is from xCloud?
> 
> The xCloud's message is `Press ... to release YOUR mouse`, not `THE mouse`.
> 
> <img alt="image" width="913" src="https://private-user-images.githubusercontent.com/96280/380575749-03ffb51e-b64a-4bb5-9829-895e52715adb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1NTE3NDAsIm5iZiI6MTc1NjU1MTQ0MCwicGF0aCI6Ii85NjI4MC8zODA1NzU3NDktMDNmZmI1MWUtYjY0YS00YmI1LTk4MjktODk1ZTUyNzE1YWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODMwVDEwNTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MjA4MGIwZmI4NjYxMjgxOTk5ODI4MDUxZDI1ZDA4N2IzYjMzNzU4NDliMmExZWE4OTIzZDRkOWUzODE1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HDku7vLNGk7L68U54rKKQpljN0pP0sD27YRxJ5IQoqU">

The option to re-map the F9 key to another key is set from the settings menu in Xcloud => press xbox button > gear icon > input > open the guide or interact with notifications. 

So it seems to be coming from xcloud.

I too have been looking for a way to remove this. Whenever I touch my mouse to swap to 2nd screen, or pause the game and touch the mouse this annoying pop-up pops up

**Comment by thegroosalugg** [comment]
> ### Device
> Desktop
> 
> ### Suggestion
> ![image](https://github.com/user-attachments/assets/2487b1d0-ae6a-4b32-8d6c-4366991a1a67) Enjoying COD BO 6 on my age old laptop with better xcloud.
> 
> It's buttery smooth, but when using mouse and keyboard I keep getting this popup during the cut scenes after around 5 seconds of not moving the mouse.
> 
> Can we add an ability to disable it in the mouse and keyboard setting.


Here - this should get rid of it 

```
const style = document.createElement('style');
style.textContent = `
  /* Hide Xbox Cloud Gaming mouse unlock popup */
  div[class^="MouseKeyboardTeachingBubble-module__entireScreen"] {
    display: none !important;
  }
`;
document.head.appendChild(style);
```

I haven't used TamperMonkey myself before, so I'll look into that another time. But for now I just open dev tools after opening the game and pasting this code into the console and the pop up won't show again unless you refresh/open a new window.
