### ISSUE TITLE
[Bug] I can't play with mouse and keyboard

### ISSUE THREAD

**Issue by capassz** [redphx/better-xcloud#544]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Windows

### Operating System

10

### Android app/Browser Version

Chrome 130.0.6723.70 

### Better xCloud Version

5.9.2

### Game list

Forza, farming etc

### Reproduction Steps

After entering the game I can't play with the keyboard

### Screenshot/video

![image](https://github.com/user-attachments/assets/3b136ee7-190e-4596-8482-7e7f5ba83e83)

**Comment by redphx** [comment]
Better xCloud is not running

**Comment by capassz** [comment]
how can i solve this?
![image](https://github.com/user-attachments/assets/b1d1d9d9-76ee-4c24-814e-8913a3d11f20)

**Comment by capassz** [comment]
> Better xCloud is not running
how can i solve this
![image](https://github.com/user-attachments/assets/2a03e2a2-bbd6-4d08-aa40-e9678939e0e8)
