### ISSUE TITLE
[Bug] the screen goes white, then comes back to a game, and the game runs with too much delay and lag

### ISSUE THREAD

**Issue by mqrmq** [redphx/better-xcloud#545]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Lenovo Ideapad Slim i5

### Operating System

Windows 10

### Android app/Browser Version

Chrome 130.0.6723.70

### Better xCloud Version

5.9.2

### Game list

All Games

### Reproduction Steps

1. Open Game
2. I play for a few minutes, usually 20 or 30
3. The bug occurs unexpectedly, it does not occur in an approximate time, it appears unexpectedly, the game is as if it restarts, the screen goes blank, then the image appears again and when the image appears again the game behaves with an incredible delay, and with too much lag which makes it impossible to play, I have to exit the game and re-enter for it to be solved, but that means losing all my progress and it is frustrating.

### Screenshot/video

https://github.com/user-attachments/assets/820c784b-40af-4b85-a481-8f72dcbc55d4
Here is a video of what happens, I was recording the entire moment while playing Fortnite, after an unexpected moment the game goes blank, and when it appears again and gives the image it behaves with a lot of delay and I just had to close the game, and reopen it so that it works normally again, which makes it very frustrating, and it is annoying to do that every time it happens since sometimes in moments when I play and I am in a fight or in the middle of a game, that usually happens and I have to hide and Praying so they don't kill me is too frustrating to be honest.

**Comment by redphx** [comment]
This is problem with your device or Chrome. Make sure it's not using CPU to render the video #433

**Comment by mqrmq** [comment]
I disabled hardware acceleration in Google and it was worse, I was lagging without doing anything, and the problem only occurs when I play with the Controller and when I play with the controller connected to a cable with the PC, but when I don't play with the Connected cable does not cause the problem, but I have to play with the cable because otherwise the controller is useless.

**Comment by mqrmq** [comment]
> This is problem with your device or Chrome. Make sure it's not using CPU to render the video #433

I disabled hardware acceleration in Google and it was worse, I was lagging without doing anything, and the problem only occurs when I play with the Controller and when I play with the controller connected to a cable with the PC, but when I don't play with the Connected cable does not cause the problem, but I have to play with the cable because otherwise the controller is useless.
