### ISSUE TITLE
[Bug] Controller emulation via Keyboard doesn't work in Ni no Kuni II: Revenant Kingdom

### ISSUE THREAD

**Issue by magicsgram** [redphx/better-xcloud#546]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

MacBook M1

### Operating System

MacOS 15.0.1 (24A348)

### Android app/Browser Version

Microsoft Edge	130.0.2849.56 (Official build) (arm64)

### Better xCloud Version

5.9.3

### Game list

Ni no Kuni II: Revenant Kingdom

### Reproduction Steps

1. Set to emulate the controller via keyboard/mouse
2. Launch Ni no Kuni II: Revenant Kingdom
3. The game does NOT respond to my keyboard input at all.
4. I can still press the key assigned to the 'guide button' and it opens the blade to the left. So it's prob not the xcloud system, it's prob the game itself that's not registering my emulated inputs.
5. No other game (that I've tried) is showing the same problem.

Please note that, the forced 'touch' input when tried from my phone works well. It's only when I try from the desktop browsers and use the controller emulation via keyboard.

When tried launching the same game via 'remote' to my own console, I see a mouse cursor shows up on a screen, which is weird. So I think the game's native support for kb/mouse is conflicting w/ the emulation or something.. IDK.

**Comment by redphx** [comment]
Works fine for me, both controller and virtual controller. Make sure the local co-op setting isn't enabled.

**Comment by magicsgram** [comment]
> Works fine for me, both controller and virtual controller. Make sure the local co-op setting isn't enabled.

Works! Confirming that local coop wasn't enabled.
I guess other singleplayer games worked w/ that feature flag on, so I just thought that would ever cause an issue.

Thank you so much!

**Comment by redphx** [comment]
When enabling the local co-op feature, the virtual controller will be registered as controller `#3`
