### ISSUE TITLE
[Bug] The 'server name' does not appear for me, that is, I can not configure my better xcloud

### ISSUE THREAD

**Issue by HQ672** [redphx/better-xcloud#549]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

notebook

### Operating System

windows 11

### Android app/Browser Version

microsoft edge

### Better xCloud Version

5.9.4

### Game list

the keyboard and mouse function works even without the server name appearing, which indicates that the script still works but I can't configure it

### Reproduction Steps

I don't know, it just didn't show the SERVER NAME

### Screenshot/video

![Captura de tela 2024-05-13 062751](https://github.com/user-attachments/assets/f3d175b2-2b3f-42bb-8c6f-e3a475b7d25f)

**Comment by HQ672** [comment]
I ended up leaving a wrong screenshot sorry
![Captura de tela 2024-11-02 202105](https://github.com/user-attachments/assets/21f381bc-c5bc-48f7-99b1-768aa986109a)

**Comment by btncua** [comment]
### Do [this](https://better-xcloud.github.io/troubleshooting/)

**Comment by btncua** [comment]
- ### #506
