### ISSUE TITLE
[Bug] Additional Buttons In The Guide Menu Are Missing

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#551]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Nvidia Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.22.0

### Better xCloud Version

5.9.4

### Reproduction Steps

Hi ...

Yesterday I noticed that the additonal buttons in the Guide menu don't show up anymore, e.g. the green "Better xCloud" button, reload page and so on.

The buttons are missing when you are on the home page and during gameplay.

So I guess there was an update to the xCloud website that broke the integration of the Guide buttons.

Thanks.

**Comment by redphx** [comment]
Fixed in Beta script. Thanks.
