### ISSUE TITLE
[Bug] PS5 controller not working

### ISSUE THREAD

**Issue by Jgotta** [redphx/better-xcloud#552]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Nvidia Shield 2017 Model

### Operating System

11

### Android app/Browser Version

5.9.4

### Better xCloud Version

5.9.4

### Game list

All Games

### Reproduction Steps

 I tried to use my PS5  controller with the Better Xcloud, but I couldn't play with it because the buttons didn’t work. I followed the instructions in the ADB app, but they are still not working properly. Can someone help me?

**Comment by redphx** [comment]
This is your device's problem
