### ISSUE TITLE
[Bug] Can't use native mkb on pc

### ISSUE THREAD

**Issue by entitybtw** [redphx/better-xcloud#553]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Pc/Laptop

### Device

Honor Magicbook x14 (FRI-F56)

### Operating System

Linux, Gentoo

### Browser Version

Brave Version 1.71.123 Chromium: 130.0.6723.116 (Official Build) unknown (64-bit)

### Better xCloud Version

5.9.5

### Game list

Fortnite

### Reproduction Steps

Can't use native mkb in Fortnite, I tried commenting two lines in script, now keyboard, mouse scroll, right click, left click works, but mouse moving don't works

### Screenshot/video

![image](https://github.com/user-attachments/assets/24fb3911-172c-47ce-8f8d-dca8d53d89c9)

**Comment by redphx** [comment]
> The bug doesn't happen when I disable Better xCloud script.  

did you try disabling Better xCloud?

**Comment by entitybtw** [comment]
> > The bug doesn't happen when I disable Better xCloud script.
> 
> did you try disabling Better xCloud?

yeah, i can try doing that again

**Comment by entitybtw** [comment]
> > > The bug doesn't happen when I disable Better xCloud script.
> > 
> > 
> > did you try disabling Better xCloud?
> 
> yeah, i can try doing that again

Sooo, i tried, and without better xcloud it working, but it slow cuz i using vpn(my country doesn't in xbox game cloud support list) what should i do?

**Comment by entitybtw** [comment]
> > > > The bug doesn't happen when I disable Better xCloud script.
> > > 
> > > 
> > > did you try disabling Better xCloud?
> > 
> > 
> > yeah, i can try doing that again
> 
> Sooo, i tried, and without better xcloud it working, but it slow cuz i using vpn(my country doesn't in xbox game cloud support list) what should i do?

rn i tried setting native mkb in better xcloud settings to default, and yeah - it started working.-.

**Comment by entitybtw** [comment]
ty for helping.-.
