### ISSUE TITLE
[Bug] Remote play "Calculating update size" popup doesn't update once size is calculated

### ISSUE THREAD

**Issue by modemman11** [redphx/better-xcloud#557]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

Dell Desktop

### Operating System

Windows 10

### Android app/Browser Version

Edge 130.0.2849.80

### Better xCloud Version

5.9.5

### Game list

Any

### Reproduction Steps

Not sure if this is a Xbox issue or Better Xcloud issue but here we go.

I have auto updates turned off on my console. 

When using Remote Play via the official Xbox Apps, I can go to launch a game with an update, and it'll say the usual "Update is available, you need it to play. Calculating update size..." Or whatever the phrasing is. Specifically, the "Calculating update size" part of the message then changes a few seconds later to display the actual size of the download, without me clicking anything. 

When doing the same actions when using better xcloud in Edge, you get a different web-based popup in your browser with the same text. However, the "Calculating update size" does not update on this popup after the download size is calculated. If I wait a few seconds, then click cancel to close the popup, and then click the game again to bring the popup back up, the correct file size is displayed.

**Comment by redphx** [comment]
This is a bug from xCloud. Since Remote Play is not a public feature I doubt they will ever fix it. And I don't plan to fix it because it rarely happens (I never ran into it).
