### ISSUE TITLE
[Bug] Keyboard and mouse not working

### ISSUE THREAD

**Issue by Carlos114820** [redphx/better-xcloud#558]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

TV LG webOS 22

### Operating System

 Linux-based,

### Android app/Browser Version

I use the app I downloaded

### Better xCloud Version

5.7.8

### Game list

I can't get into any

### Reproduction Steps

Open Better

### Screenshot/video

I'm using version 5.7.8 dwebOS, and when I play with keyboard and mouse, I don't see any option to use them. Also, I can't get into the game because I need to connect a controller, but I'm not able to do that.

**Comment by redphx** [comment]
https://github.com/redphx/better-xcloud-tv/issues/10
