### ISSUE TITLE
[Bug] The touch panel on my PS4 controller does not work

### ISSUE THREAD

**Issue by mqrmq** [redphx/better-xcloud#560]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Lenovo Ideapad Slim i5

### Operating System

Windows 10

### Android app/Browser Version

Chrome 130.0.6723.70

### Better xCloud Version

5.9.5

### Game list

All Games

### Reproduction Steps

I know this is not a bug but I want to try to know how to solve it, I can't use my touch panel because it takes screenshots, I would like to know a way to disable the screenshots or change the button because I really don't want to use it in games like Fortnite, but no I can because it takes photos and those photos sometimes cause me a delay, it's a little uncomfortable, and I can't find any configuration that tells me to deactivate it

**Comment by redphx** [comment]
The touchpad maps to the screenshot button on Windows. Even if you disable the screenshot feature it won't have the same function as when using on PS.

**Comment by mqrmq** [comment]
I am mapping the ps4 panel to an xbox button with DS4WINDOWS, but the
problem is that the button that I assign to it works, but it takes
screenshots and I want to disable the function to take screenshots in
xcloud, since I use a custom operating system and It disables many things,
but the problem is with xcloud better, and I want to disable it.

**Comment by mqrmq** [comment]
I am mapping the ps4 panel to an xbox button with DS4WINDOWS, but the problem is that the button that I assign to it works, but it takes screenshots and I want to disable the function to take screenshots in xcloud, since I use a custom operating system and It disables many things, but the problem is with xcloud better, and I want to disable it.

**Comment by redphx** [comment]
Edit script in Tampermonnkey, replace `currentGamepad.buttons[17] && currentGamepad.buttons[17].pressed` with `false`
