### ISSUE TITLE
[Bug] From my Android TV I have tried to connect my DualShock 4 (PlayStation 4 controller) and it does not detect it

### ISSUE THREAD

**Issue by rauulvicentee** [redphx/better-xcloud#562]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

Xiaomi TV p32

### Operating System

Android 11

### Android app/Browser Version

Without

### Better xCloud Version

0.22.0

### Game list

Fortnite (The only one I tried )

### Reproduction Steps

I connected the controller and opened the game, it loaded correctly but the controller does not work. It was not detected in the menu either.

**Comment by redphx** [comment]
https://www.xda-developers.com/android-11-trouble-getting-games-recognize-their-controllers/
