### ISSUE TITLE
[Feature] Hide “Play your own games” section

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#567]
### Device

All devices

### Suggestion

Hi …

The “play your own games” feature is finally there.

But at the moment I don’t own any games on the Xbox store yet. And as a cloud only user without a Xbox console, I also have no plans to start buying games now.

So I would be happy if you could add the ability to hide the new “play your own games” section on the home screen with one of the next updates.

Thanks.

**Comment by madebyaris** [comment]
Hi @KingNothing81 , that's would be a great idea, so the other folks will not confuse about it.

I already build this function, and will pull-request to it.
I'm thinking to add icon that says "need to own", on all game section.

![image](https://github.com/user-attachments/assets/f804f824-d2d7-437e-81f1-073aaf3222b6)

**Comment by KingNothing81** [comment]
@madebyaris I'm happy to see that I'm not the only one that would like to hide something so many have been waiting for. ;)

But I don't know if we need an extra mark for the games you need to own, as the games included in Game Pass already show a little GP icon in the bottom left corner. And it's missing for the games you need to own.

![388842222-44236f50-89ec-4bb6-af16-0c5ed0b9f9d3](https://github.com/user-attachments/assets/3bb78ab9-38d4-441f-bcdb-d2a05866c735)

But what I would like to see is that you can set a filter in the all games section that just hides the games you need to own, so it only shows the games included in GP.

**Comment by redphx** [comment]
Version 6.0 will have a new setting that disable this feature on both Home & All games pages.

<img width="428" alt="image" src="https://github.com/user-attachments/assets/85decbc2-d8e0-464e-a471-aac177d72628">

**Comment by KingNothing81** [comment]
@redphx Thanks. That's great. I wonder if it might need an explanation text, so people will know that it will also hide games in the "all games" section? Or how about calling it something like "Game Pass Only Mode"?

**Comment by redphx** [comment]
Added in 6.0
