### ISSUE TITLE
[Feature] Text Input Box removal

### ISSUE THREAD

**Issue by Sus002** [redphx/better-xcloud#570]
### Device

Desktop

### Suggestion

Hello, I’m facing an issue with the text input box that appears when you try to write something in-game. In MSFS 2024, when I press on a search bar to type something, the text box pops up normally—no issues there. The problem is that the game requires me to choose from a list of similar results to proceed. However, when I type what I need, no options appear. If I click the search bar again, the options show up, but I can’t select the one I want because the text box doesn’t let me. Additionally, if I press B on the controller to go back, the options disappear. Maybe adding an option to disable the text box would help since the game already supports keyboard input.

[screen-capture.webm](https://github.com/user-attachments/assets/a2673d5a-fa50-478c-817e-399950e49e11)

**Comment by btncua** [comment]
- ### #422

**Comment by Sus002** [comment]
In my case, what would you suggest I do? I can still type with the keyboard directly in-game, but in that specific search bar, when I go back, the options disappear. However, in other search bars, this doesn’t happen, so I can type with my keyboard. So is there any any solution?

**Comment by btncua** [comment]
### Report on [/r/xcloud subreddit](https://reddit.com/r/xcloud/)
