### ISSUE TITLE
[Bug] Can't play genshin without touchscreen

### ISSUE THREAD

**Issue by k22405572** [redphx/better-xcloud#573]
### Checklist

- [x] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Desktop

### Device

PC

### Operating System

Windows 11

### Android app/Browser Version

Edge 131.0

### Better xCloud Version

5.9.7

### Game list

Genshin Impact

### Reproduction Steps

1. Set the video aspect ratio to 16:9 or other ratios
2. Open Genshin Impact on PC or TV
3. Automatically switch to touch play
4. Can’t control without touch screen

Solution:
1. Set the video aspect ratio to "Stretch"

**Comment by redphx** [comment]
I don't have this problem in 6.0

**Comment by redphx** [comment]
Most likely xCloud's bug
