### ISSUE TITLE
[Bug] Black screen on WebGL2

### ISSUE THREAD

**Issue by programista-zacny** [redphx/better-xcloud#576]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [x] xCloud officially supports my country/region.
- [x] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Laptop

### Device

Lenovo Thinkbook 16

### Operating System

Manjaro Linux

### Android app/Browser Version

Google Chrome 131.0.6778.85

### Better xCloud Version

5.9.7

### Game list

Halo Inifite

### Reproduction Steps

I'm using Manjaro Linux with KDE Plasma 6.2.4 on Wayland.
AMD Ryzen 5 7530U with Radeon Graphics.

My Chrome flags:
```
--ignore-gpu-blocklist
--enable-zero-copy
--ozone-platform-hint=wayland
--use-gl=angle
--use-angle=vulkan
--enable-accelerated-video-decode
--enable-features=AcceleratedVideoDecodeLinuxGL,VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,UseMultiPlaneFormatForHardwareVideo
```
`chrome://gpu/`
```
Graphics Feature Status
=======================
*   Canvas: Hardware accelerated
*   Canvas out-of-process rasterization: Enabled
*   Direct Rendering Display Compositor: Disabled
*   Compositing: Hardware accelerated
*   Multiple Raster Threads: Enabled
*   OpenGL: Enabled
*   Rasterization: Hardware accelerated
*   Raw Draw: Disabled
*   Skia Graphite: Disabled
*   Video Decode: Hardware accelerated
*   Video Encode: Software only. Hardware acceleration disabled
*   Vulkan: Enabled
*   WebGL: Hardware accelerated
*   WebGL2: Hardware accelerated
*   WebGPU: Disabled
*   WebNN: Disabled
```

Default render is working, switching to WebGL2 gives black screen when the game is running.
Loading screen is working without any problem.

### Screenshot/video

[Nagranie ekranu_20241201_161023.webm](https://github.com/user-attachments/assets/443cb87f-97ce-4564-8c75-dad6bd203d74)

**Comment by redphx** [comment]
check chrome devtools for errors

**Comment by programista-zacny** [comment]
![image](https://github.com/user-attachments/assets/453105e4-3478-46a1-ab3b-b8e14e76c0b9)

**Comment by programista-zacny** [comment]
I have made some research and looks like it's a problem on the line: Linux - Kernel - GPU drivers - Wayland - Vulkan - Chrome.
@redphx you can close this issue. Sorry for inconvenience.
