### ISSUE TITLE
[Feature] better geforce now?

### ISSUE THREAD

**Issue by soyangelromero** [redphx/better-xcloud#578]
### Device

All devices

### Suggestion

Guys, I know this may not be the best space to suggest this, but I haven't found another place to ask this.

It would be immensely good if you would create a 'better geforce now', that service has really bad app, it also has absurd regional locking. It would be great if you could create an app like this for it.

Thank you in advance.

**Comment by redphx** [comment]
I dont use GFN so I don't have plan to work on it
