### ISSUE TITLE
[Feature] Get higher bitrates with the “Samsung TV” UA profile

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#579]
### Device

All devices

### Suggestion

Hi …

Triggered by that post on Reddit …

https://www.reddit.com/r/xcloud/comments/1h6ehvj/398_mbps_bitrate_on_samsung_tv/

… I played around with the BxC UA settings. 

And found out that I can also get bitrates above 15 Mb/s by using the “Samsung Smart TV” UA profile. But only if “target resolution” and “visual quality” is set to “default”. Like this I’m seeing bitrate peak values up to around 20 Mb/s. 

I only have a 50 Mb/s internet connection. So I don’t know if users with a faster connection might be able to get even higher values this way.

But as mentioned: This only works if resolution and visual quality is kept on “default”. When setting anything else here, the 15 Mb/s cap seems to be in place again.

So I think at the moment BxC is forcing 1080p@High on unsupported devices by claiming to be a Windows PC. But maybe you want to change this, so BxC identifies as a Samsung TV. And all users can benefit from the higher bitrates.

Thanks.

**Comment by redphx** [comment]
Thanks for letting me know. Added in 6.0.0-beta-3

**Comment by KingNothing81** [comment]
Also did a post about this on Reddit:

https://www.reddit.com/r/xcloud/comments/1h6voq6/get_higher_bitrates_with_better_xcloud_and_the/

Because I’m curious what bitrates others will get like this.

But do you happen to know if this is something new? Or could it be that Samsung TVs always got higher bitrates?
