### ISSUE TITLE
[Feature]  720 HQ bitrate

### ISSUE THREAD

**Issue by MotorStorm891** [redphx/better-xcloud#580]
### Device

All devices

### Suggestion

Hi, 1080 HQ is a great feature. Could you had a high bitrate  too for 720. I'm using your app on my Nintendo switch. There is an Android partition ( android 11) on it. Yes, it's true:) . Better X-cloud app works well. The screen cap to 720 in handle and when I set 1080 normal mode on better x-cloud, fps is only at 30 even if I've setted 60 fps (limitation of the wifi ?) But graphics definition are better.

 So could you had a 720 HQ with a better bitrate ?

I'm using Moonlight app  to stream my PC on my Nintendo switch directly. Not using the android partition. It works very well.  
Is it possible possible to port Better X-cloud app in native for Nintendo Switch like for Moonlight ?

**Comment by redphx** [comment]
Only xCloud can add this
