### ISSUE TITLE
[Feature] Add the option to adjust the screen to the top

### ISSUE THREAD

**Issue by Zhuofei-Wang** [redphx/better-xcloud#583]
### Device

Phone/Tablet

### Device name

mi mix fold 4

### Android Version

15

### Suggestion

Thank you for your excellent work！For fold screen or other screens with square proportions, I hope there is an option to place the screen at the top so that there is more space below to place the virtual controller

**Comment by redphx** [comment]
you need to provide a mockup screenshot

**Comment by Zhuofei-Wang** [comment]
![1733455967461](https://github.com/user-attachments/assets/b5c0d063-48b3-400c-99db-fd85e697a659)

**Comment by redphx** [comment]
How does it look on your phone at the moment?

**Comment by Zhuofei-Wang** [comment]
![Screenshot_2024-12-06-11-23-31-459_com redphx betterxc](https://github.com/user-attachments/assets/012df58f-6348-4401-a8d4-41aa809c34aa)

**Comment by redphx** [comment]
Added in beta: https://github.com/redphx/better-xcloud/raw/refs/heads/typescript/dist/better-xcloud.user.js

**Comment by redphx** [comment]
Added in 6.0.1
