### ISSUE TITLE
[Bug] Remote Play outside home

### ISSUE THREAD

**Issue by andcortez** [redphx/better-xcloud#584]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Phone/Tablet

### Device

Samsung Galaxy S23 Plus

### Operating System

Android 14

### Android app/Browser Version

Android App 0.22.0

### Better xCloud Version

6.0

### Game list

Remote Play gaming

### Reproduction Steps

Hello, I'm attempting to use remote play outside my home, but it doesn't initiate properly. Only the Xbox boot logo appears, and then the screen freezes with a black image. I've tested it within my home (local network) where it functions well, but outside of my home (using mobile data or Wi-Fi), the remote play fails to operate as expected. Note: The Xbox app functions normally.

**Comment by redphx** [comment]
#434
