### ISSUE TITLE
[Feature] Can you get the xbox to recognize the microphone/headset connected to the pc in 'Remote Play'? 

### ISSUE THREAD

**Issue by soyangelromero** [redphx/better-xcloud#585]
### Device

Desktop

### Suggestion

Well, that's it. It would be nice if 'Better Xcloud' could make the microphone/headset connected to the pc be recognized by the xbox in 'remote play'. 

It would be good because xbox only recognizes few headsets.

**Comment by redphx** [comment]
not possible
