### ISSUE TITLE
[Feature] hide 8-dot tab

### ISSUE THREAD

**Issue by CincoQuallity** [redphx/better-xcloud#587]
### Device

All devices

### Suggestion

There’s an 8-dot tab in the upper left hand corner when in game. Would it be possible to hide that tab or maybe change its opacity? 

Maybe tapping the upper left hand corner, when it’s hidden, would reveal it again. Then it would disappear again after a few seconds.

I’m not sure if any of this is even possible, but I figured I’d ask. I think the ability to hide that tab would provide a cleaner image. Also, I’m not a fan of those constant white dots when playing on an OLED screen.

![IMG_9948](https://github.com/user-attachments/assets/4636a0b8-2da9-430d-aff1-2a60f8ded285)

**Comment by btncua** [comment]
![2024-12-07](https://github.com/user-attachments/assets/6ebacefc-ecf3-4e1b-be0b-a53a0578ecdc)

**Comment by CincoQuallity** [comment]
> ![2024-12-07](https://private-user-images.githubusercontent.com/166375403/393545283-6ebacefc-ecf3-4e1b-be0b-a53a0578ecdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MDQyMDAsIm5iZiI6MTczMzYwMzkwMCwicGF0aCI6Ii8xNjYzNzU0MDMvMzkzNTQ1MjgzLTZlYmFjZWZjLWVjZjMtNGUxYi1iZTBiLWE1M2EwNTc4ZWNkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QyMDM4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGVlMDJiYjc2NTYyYmM4ZDllNWJmYmI0MTA5NWVmMzg2MjViOTc1NjFmZTdkOWI4MjliZjNjYTY3YjYzMTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vud33jQBFRjyLfs-c5et2tmV80QXEhulwlir0u0n6dw)

Oh, this already exists? Ha, go figure. Thanks for the info. It’s not hard to tell that I’ve only recently downloaded this miracle app.

I asked about this feature in one of the Better xCloud reddit posts and no one responded, so I assumed it might not be implemented yet.
