### ISSUE TITLE
[Bug] Mouse cursor not showing in native MKB game

### ISSUE THREAD

**Issue by welintons2** [redphx/better-xcloud#588]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Phone/Tablet

### Device

Motorola G52

### Operating System

Android 13

### Android app/Browser Version

Chrome 131.0.6778.104

### Better xCloud Version

0.22.1

### Game list

Call Of Duty Warzone, Call Of Duty Black Ops 6, Call Of Duty Modern Warfare 3

### Reproduction Steps

My Better Xcloud has a problem where the mouse pointer does not appear in the game (Black Ops 6/Warzone/Modern Warfare 3), this bug did not happen in the previous version, I don't know how to solve it.. This bug did not happen in the previous version (0.22.0) but in the current version (0.22.1) it is happening 😔

**Comment by welintons2** [comment]
I hope there is a solution to this "problem" as soon as possible.

**Comment by redphx** [comment]
fixed in 6.0.2

**Comment by welintons2** [comment]
> corrigido em 6.0.2

Could you send me the link?
