### ISSUE TITLE
[Bug] Sliders Don’t Work When Using Controller

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#591]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Nvidia Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.22.2

### Better xCloud Version

6.0.3

### Reproduction Steps

Hi ...

Since the last update - I don't know if app or script, as I updated both at once - the opacity slider in the stream stats settings doesn't work anymore.

It always shows "50%" (minimum value) for me. And trying to change the value with the slider doesn't have an effect. It keeps showing "50%" and the opacity doesn't change.

Thanks.

**Comment by KingNothing81** [comment]
Hm … today the slider is working normal again. 

Sorry … I tried this several times yesterday, also with closing the app in between before I opened an issue.

But I guess it was just a temporary glitch on my side and I close this again.

**Comment by KingNothing81** [comment]
Hi …

Unfortunately I have to reopen this issue.

Because now I noticed that this affects all sliders, not just the opacity slider in the stream stats settings. But it only happens when I use the controller to interact with the sliders.

Here is a video when using the controller:

https://github.com/user-attachments/assets/4c49fafb-b7b3-420b-8ac1-0909a59290bc

As you can see, I can move the sliders just fine. But the value shown above doesn’t change.

And this video is with using my remote:

https://github.com/user-attachments/assets/96f1f875-f3e4-4d2f-86a2-1d0a4bebb1ba

When using the remote, all sliders work as expected, changing the value when I move the slider.

So at the moment I can’t use the controller to adjust settings with sliders, but just my remote.

To troubleshoot, I already tried to use the “clear data” option in the app. And also deleted all app data in the Android settings. But with no effect.

Thanks.

**Comment by redphx** [comment]
Fixed in beta. Thanks.
