### ISSUE TITLE
[Feature] Ability to use it on any sites

### ISSUE THREAD

**Issue by Spidey90** [redphx/better-xcloud#592]
### Device

Desktop

### Suggestion

Can you make it so that I can use this better xcloud in any website i want to. There is an emulator I am trying to use which is a website but runs the game locally. All the other online emulators are too laggy due to my internet. I am just wondering if you are able to make this extension work on any site, like https://ds.44670.org/. Thank you in advance

**Comment by redphx** [comment]
Impossible
