### ISSUE TITLE
[Bug] Better options menu won't open

### ISSUE THREAD

**Issue by NatanaelRM** [redphx/better-xcloud#593]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

Realme TV stick

### Operating System

Android TV 11

### Android app/Browser Version

0.22.2

### Better xCloud Version

6.0.4

### Reproduction Steps

1. I open any game
2. I press the hone button on the controller 
3. I press "BETTER XCLOUD" to open the script options and it doesn't open

### Screenshot/video

https://github.com/user-attachments/assets/5cd41c35-2e53-4972-b7a2-fe7fbefcb598

**Comment by redphx** [comment]
Fixed in 6.0.5
