### ISSUE TITLE
[Bug] BxC Button In Guide Menu Stopped Working & Compact Button Layout Used With Smart TV Profiles

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud#594]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

NVIDIA Shield TV

### Operating System

Android TV 11

### Android app/Browser Version

0.22.2

### Better xCloud Version

6.0.4

### Reproduction Steps

Hi …

I think the last update to the xCloud website caused two issues with the Guide menu:

- The green BxC button doesn’t open the settings anymore, just closes the Guide menu.

- For the Smart TV profiles the compact button layout is still used when “Layout” is set to “Normal”. Which makes it impossible to change between the home/refresh/quit buttons, as pressing left/right will just switch to the next tab in the Guide menu.

Thanks.

P.S.: And many additional thanks for adding an option to disable the achievement notifications. Now I can stop blocking URLs in my router. That’s really appreciated. =)

### Screenshot/video

https://github.com/user-attachments/assets/65e062ad-abff-4400-943d-a13369b15541

**Comment by redphx** [comment]
Fixed in 6.0.5
