### ISSUE TITLE
[Bug] does not recognize Gamepad

### ISSUE THREAD

**Issue by gabesantanna** [redphx/better-xcloud#596]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [x] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

Mi Stick TV, Smart TV LG

### Operating System

Android 

### Android app/Browser Version

I don't know

### Better xCloud Version

current version

### Reproduction Steps

When opening the game it does not recognize the gamepad. Even clicking on the gamepad icon and trying to pair, nothing happens.

This does not happen in the official Xcloud app, nor does it happen without the script

**Comment by redphx** [comment]
xCloud's bug

**Comment by gabesantanna** [comment]
This does not happen in the official Xcloud app, nor does it happen without the script
