### ISSUE TITLE
[Bug] Game cover waiting time

### ISSUE THREAD

**Issue by NatanaelRM** [redphx/better-xcloud#597]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

Realme TV stick

### Operating System

Android TV 11

### Android app/Browser Version

0.22.2

### Better xCloud Version

6.0.5

### Reproduction Steps

The waiting time no longer appears on the game cover in this latest version.

**Comment by redphx** [comment]
Fixed in 6.0.6  
Thanks.

**Comment by RudyBugy** [comment]
> Fixed in 6.0.6

The setting for displaying the queue waiting time has never worked for me, neither before version 6.0.6 nor after.

The option on the loading screen show the estimated wait time has also never worked.

I live in an unsupported region, I use a desktop PC, Windows 7, Chrome browser 109.0.5414.120, script version 6.0.6 and all previous versions.
