### ISSUE TITLE
[Bug] MOUSE WHEEL BUG

### ISSUE THREAD

**Issue by Sofyanes2** [redphx/better-xcloud#600]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### xCloud officially supports your country/region

Yes

### The bug doesn't happen when you disable Better xCloud script

No

### Previous Better xCloud versions didn't have this bug (name which one)

No

### Device

Phone/Tablet

### Device

Xiaomi Pad 6

### Operating System

Android 14

### Android app/Browser Version

Chrome 131.0.6778.135

### Better xCloud Version

6.0.6

### Game list

Fortnite

### Reproduction Steps

1.Activate the keyboard and mouse function as well as version forcing for the console on Fortnite.

2.With the scroll wheel reset, you edit the construction.

3.It executes 40 times per millisecond, whereas normally it should only execute once, and when I move the mouse, it multiplies by 40.
(Also, I’m using the Better XCloud app.)

### Screenshot/video

https://github.com/user-attachments/assets/7873e232-61f7-4f52-ac50-182f5272e8bd

**Comment by redphx** [comment]
Fixed in 6.1.1
