### ISSUE TITLE
[Bug] Controller not working

### ISSUE THREAD

**Issue by mathfrei** [redphx/better-xcloud#601]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### xCloud officially supports your country/region

Yes

### The bug doesn't happen when you disable Better xCloud script

No

### Previous Better xCloud versions didn't have this bug (name which one)

Yes

### Device

Desktop

### Device

PC

### Operating System

Windows 11

### Android app/Browser Version

edge 131.0.2903.99 (Compilação oficial) (64 bits)

### Better xCloud Version

6.0.6

### Game list

Call Of Duty Black Ops 6

### Reproduction Steps

This happens  often.
Mouse just don't work.
No configuration in game can change it (It's already on mouse option).
My only way it's to restart and enter the qeue of Xcloud all again.
But mouse to access Xbox hub works.

### Screenshot/video

Youtube video link:
https://youtu.be/-Y9WMR5GBXQ

**Comment by redphx** [comment]
xCloud bug
