### ISSUE TITLE
[Bug] Some functions are missing when minimizing the Android app 

### ISSUE THREAD

**Issue by akmodzs** [redphx/better-xcloud#603]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### xCloud officially supports your country/region

Yes

### The bug doesn't happen when you disable Better xCloud script

No

### Previous Better xCloud versions didn't have this bug (name which one)

No

### Device

Phone/Tablet

### Device

Xiaomi POCO X3

### Operating System

Android 15

### Android app/Browser Version

0.22.2

### Better xCloud Version

6.0.6

### Game list

Indiana Jones, Farming Simulator 22

### Reproduction Steps

I choose the game. It stays in a queue. I go to another app until the queue is complete. I return to BX and some of the buttons disappear from the interface, as seen in the screenshot below. 

### Screenshot/video

![Screenshot_20241214-135750](https://github.com/user-attachments/assets/4ade7657-15bb-43ce-be2e-fe77b1102343)

**Comment by redphx** [comment]
Just refresh the stream
