### ISSUE TITLE
[Bug] WITH THE SCREEN MODE

### ISSUE THREAD

**Issue by xddsda** [redphx/better-xcloud#604]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### xCloud officially supports your country/region

Yes

### The bug doesn't happen when you disable Better xCloud script

No

### Previous Better xCloud versions didn't have this bug (name which one)

No

### Device

Laptop

### Device

asus

### Operating System

windows 10

### Android app/Browser Version

chrome

### Better xCloud Version

newest

### Game list

fortnite

### Reproduction Steps

**when i put stretched mode on my screen when i do full screen it comes back to normal**

**Comment by redphx** [comment]
Can't reproduce the bug

**Comment by xddsda** [comment]
i have another bug with tampermonkey it says blacklisted due to security settings and it dosnt work the script
