### ISSUE TITLE
[Bug] I can't use the script

### ISSUE THREAD

**Issue by yurinho14** [redphx/better-xcloud#605]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### xCloud officially supports your country/region

Yes

### The bug doesn't happen when you disable Better xCloud script

No

### Previous Better xCloud versions didn't have this bug (name which one)

No

### Device

Laptop

### Device

Notebook

### Operating System

Windows 10

### Android app/Browser Version

Microsoft Edge

### Better xCloud Version

6.0.6

### Game list

All

### Reproduction Steps

I installed the extension, and soon after, the script, but when I open the www.xbox.com/play it doesn't appear next to my profile picture so I can configure my better xCloud.

### Screenshot/video

![image](https://github.com/user-attachments/assets/2d281a29-93f5-44e7-ac00-8fcca6fcec0d)

**Comment by redphx** [comment]
https://better-xcloud.github.io/troubleshooting/
