### ISSUE TITLE
[Feature] tvOS Support

### ISSUE THREAD

**Issue by netwarex** [redphx/better-xcloud#607]
### Device

TV

### Suggestion

There are some options for tvOS browser support like this: https://github.com/Moballo-LLC/tvOS-Browser

Would it be possible to create a sideloadable tvOS app?

**Comment by redphx** [comment]
Don't think so

**Comment by Julmik647** [comment]
You can try asking developer of Nexus+ for tvOS port.
Edit: [Developer of Nexus+ said that it's not possible, beacuse of no WebKit](https://gist.github.com/KhaosT/a4d90479e3cb0aae959ad55b08cd8358?permalink_comment_id=5608551#gistcomment-5608551) (browser engine used by Safari) [support on tvOS](https://gist.github.com/KhaosT/a4d90479e3cb0aae959ad55b08cd8358?permalink_comment_id=5608551#gistcomment-5608551). Homever, [the app that you linked](https://github.com/Moballo-LLC/tvOS-Browser) probably uses some things that don't allow IT to be adden to App Store. Try asking developer of that App for Userscripts and/or extensions support.

**Comment by Julmik647** [comment]
You can try [OneCast](https://www.onecast.me/) instead.
As for Better xCloud: Apple doesn't allow to use Webkit on tvOS so it's not possible to have Better xCloud for Apple TV or at least it couldn't be able to be in App Store.
