### ISSUE TITLE
[Feature] Force/bypass fullscreen

### ISSUE THREAD

**Issue by 0xSkyla** [redphx/better-xcloud#608]
### Device

Desktop

### Suggestion

A checkbox to stop xbox from checking if the window is in fullscreen

**Comment by redphx** [comment]
Screenshot?

**Comment by Sofyanes2** [comment]
Why dis you answer him and not me :(

**Comment by Sofyanes2** [comment]
Why did you answer him and not me :(

> Screenshot?

**Comment by KingNothing81** [comment]
> ### Device
> Desktop
> 
> ### Suggestion
> A checkbox to stop xbox from checking if the window is in fullscreen

Have you already tried to achieve this by using one of the Smart TV UA profiles?

**Comment by 0xSkyla** [comment]
> > ### Device
> > Desktop
> > ### Suggestion
> > A checkbox to stop xbox from checking if the window is in fullscreen
> 
> Have you already tried to achieve this by using one of the Smart TV UA profiles?

doesnt work, i want to use mouse and keyboard

**Comment by redphx** [comment]
#373
