### ISSUE TITLE
[Feature] Adjust timeout when using Remote Play

### ISSUE THREAD

**Issue by ForceConstant** [redphx/better-xcloud#613]
### Device

Desktop

### Suggestion

I can understand having a short timeout when playing with public servers, but when streaming from my own xbox, the timeout seems very short like 5 minutes before it asks me if I am still there. Anyway to adjust this?

**Comment by redphx** [comment]
This feature had been implemented a long time ago and it's still working for me.

**Comment by ForceConstant** [comment]
@redphx cool, I didn't see this mentioned anywhere. So is timeout completely disabled?

**Comment by ForceConstant** [comment]
@redphx can you clarify if this has really been implemented? Because I am still getting timeout today. More details is I get "Xbox is going to power off" after like 15 mins even though I have power off set to 6hr.
