### ISSUE TITLE
[Bug] RTX Video Enhancement Inactive 

### ISSUE THREAD

**Issue by cbeauch** [redphx/better-xcloud#616]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### xCloud officially supports your country/region

Yes

### The bug doesn't happen when you disable Better xCloud script

Yes

### Previous Better xCloud versions didn't have this bug (name which one)

No

### Device

Desktop

### Device

My-PC

### Operating System

WIndows 11 

### Android app/Browser Version

Chrome 131.0.6778.205

### Better xCloud Version

6.0.7

### Reproduction Steps

I want to use Better Xcloud's stream quality options and RTX Super Resolution. 

To replicate 
- **Enable** Better Xcloud 
- Launch game 
- Look at NVIDIA Control Panel 
- See Super Resolution is **inactive**

- **Disable** Better Xcloud 
- Launch game 
- Look at NVIDIA Control Panel 
- See Super Resolution is **active**

This occurs when everything in on default.

**Comment by redphx** [comment]
I don't have NVIDIA PC. And most likely this is a problem with NVIDIA and browser

**Comment by jcrgama** [comment]
It actually doesn't enable RTX Super Resolution and RTX HDR when the Better Xcloud plugin is enabled. It would be great if they worked together. I tested it on Opera, Edge and Chrome.

**Comment by jcrgama** [comment]
correction: it only works together with Opera GX, install Tampermonkey from the extension store itself. Chrome and Edge problem.
