### ISSUE TITLE
[Beta] Version 6.1 - Controller customization

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#617]
### 🐞 How to report bug
Include these info:  
- Device
- Script/Browser
- Screenshot/Video

### Android
- Open App settings > Better xCloud script variant > Beta

### Browser
- Install [this version](https://github.com/redphx/better-xcloud/raw/refs/heads/typescript/dist/better-xcloud.user.js)

## How to uninstall
If you wish to return to stable version, do the following steps:

### Android
- Clear app data

### Browser
1. Open Better xCloud settings > scroll to the bottom > Clear data. Do NOT refresh the page.
2. Close xCloud tab
3. Re-install Better xCloud script on the home page

### Added
- Add ability to customize controller buttons, trigger and sticks

### Changes
- Update style for selection boxes when not using controller-friendly UI
- Move controller's vibration instensity setting to the Controller customization feature

### Screenshots

![image](https://github.com/user-attachments/assets/fa227767-f4c1-493c-8f24-3bb86a716b89)

![image](https://github.com/user-attachments/assets/c71dfdb4-5810-4a4d-9ea5-d7e32b252bdf)

**Comment by KingNothing81** [comment]
Hi … I didn’t encounter bugs so far, but I see that adjusting controller vibration is now included in the controller customization options.

But this means that users can’t adjust vibration intensity anymore, without creating a new preset first. But will doing this also increase input latency, even if they don’t remap any other buttons? If yes, maybe it would be better to exclude the vibration intensity setting again?

But if you want to keep it this way, how about also including the polling rate setting? Because maybe some users also want to have controller / game specific polling rates.

Thanks.

**Comment by redphx** [comment]
The vibration uses the same code as before. "Slightly" = very very slightly unless your device is slow. 

Polling rate must be the same for all controllers.

**Comment by RudyBugy** [comment]
> * Update style for selection boxes when not using controller-friendly UI

New fields are not configured from the controller.

**Comment by redphx** [comment]
> New fields are not configured from the controller.

Explain???

**Comment by RudyBugy** [comment]
![image](https://github.com/user-attachments/assets/3cfb2bd7-01a1-479a-8f2a-aba39f73dbb0)
I can't select options using the controller.

and after pressing the green pencil the controller doesn't work in the menu that opens and there's no way to close it (only with the mouse)

**Comment by redphx** [comment]
Enable `Controller-friendly UI` setting if you want to control using controller

**Comment by RudyBugy** [comment]
I didn't find this setting

**Comment by redphx** [comment]
![image](https://github.com/user-attachments/assets/1f8ed0b3-7b82-415c-a241-9267b46a2f0e)

**Comment by RudyBugy** [comment]
thank you. now everything works.

in Russian translation this option is translated as "lightweight interface" and it is not clear what it is responsible for, so I did not use it and did not find it.

**Comment by RudyBugy** [comment]
![image](https://github.com/user-attachments/assets/754e67a2-f9de-49ca-954d-a73cf9a9157f)

trifle. The camera emoji is displayed as an empty square.

**Comment by redphx** [comment]
> trifle. The camera emoji is displayed as an empty square.  

Fixed. Reinstall the script.

**Comment by RudyBugy** [comment]
Good 

![image](https://github.com/user-attachments/assets/7cd11e35-de55-4a7b-bad8-ce1d15f01807)

**Comment by redphx** [comment]
beta-2:
- Add summary (mapping only)
- Only show latency note when changing mapping or ranges/deadzones. Only changing vibration intensity doesn't affect latency.
- Bug fixes

![image](https://github.com/user-attachments/assets/0eb92842-0dd1-4513-9c7b-564fa022552e)
