### ISSUE TITLE
[Feature] Integration with Greenlight

### ISSUE THREAD

**Issue by KillzTheSpy2** [redphx/better-xcloud#621]
### Device

Desktop

### Suggestion

I use greenlight to stream my xbox, and it would be pretty helpful if i could use keyboard and mouse for streaming. I know its a big ask, and a big job, but it would be so good. The "greenlight" im talking about is this: [https://github.com/unknownskl/greenlight](url)
Even if all features aren't ported over, i'd still just enjoy the option of using a virtual controller with keyboard and mouse.

**Comment by redphx** [comment]
What do you mean? You can use virtual controller with remote play.

**Comment by KillzTheSpy2** [comment]
> What do you mean? You can use virtual controller with remote play.

How?

**Comment by redphx** [comment]
![image](https://github.com/user-attachments/assets/4e7c0407-673b-4756-acdf-440fed0e2428)

**Comment by KillzTheSpy2** [comment]
yes i know you can do that, but im talking about a different app. I use Greenlight to remote play on my xbox, so i can play games unsupported by cloud gaming, but i cant use keyboard and mouse as a virtual controller.
