### ISSUE TITLE
[Feature] Add ability to play Genshin impact with a controller on Better xcloud with a controller

### ISSUE THREAD

**Issue by MotorStorm891** [redphx/better-xcloud#622]
### Device

Phone/Tablet

### Suggestion

Genshin Impact only plays tactile  on Xbox cloud gaming on android feature ( smartphone, Nintendo switch android partition).
Is it possible to add the possibility of using a controller with an emulation remapping or like for the trick of fortnite (  option of console version), here it could be the PC version available for android devices.

I've seen that Genshing impact streaming only play in 720 even if 1080 is "on". Strange.
:)
Have a nice days

**Comment by redphx** [comment]
I believe there is a setting in Genshin that allows playing with controller
