### ISSUE TITLE
[Feature] Touch controller hold to toggle

### ISSUE THREAD

**Issue by F3niIxX** [redphx/better-xcloud#625]
### Device type

Phone/Tablet

### Device

touch screen android/any 

### Suggestion

Ability to hold the analog sticks .... Just like on cod mobile/pubg for example or if you hold LS/RS for some time the button is always pressed double tap or something similar.... Good when playing some games that u have to run by pressing LS

**Comment by redphx** [comment]
Only possible with custom touch control: https://github.com/redphx/better-xcloud/wiki/How-to-create-custom-touch-control-layout
