### ISSUE TITLE
[Feature] Add controller vibration in Android extension

### ISSUE THREAD

**Issue by ruanraco** [redphx/better-xcloud#63]

**Comment by dolphin-hacker** [comment]
please let me know if I can help with this one in any way, really missing this feature

**Comment by redphx** [comment]
Thanks, I'll try to implement it soon.

**Comment by DVergil** [comment]
There is a flag in Google Chrome that might help with this

**Comment by DVergil** [comment]
but a direct activation of Rumble in xcloud itself might be better

**Comment by dolphin-hacker** [comment]
I think I may have stumbled upon that flag as well when troubleshooting but it's been a while, which one is it

**Comment by redphx** [comment]
Added in 2.1

**Comment by dolphin-hacker** [comment]
Dude you are the man!!!!
