### ISSUE TITLE
[Bug] Video Settings does not work with Clarity Boost On

### ISSUE THREAD

**Issue by ricardo404** [redphx/better-xcloud#64]
Red, I don't know if you already know, but with Clarity Boost turned on, the video adjustment options (Contrast, Saturation...) Does not work.

Amend this issue clears my doubts: The more objects we see in Xcloud, for example, moving objects, with a lot of details, can cause FPS loss in WEBRTC on old computers?

**Comment by ricardo404** [comment]
See, brightness at 50%, Clarity Boost off, note brightness is indeed low.

![Screenshot_16](https://github.com/redphx/better-xcloud/assets/35298519/7f379801-4ffc-432f-90c0-94a5a48a8db9)




Clarity Boost on, no practical effect on brightness adjustment.

![Screenshot_17](https://github.com/redphx/better-xcloud/assets/35298519/1c1dc4e0-3541-4e58-aa26-38f2620de149)

**Comment by redphx** [comment]
I already talked about this in the FAQ. It won't be possible.

**Comment by redphx** [comment]
I don't think this can be fixed. I don't have a Windows device to test atm.

**Comment by ricardo404** [comment]
So sad.

**Comment by redphx** [comment]
Better xCloud uses the CSS property `filter` to change the brightness/saturation/contrast. These values were ignored by the browser when the Clarity Boost feature was ON.  

Maybe it was an oversight from Edge when implementing this feature.
