### ISSUE TITLE
[Bug] 1.10

### ISSUE THREAD

**Issue by ricardo404** [redphx/better-xcloud#69]
Red, I went to test 1.10 and this happened:

![image](https://github.com/redphx/better-xcloud/assets/35298519/fc1418b0-1bf1-40a5-8109-0500dce910d9)

![image](https://github.com/redphx/better-xcloud/assets/35298519/ee7da5cd-717f-4223-8581-dba7bb4cea15)

**Comment by ricardo404** [comment]
The useragent option is stuck at the top start playing and at the very bottom is the rocket loading screen. It basically took up most of the screen space.

**Comment by redphx** [comment]
It should be fixed now. Please re-install the version 1.10.  
Thanks for reporting.
