### ISSUE TITLE
[Feature] PC Browser - Start in fullscreen after the play button is pressed 

### ISSUE THREAD

**Issue by johnnyslt** [redphx/better-xcloud#71]
When playing from a PC Browser, it would nice if you can make an option to enter the game  in fullscreen mode automatically, and exit when you quit the game.

Thanks !

**Comment by redphx** [comment]
Nice idea.

**Comment by redphx** [comment]
It's not possible to automatically activate the fullscreen mode without user interactions (click, key press, ...).  
Maybe clicking the mouse once while playing to activate it?

**Comment by johnnyslt** [comment]
Hi,

Which ever works, without breaking other functions.

Or maybe a joystick buton press in the 1st 15-20 sec when the game loads?
Keeping the listener longer might break the gaming.

Maybe other people have a different suggestion.

Thanks !

lun., 7 aug. 2023, 13:41 redphx ***@***.***> a scris:

**Comment by redphx** [comment]
You can't activate it with gamepad, only mouse or keyboard. But then you could just press F11?
