### ISSUE TITLE
[Bug] Battery level badge stuck at 100% on iOS 16.6

### ISSUE THREAD

**Issue by ILikePlayingGames** [redphx/better-xcloud#75]
The in-game battery badge in the stream menu is constantly 100% despite the iPhone battery level being different

**Comment by redphx** [comment]
It shouldn't be showing. Safari doesn't support getting device's battery level.

**Comment by ILikePlayingGames** [comment]
Oh I didn’t know WebKit did not support it. https://trac.webkit.org/changeset/208300/webkit

The badge is hidden correctly.

**Comment by redphx** [comment]
You can use this page for reference: https://caniuse.com/battery-status  

I thought it was bugged? It shouldn't be showing when the battery level is 100%

**Comment by ILikePlayingGames** [comment]
No, it’s being hidden correctly. I was just wondering about whether battery could be supported on iOS. Sorry for the confusion
