### ISSUE TITLE
[Bug] 404 on iOS 16.6 after updating to v1.10.1

### ISSUE THREAD

**Issue by ILikePlayingGames** [redphx/better-xcloud#76]
Trying to access xCloud produced error 404 after updating to better xcloud v1.10.1. The error cleared after about 10 refreshes.

**Comment by ILikePlayingGames** [comment]
better xcloud settings:
`
block_social_features: false
block_tracking: true
disable_bandwidth_checking: false
hide_dots_icon: true
prefer_ipv6_server: false
reduce_animations: false
screenshot_button_position: "bottom-left"
server_region: "default"
skip_splash_video: false
stats_conditional_formatting: false
stats_opacity: 80
stats_position: "top-left"
stats_quick_glance: false
stats_show_when_playing: false
stats_text_size: "0.9rem"
stats_transparent: false
stream_hide_idle_cursor: false
stream_preferred_locale: "default"
stream_simplify_menu: true
stream_target_resolution: "auto"
stream_touch_controller: "default"
user_agent_custom: ""
user_agent_profile: "default"
use_desktop_codec: false
version_current: "1.10.1"
version_last_check: [1691365032](tel:1691365032)
version_latest: "1.10.1"
video_brightness: 100
video_contrast: 100
video_fill_full_screen: false
video_saturation: 100
`

**Comment by redphx** [comment]
Please use only this issue for this 404 error: https://github.com/redphx/better-xcloud/issues/78
