### ISSUE TITLE
[Bug] Error message when using the User-Agent switching feature

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#78]
If you run into the error page from time to time, try to switch the "User-Agent profile" to default.  

Still investigating the problem.

**Comment by redphx** [comment]
@ILikePlayingGames I think changing User-Agent doesn't provide benefits anymore. You might want to switch it back to default.

**Comment by ILikePlayingGames** [comment]
In #76 the user agent was default and it still got the 404 error.

**Comment by redphx** [comment]
You'll get the error page when this request fails.  

<img width="724" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/6680b4ac-3091-4d56-b210-e8c97537edfb">

It's bugged when this URL is requested:  
```
https://emerald.xboxservices.com/xboxcomfd/experimentation?platform=iOS&appVersion=1.1.2308.0701&env=prod&locale=
```

but not this one:
```
https://emerald.xboxservices.com/xboxcomfd/experimentation?deviceId=...&clientIp=...&platform=macOS&appVersion=1.1.2308.0701&env=prod&locale=en-US
```

I'm not sure why sometimes it switches between the two.

**Comment by redphx** [comment]
I think this and #80 issues happened because the Userscripts extension is bugged.  

Better xCloud has `@run-at` flag set to `document-start`, which means it should start before anything else in the web page.  

When it works it should look like this:  
<img width="441" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/1ae96a9c-7344-45fe-9bdf-0da44f0597d1">
  
But sometimes it was initialized after the page was loaded, which led to unexpected errors:  

<img width="425" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/75241fc3-2f30-471e-afa2-0995fb0e0574">

There is nothing I can do until Userscripts devs fix this bug.

**Comment by redphx** [comment]
Bug reported: https://github.com/quoid/userscripts/issues/529
