### ISSUE TITLE
[Bug] Crashes with Kiwi Browser (Android)

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#8]
Some users report that the script doesn't work with Kiwi Browser (crashes when trying to play).  
I don't use this browser personally so it's gonna be in a low-priority list.  

I still recommend using Better xCloud with Firefox/Hermit on Android.

**Comment by danfozzy** [comment]
Tried 1.3.2, same crashing issue. To try rule out the issue being with tampermonkey on kiwi browser, is there any other script extension that I could test other than tampermonkey?

**Comment by redphx** [comment]
I could be wrong, but I think Kiwi isn't using the latest Chromium version (105 vs 114).

**Comment by redphx** [comment]
> Error: WebRtcStream: Connect. Error:InvalidModificationError: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver': Invalid codec preferences: invalid codec with name "H264".

Kiwi Browser doesn't support the H264 high quality codec profile.

**Comment by redphx** [comment]
Fixed in [1.4.1](https://github.com/redphx/better-xcloud/releases/tag/v1.4.1)
