### ISSUE TITLE
[Bug] Not working properly with Safari

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#81]
Edit: workaround implemented in 1.11  

Better xCloud needs to be excecuted before the page load to be working properly. That's why it has `@run-at document-start` flag. It works great with Tamperscript.  

But this feature is currently bugged/not working as intended on Usercripts for Safari (the devs know this). According to [their document](https://violentmonkey.github.io/api/metadata-block/#run-at), the script isn't always injected to the page before anything else, and this leads to unexpected errors & broken features (#78 and #80 for example).  

<img width="710" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/5f9848b1-04a6-4308-80e8-68eb381f0296">

This is a limitation of Userscripts for Safari and they are trying to fix it. But in the meantime I'll have to come up with a workaround.  

If you're on macOS I'd recommend using xCloud on Chrome/Edge instead. For iOS/iPadOS, wait for a patch. You can still use it but some of the features may not work properly.

**Comment by redphx** [comment]
@ILikePlayingGames please test this version: https://github.com/redphx/better-xcloud/blob/feature/safari_fix/better-xcloud.user.js  

I only tested it on Mac and it worked for me.  

- The Settings button should appear everytime
- You're less likely to get the error page.
- The User-Agent feature won't work reliably.
- Everything else should work.  
- Help me test the "touch controller for all games" feature.

Thanks.

**Comment by redphx** [comment]
Please also test the 1080p setting

**Comment by redphx** [comment]
I think this solution works everytime: instead of using https://xbox.com/play, use this link: https://www.xbox.com/auth/msa?action=logIn&returnUrl=https%3A%2F%2Fwww.xbox.com%2Fplay&prompt=none  

It will give the Userscripts extension enough time to inject the script before the page load. The downside is you'll have to wait ~5s because of the log in process.

**Comment by redphx** [comment]
Implemented a work around in v1.11

**Comment by ILikePlayingGames** [comment]
Thanks! The automatic refreshing is working for me

**Comment by ILikePlayingGames** [comment]
I noticed that the script will not start automatically if I go to http://xbox.com/play when logged out and then log in on the page. The script starts after I reload the page once after logging in. Can you please check if it's possible to make the script start when xCloud finishes logging in?

**Comment by iosman212** [comment]
[NewStyle-5r5oem24.css.txt](https://github.com/user-attachments/files/20846370/NewStyle-5r5oem24.css.txt)
