### ISSUE TITLE
[Feature] Force Mic On

### ISSUE THREAD

**Issue by Haisom** [redphx/better-xcloud#86]
**I'm using:**  
- Device: PC
- OS: Windows 11
- Browser: Edge
  
**I want to suggest this feature:**  
Enable microphone on game launch, if possible.

Thank you!

**Comment by redphx** [comment]
I was able to enable the mic, but how do I check whether it works or not? Which game has a mic check feature in the settings?

**Comment by Haisom** [comment]
I think the fastest way to test is by playing either GTA Online or Battlefield 2042
Both have indicators for when your voice is detected
