### ISSUE TITLE
[Bug] Safari can't go fullscreen.

### ISSUE THREAD

**Issue by dianranVIP** [redphx/better-xcloud#90]
iphone ios15.5 Safari
better-xcloud 1.10.2
Safari cannot go full screen.
Before, I only opened a webpage, and then turned the phone horizontally to enter the full screen, but now it doesn't work.
On the page outside the game, the full screen can still be achieved by turning the mobile phone horizontally, but after entering the game, the full screen cannot be achieved by turning the mobile phone horizontally.

**Comment by redphx** [comment]
Does it work when you disable the script? What was the last version that it worked?

**Comment by dianranVIP** [comment]
I recorded a video, please take a look, I tried to install all the scripts of lower versions,even disable the script , still can't display in full screen, but iphone didn't have this problem before, believe me, this is a recent phenomenon, hope it can be resolved method, thank you.

https://youtu.be/FaflEmwPJRQ

**Comment by redphx** [comment]
If disabling the script doesn't make the bug go away then it's a bug from the xCloud website. Please report it to them.
