### ISSUE TITLE
[Bug] Video settings

### ISSUE THREAD

**Issue by ghost** [redphx/better-xcloud#92]
### Bug in the "Video settings"
**Platform**
 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Microsoft Edge Canary]
 - Browser Version: [117]
 - Better xCloud Version: [1.11]

**Describe the bug**
When I increase or decrease any of the 3 video options it zooms in on the game screen

**Screenshots/Videos**

https://github.com/redphx/better-xcloud/assets/115114046/bf0e2e65-e4cd-4650-ae2b-fe6b0704bd5f

**Comment by redphx** [comment]
Are you using any other extensions?

**Comment by pedrohenrique-bragap** [comment]
> Are you using any other extensions?

AdBlock, Lightshot, AIPRM For ChatGPT, Enpass - password manager and OCR - Image Reader

**Comment by ghost** [comment]
> Are you using any other extensions?

AdBlock, Lightshot, AIPRM For ChatGPT, Enpass - password manager and a OCR - Image Reader

**Comment by redphx** [comment]
<img width="321" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/5e785654-0f87-4c54-a5e3-3eb0155a757c">
<img width="321" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/96beeb59-7683-45c4-91be-4ec8b23bd5d4">

Something is wrong. When the video is zoomed in, part of the System menu bar is cropped.  
I think it's more likely a rendering bug of the browser
