### ISSUE TITLE
[Bug] Screenshot Button don't appear

### ISSUE THREAD

**Issue by Mondazul** [redphx/better-xcloud#97]
**Platform**
 - Device: Phone
 - OS: Android 
 - Browser: Kiwi
 - Browser Version:116.0
 - Better xCloud Version: 1.12

**Describe the bug**
...the screenshot button doesn't work, as you can see in the image the game is running in fullscreen so nothing is possibly blocking the button.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.
![Screenshot_2023-08-13-02-25-52-735_com.kiwibrowser.browser.jpg](https://github.com/redphx/better-xcloud/assets/142168895/5e3c8bf5-0317-424a-bf22-97bcce1a572b)

**Comment by redphx** [comment]
Are you using another script for the touch controller? Maybe it was displayed in front of the screenshot button, that's why you couldn't press on it. Try to disable that script.

**Comment by Mondazul** [comment]
nope, it didn't fix the problem. I remember in the update where you added the option to choose between 1080p and 720p the button worked

**Comment by redphx** [comment]
https://github.com/redphx/better-xcloud/blob/main/better-xcloud.user.js#L1781

<img width="337" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/d2b85c75-e593-47ea-bff3-f201581a18a2">

Try to change these lines to:  
```css
.better-xcloud-screenshot-button {
    display: block;
    opacity: 1;
```

Refresh the page and see where the screenshot button is
